Fix/minting prop weight
UniqueNetwork/unique-chain pull request #1000
Opened 2023-09-25 15:01 UTC by mrshiposha

2023-09-25 15:23 UTC, mrshiposha commented
Тесты по весам упадут, т.к. я сделал тестовый бенч nft/rft, но не проводил каллибровку. Надо провести бенч на бенч-хосте

2023-09-26 08:20 UTC, CertainLach requested changes

2023-09-26 08:20 UTC, CertainLach commented on pallets/nonfungible/src/weights.rs
>  	/// Proof: Common CollectionPropertyPermissions (max_values: None, max_size: Some(16726), added: 19201, mode: MaxEncodedLen)
Если проперти нет, то зачем оно читается?

2023-09-26 08:20 UTC, CertainLach commented on pallets/nonfungible/src/weights.rs
> +		Weight::from_parts(612_529, 20191)
Базовая стоимость в 10 раз меньше!

2023-09-26 08:20 UTC, CertainLach commented on pallets/nonfungible/src/lib.rs
> +			TokenPropertiesT::new()
debug_assert!(get().is_empty())

2023-09-26 08:20 UTC, CertainLach commented on .docker/Dockerfile-chain-dev
> +CMD cargo run --profile integration-tests --features=${NETWORK}-runtime -- --dev -linfo --rpc-cors=all --unsafe-rpc-external
Лучше разбей обратно на build и run, чтобы сборка то кеширована была, а не происходила при каждом запуске.
Также тут healthcheckи будут с ума сходить (внешние)

2023-09-26 09:33 UTC, mrshiposha commented on pallets/nonfungible/src/weights.rs
>  	/// Proof: Common CollectionPropertyPermissions (max_values: None, max_size: Some(16726), added: 19201, mode: MaxEncodedLen)
Надо проверять имеет ли отправитель право то или иное проперти выставлять. А это мы можем понять только если прочитаем их permissions

2023-09-26 09:35 UTC, mrshiposha commented on pallets/nonfungible/src/weights.rs
> +		Weight::from_parts(612_529, 20191)
Полагаю это результат того, что я бенчил на своей собственной машине :)

2023-09-26 09:46 UTC, CertainLach commented on pallets/nonfungible/src/weights.rs
>  	/// Proof: Common CollectionPropertyPermissions (max_values: None, max_size: Some(16726), added: 19201, mode: MaxEncodedLen)
Так у нас в этом бенчмарке не выставляются проперти

2023-09-26 09:46 UTC, CertainLach commented on pallets/nonfungible/src/weights.rs
> +		Weight::from_parts(612_529, 20191)
В остальных разница не такая большая

2023-09-26 09:47 UTC, mrshiposha commented on pallets/nonfungible/src/weights.rs
>  	/// Proof: Common CollectionPropertyPermissions (max_values: None, max_size: Some(16726), added: 19201, mode: MaxEncodedLen)
А, стоп. Я о другом бенче подумал. Интересно.

2023-09-26 09:56 UTC, mrshiposha commented on pallets/nonfungible/src/lib.rs
> +			TokenPropertiesT::new()
А с другой стороны, оно нам надо? Мы же гарантированно создаем токен и даже если что-то лежит, мы в любом случае это перепишем

2023-09-26 10:28 UTC, mrshiposha commented on pallets/nonfungible/src/weights.rs
>  	/// Proof: Common CollectionPropertyPermissions (max_values: None, max_size: Some(16726), added: 19201, mode: MaxEncodedLen)
Done

2023-09-26 10:28 UTC, mrshiposha commented on .docker/Dockerfile-chain-dev
> +CMD cargo run --profile integration-tests --features=${NETWORK}-runtime -- --dev -linfo --rpc-cors=all --unsafe-rpc-external
Done

2023-10-02 15:24 UTC, CertainLach requested changes

2023-10-02 15:24 UTC, CertainLach commented on pallets/fungible/src/common.rs
> +	fn set_token_properties_map(&self, _token_id: TokenId, _map: up_data_structs::TokenProperties) {
Кажется что этот метод стоит назвать _raw, чтобы никто не подумал что его сильно напрямую использовать

2023-10-02 15:24 UTC, CertainLach commented on pallets/nonfungible/src/common.rs
> +	fn properties_exist(&self, token: TokenId) -> bool {
В PoV нет отдельной ноды для "наличие этого ключа было проверено", проверка наличия считается как чтение. Возможно get_ стоит сделать чтобы возвращал Option?

2023-10-02 15:24 UTC, CertainLach commented on pallets/nonfungible/src/common.rs
> +	fn properties_exist(&self, token: TokenId) -> bool {
По времени оно тоже много занимает, поскольку 2 раза идёт поиск по бд, и т.к это лишь проверка - то в кеш значений оно не попадает для чтения.
Т.е нужно изменить на OptionQuery

2023-10-02 15:24 UTC, CertainLach commented on pallets/refungible/src/lib.rs
> -				if balance != total_pieces {
Кажется эта проверка забыта?

2023-10-02 15:24 UTC, CertainLach commented on pallets/structure/src/weights.rs
> +		Weight::from_parts(7_578_000, 4325)
Хм, интересно почему. У нас для поиска читалась какая-то большая информация для токенов, которая однако погружалась в коде инициализации бенчмарка? Да вроде не похоже...

2023-10-02 15:24 UTC, CertainLach commented on primitives/common/src/constants.rs
> +pub const WEIGHT_TO_FEE_COEFF: u64 = /*<weight2fee>*/77_334_604_063_436_322/*</weight2fee>*/;
Изменение во втором и третьем знаке! 🎉

2023-10-02 15:24 UTC, CertainLach commented on tests/src/migrations/correctStateAfterMaintenance.ts
> +const WS_ENDPOINT = 'ws://127.0.0.1:9944';
Ай, так это у нас из тестов вызывается, вот почему оно в релизном ci падало!
Изменени пожалуйста на config.ta

2023-10-02 15:24 UTC, CertainLach commented on tests/src/performance.test.ts
> +    expect(results).to.be.deep.equal([
Это наверное seq test должен быть, в параллельных не факт что такие результаты будут

2023-10-02 15:40 UTC, mrshiposha commented on pallets/refungible/src/lib.rs
> -				if balance != total_pieces {
Эм, она есть. Копировал как есть. Сейчас еще перепроверил, на всякий случай.

2023-10-02 16:07 UTC, mrshiposha commented on pallets/fungible/src/common.rs
> +	fn set_token_properties_map(&self, _token_id: TokenId, _map: up_data_structs::TokenProperties) {
Done

2023-10-02 16:07 UTC, mrshiposha commented on pallets/nonfungible/src/common.rs
> +	fn properties_exist(&self, token: TokenId) -> bool {
Done

2023-10-02 16:07 UTC, mrshiposha commented on tests/src/migrations/correctStateAfterMaintenance.ts
> +const WS_ENDPOINT = 'ws://127.0.0.1:9944';
Done

2023-10-02 16:07 UTC, mrshiposha commented on tests/src/performance.test.ts
> +    expect(results).to.be.deep.equal([
Done

2023-10-02 16:14 UTC, CertainLach requested changes

2023-10-02 16:15 UTC, mrshiposha commented on pallets/nonfungible/src/erc.rs
> +			<TokenProperties<T>>::get((self.id, token_id)).ok_or("Token properties not found")?;
Я скопировал эту штуку из другого места этого файла. Там много таких сообщений с большой буквы. Поправить?

2023-10-02 16:18 UTC, CertainLach commented on Makefile
> +	cargo run --profile production --features runtime-benchmarks,$(RUNTIME) -- \
Я подумал, а зачем мы вообще это кучу раз компилируем...
У нас там перед каждым бенчмарком палеты ноду снова пересобирает, и я только что понял что она пересобирает - у нас изменяется weights.rs, и оно собирает ноду с новыми весами.

По идее тут нужно один раз ноду собрать, и потом вызывать `./unique-collator benchmark ...`

Что тут однако не выйдет сделать, поскольку у нас рекурсивный make.
Сейчас unactionable, но способ оптимизации ясен.

2023-10-02 16:27 UTC, CertainLach requested changes
Ещё один нитпик и можно принимать

2023-10-02 16:27 UTC, CertainLach commented on node/cli/src/service.rs
> +		let interval = tokio::time::interval(Duration::from_millis(interval));
Duration должен на самом высоком уровне создаваться, т.е из cli получаем u64, а дальше везде по коду Duration

2023-10-02 16:27 UTC, CertainLach commented on pallets/common/src/lib.rs
> +	fn compute_value_if_not_already(&mut self) {
Длинно и не так понятно)
Может `force()` назвать, как в FP принято?

2023-10-02 16:27 UTC, CertainLach commented on pallets/nonfungible/src/erc.rs
> +			<TokenProperties<T>>::get((self.id, token_id)).ok_or("Token properties not found")?;
Да, неправильно что у нас где-то просочились большие буквы, но я иногда это не замечаю)

2023-10-02 16:28 UTC, mrshiposha commented on node/cli/src/service.rs
> +		let interval = tokio::time::interval(Duration::from_millis(interval));
Ну да, однако другую штуку (delay) я не могу обернуть в Duration, т.к. субстратный интерфейс предоставляет только u64. Для консистентности я решил все перевести на u64.

Просто это используется исключительно здесь, и нигде не будет больше использоваться

2023-10-02 16:30 UTC, mrshiposha commented on pallets/common/src/lib.rs
> +	fn compute_value_if_not_already(&mut self) {
Мб `force_value()` тогда?

2023-10-02 16:40 UTC, mrshiposha commented on pallets/refungible/src/erc.rs
> +		let props =
Done

2023-10-02 17:02 UTC, CertainLach commented on pallets/common/src/lib.rs
> +	fn compute_value_if_not_already(&mut self) {
Можно

2023-10-02 17:04 UTC, CertainLach commented on pallets/refungible/src/common.rs
> +		Ok(is_bundle_owner)
```suggestion
		<PalletStructure<T>>::check_indirectly_owned(
			maybe_owner.clone(),
			self.id,
			token,
			None,
			nesting_budget,
		)
```

2023-10-02 17:05 UTC, CertainLach commented on pallets/refungible/src/common.rs
> +		Ok(is_bundle_owner)
(clippy на это жалуется)

2023-10-02 19:20 UTC, merged