Add typing to polkadot queries and events
UniqueNetwork/unique-chain pull request #1001
Opened 2023-09-26 22:31 UTC by fairax

2023-09-28 09:20 UTC, CertainLach commented on tests/src/collator-selection/identity.seqtest.ts
> +  return typeof obj == 'object' && 'registry' in obj;
obj instanceof Codec, не?

2023-09-28 09:20 UTC, CertainLach commented on tests/src/collator-selection/identity.seqtest.ts
> +    function equal(this: any, _super: any) {
Неплохо, но надо бы это для всех тестов включить (глобальный before/вообще без обёрток)

2023-10-02 08:32 UTC, CertainLach requested changes

2023-10-09 10:11 UTC, CertainLach commented on tests/src/collator-selection/identity.seqtest.ts
> +      const registry = helper.getApi().registry;
Почему бы не переименовать поле api в _api/#api, и не создать getter?

2023-10-09 10:35 UTC, CertainLach commented on tests/src/collator-selection/identity.seqtest.ts
> +      const registry = helper.getApi().registry;
В плане,
```
#api?: ApiPromise;
get api(): ApiPromise {
   if(this.#api) return this.#api;
   this.#api = ApiPromise.create(...);
   return this.#api;
}
```

Чтобы не писать везде getApi(), это некрасиво)

2023-10-09 10:45 UTC, uandysmith commented on tests/src/collator-selection/identity.seqtest.ts
> +      const registry = helper.getApi().registry;
Там в текущей реализации бросает эксцепшен, если коннекта нет, это как раз то поведение, которое хочется сохранить. Через геттеры вроде не очень эксцепшенами бросаться

2023-10-09 10:48 UTC, CertainLach commented on tests/src/collator-selection/identity.seqtest.ts
> +      const registry = helper.getApi().registry;
Какая разница, эксепшон оно кинет, или руганётся на undefined в случае с .api!
У нас коннекшон есть в 99% случаев, я не думаю что ради этого стоит весь код в таком стиле писать

2023-10-09 10:49 UTC, uandysmith commented on tests/src/collator-selection/identity.seqtest.ts
> +      const registry = helper.getApi().registry;
У нас - да, однако в скриптах хелпер инициализируется самостоятельно, без using. 
Это оттуда пошло и опять же хочу сохранить для пакета.

2023-10-09 11:02 UTC, uandysmith commented on tests/src/collator-selection/identity.seqtest.ts
> +      const registry = helper.getApi().registry;
Потом в скриптах у меня было часто
```
const api = helper.getApi();
```
Что не так красиво, обращаясь к его свойству

2023-10-09 11:28 UTC, CertainLach commented on tests/src/collator-selection/identity.seqtest.ts
> +      const registry = helper.getApi().registry;
Ну вот да, с get методом напрашивается сделать один раз получение
А если геттером сделать - то можно код как есть оставить

2025-03-13 14:07 UTC, closed without merging

2025-03-13 14:07 UTC, vklachkov commented
Should be rewritten after https://github.com/UniqueNetwork/unique-chain/pull/1102