Upgrade to polkadot 1.1.0
UniqueNetwork/unique-chain pull request #1004
Opened 2023-10-02 22:31 UTC by CertainLach

2023-10-03 16:29 UTC, mrshiposha requested changes

2023-10-03 16:29 UTC, mrshiposha commented on primitives/data-structs/src/lib.rs
>  pub enum MetaUpdatePermission {
Судя по всему, мы могли бы это убрать, все миграции релеватные давно прошли

2023-10-03 16:29 UTC, mrshiposha commented on runtime/common/config/pallets/scheduler.rs
>  // You should have received a copy of the GNU General Public License
По идее, этот файл надо тоже удалить

2023-10-03 16:29 UTC, mrshiposha commented on runtime/common/config/substrate.rs
> +	type AllowMultipleBlocksPerSlot = ConstBool<true>;
О! А это ли не та штука, которая включает async backing с нашей стороны?

2023-10-03 16:30 UTC, mrshiposha commented
@CertainLach в основном только вопросы и пара nitpicks

2023-10-03 17:28 UTC, CertainLach commented on Cargo.toml
> +orml-tokens = { default-features = false, git = "https://github.com/moonbeam-foundation/open-runtime-module-library", branch = "upgrade-to-polkadot-v1.1.0" }
PR ещё не принят, но там всё в целом ок.

2023-10-03 17:29 UTC, CertainLach commented on Cargo.toml
> +exclude = ['pallets/scheduler-v2']
Yep, забыл.

2023-10-03 17:29 UTC, CertainLach commented on README.md
> +TODO
Там речь про парачейны, а не про dev режим
Справку по dev режиму можно отдельной секцией сделать.

2023-10-03 17:31 UTC, CertainLach commented on node/cli/Cargo.toml
> +fc-api.workspace = true
По идее такое taplo должен уметь, но я не вижу у него опции этой.
Могу в deppatcher написать форматирование такого, по идее не сложно)

2023-10-03 17:32 UTC, CertainLach commented on node/cli/Cargo.toml
> +lookahead = []
lookahead коллатор включается, да. Оно хочет новый рантайм реле, пока только в dev окружении можно собирать

2023-10-03 17:35 UTC, CertainLach commented on node/cli/src/service.rs
> +				pending_create_inherent_data_providers: |_, ()| async move { Ok(()) },
Во frontier появилась возможность pending блок смотреть, а для pending блока нужны inherents.
У нас нет inherentов, которые эфиру могут быть полезны (Разве что вдруг timestamp станем предоставлять? Хотя он слишком non-deterministic), поэтому тут пусто.
Можно было бы использовать тот же CIDP что и для ауры, но с новым апи cumulus он там тоже пустой (Создание inherent timestamp и paras скрыто за абстракцией)

2023-10-03 17:35 UTC, CertainLach commented on node/cli/src/service.rs
> +		RequireSecondedInBlockAnnounce::new(relay_chain_interface.clone(), para_id);
Это просто переименовали, BlockAnnounceValidator - тайпалиас для RequireSecondedInBlockAnnounce

2023-10-03 17:37 UTC, CertainLach commented on pallets/evm-transaction-payment/src/lib.rs
> +		base_fee <= gas_fee && gas_fee <= base_fee * 21 / 10
Комментарий бы тут оставить надо, да. По требованиям у нас спонсироваться должны транзакции, которые в 2 раза дороже чем надо (Metamask по дефолту цену в 2 раза завышает)
Однако мы оставили leeway (Я его предлагал убрать, и андрей вроде согласился, и о нём забыли), а потому мы разрешили спонсировать транзакции в 2.1 раза дороже, отсюда * 21 / 10

2023-10-03 17:38 UTC, CertainLach commented on pallets/evm-transaction-payment/src/lib.rs
> +		base_fee <= gas_fee && gas_fee <= base_fee * 21 / 10
Это условие у нас раньше во frontier было.

2023-10-03 17:39 UTC, CertainLach commented on runtime/common/config/substrate.rs
> +	type AllowMultipleBlocksPerSlot = ConstBool<true>;
```
Whether to allow block authors to create multiple blocks per slot.

If this is true, the pallet will allow slots to stay the same across sequential blocks. If this is false, the pallet will require that subsequent blocks always have higher slots than previous ones.

Regardless of the setting of this storage value, the pallet will always enforce the invariant that slots don’t move backwards as the chain progresses.

The typical value for this should be ‘false’ unless this pallet is being augmented by another pallet which enforces some limitation on the number of blocks authors can create using the same slot.
```

Async backing у нас в любом случае работает, это лишь позволяет несколько блоков за слот реле производить. (Но для этого ещё нода должна быть с lookahead собрана)

2023-10-09 14:07 UTC, CertainLach commented
Нода будет отдельным PRом

2023-10-09 14:09 UTC, mrshiposha approved these changes

2023-10-09 14:10 UTC, merged