Fix/token properties benchmarks
UniqueNetwork/unique-chain pull request #1007
Opened 2023-10-05 19:19 UTC by mrshiposha

2023-10-05 20:19 UTC, CertainLach requested changes

2023-10-05 20:19 UTC, CertainLach commented on primitives/common/src/constants.rs
> +pub const MAX_NESTING_BUDGET: u32 = 5;
Это не максимум, у эфира может быть больше

2023-10-05 20:19 UTC, CertainLach commented on pallets/refungible/src/common.rs
> +				+ <PalletStructure<T>>::find_parent_weight(MAX_NESTING_BUDGET)
Так делать некорректно, поскольку в common интерфейсы нам попадает уже budget, так было бы правильно если бы мы его тут (в common интерфейсе) конструировали

2023-10-05 20:22 UTC, CertainLach commented on pallets/unique/src/lib.rs
> -	pub const NESTING_BUDGET: u32 = 5;
И я таки считаю что константа там лучше чем

2023-10-06 07:58 UTC, mrshiposha commented on pallets/unique/src/lib.rs
> -	pub const NESTING_BUDGET: u32 = 5;
Да, это щас черновик. По-другому сделаем

2023-10-06 08:11 UTC, CertainLach commented on pallets/refungible/src/common.rs
> +				+ <PalletStructure<T>>::find_parent_weight(MAX_NESTING_BUDGET)
Возможно имеет смысл бюджет сделать generic, чтобы было более понятно какие веса нужно для каких бюджетов использовать, и чтобы нельзя было его использовать не в тех местах?

enum NestingKind {}

dyn Budget<NestingKind>

2023-10-10 17:00 UTC, CertainLach requested changes

2023-10-10 17:00 UTC, CertainLach commented on pallets/balances-adapter/src/common.rs
> +		_nesting_budget: &dyn up_data_structs::budget::Budget,
Бюджет должен целиком переходить в вес по месту своей инициализации, неправильно его в весах самих операций учитывать

2023-10-10 17:01 UTC, CertainLach commented on pallets/balances-adapter/src/common.rs
> +		_nesting_budget: &dyn up_data_structs::budget::Budget,
Мы оплачиваем операции создания NFT возможность залезать во вложенные токены, само создание NFT от этого дороже не становится

2023-10-10 18:27 UTC, CertainLach commented on pallets/balances-adapter/src/common.rs
> +		_nesting_budget: &dyn up_data_structs::budget::Budget,
По месту инициализации то у нас конкретный тип, Value, и мы его по владению внутреннему коду не отдаём
```rust
impl Value {
  fn remaining(&self) -> u32;
}

#[weight(Weights::transfer() + nest_weight * NEST_LIMIT)]
fn transfer() -> ResultWithPostInfo {
    let nest_budget = Value(NEST_LIMIT);
    let post_info = dispatch(|t| t.transfer(&nest_budget));
    let refund = nest_budget.remaining();
    post_info.weight -= nest_weight.refund;
    post_info
}
```

2023-10-10 18:33 UTC, CertainLach commented on pallets/balances-adapter/src/common.rs
> +		_nesting_budget: &dyn up_data_structs::budget::Budget,
Если стоимость бюджетов будет обрабатываться в common weights, то я не представляю как будет выглядеть управление стоимостью в safe_transfer, при котором во время одного трансфера может быть вызван другой трансфер.
Ради эфира стоит бюджет полностью в callsite разбирать

2023-10-10 18:34 UTC, CertainLach commented on pallets/balances-adapter/src/common.rs
> +		_nesting_budget: &dyn up_data_structs::budget::Budget,
Лучше всё же remaining тут

2023-10-10 18:39 UTC, CertainLach commented on pallets/balances-adapter/src/common.rs
> +		_nesting_budget: &dyn up_data_structs::budget::Budget,
Разумеется можно по функциям это всё раскидать красивым:

```
/// Value по значению чтобы нельзя было ошибиться и не там этот вызов вставить
fn post_add_consumed_budget(post: &mut ResultWithPostInfo, budget: Value, initial: u32, per_consume: Weight) {...}

post_add_consumed_budget(&mut post_info, nest_budget, NEST_LIMIT, nest_weight)
```

2023-10-11 07:54 UTC, mrshiposha commented on pallets/balances-adapter/src/common.rs
> +		_nesting_budget: &dyn up_data_structs::budget::Budget,
Согласен. Я не сообразил, что post_info имеет pub поля. Это и меньше усилий займет.

2023-10-11 15:50 UTC, CertainLach commented on pallets/common/src/lib.rs
> +	is_collection_admin: LazyValue<bool, FIsAdmin>,
Как насчёт избавиться от этих жутких генериков?)
Либо через
trait Lazy { type Value = bool; }

Либо, ещё лучше, просто спрятать его в

enum LazyValue<T> {
Pending(Box<dyn FnOnce() -> T>),
Pending,
Computed(T),
}

2023-10-11 15:54 UTC, CertainLach commented on pallets/common/src/lib.rs
> +	is_collection_admin: LazyValue<bool, FIsAdmin>,
Второй вариант можно будет в том числе заменить на alloc::once::LazyCell после стабилизации
https://doc.rust-lang.org/std/cell/struct.LazyCell.html

2023-10-11 15:57 UTC, CertainLach commented on primitives/data-structs/src/budget.rs
> +	pub fn remaining(&self) -> u32 {
Оно принимало по значению чтобы им нельзя было пользоваться после возрата средств, мне кажется тут стоит оставить прежнее название и receiver.
Разве что можно переименовать в refund_amount

2023-10-11 19:04 UTC, mrshiposha commented on pallets/common/src/lib.rs
> +	is_collection_admin: LazyValue<bool, FIsAdmin>,
LazyCell из std тоже берет вторым аргументом generic. И более того, у него impl определен только для `F: FnOnce() -> T`.

То есть после стабилизации дженерики придется вернуть. Можно, конечно, сделать trait или юзать dyn FnOnce, но тогда мы не сможем уже заменить на стандартный LazyCell потом.

2023-10-11 19:05 UTC, mrshiposha commented on pallets/common/src/lib.rs
> +	is_collection_admin: LazyValue<bool, FIsAdmin>,
Но я, в целом, не против использовать dyn FnOnce

2023-10-12 08:06 UTC, CertainLach commented on pallets/common/src/lib.rs
> +	is_collection_admin: LazyValue<bool, FIsAdmin>,
А, там дизайн переделали. Странно оно теперь устроено, переменные же не захватить

2023-10-12 08:10 UTC, mrshiposha commented on pallets/common/src/lib.rs
> +	is_collection_admin: LazyValue<bool, FIsAdmin>,
Почему же, можно. Просто по умолчанию там втыкается `fn`, который не захватывает. Однако, можно воткнуть и closure, и для closure FnOnce есть нормальный impl

2023-10-12 09:43 UTC, CertainLach commented on pallets/common/src/lib.rs
> +	is_collection_admin: LazyValue<bool, FIsAdmin>,
Не, там именно что для dyn нужно какие-то костыли сооружать теперь: https://github.com/rust-lang/rust/issues/109736
Возможно с dyn_star придумают лучший дизайн (owned dyn): https://github.com/rust-lang/rust/issues/102425

2023-10-12 09:46 UTC, CertainLach commented on pallets/common/src/lib.rs
> +	InProgress(PhantomData<sp_std::cell::Cell<T>>),
Nit: нам не нужно чтобы dropck считал что тут есть interior mutability, потому что его тут нет
Правильнее будет `PhantomData<Option<T>>`, или даже `PhantomData<T>`, поскольку разницы для rustc нет

2023-10-12 09:48 UTC, CertainLach commented on pallets/common/src/lib.rs
> +				// InProgress is ruled out by not implementing Sync and absence of recursion
Рекурсия возможна, другое дело что мы её поддерживать не хотим, а поэтому тут правильнее сделать panic!()

2023-10-12 12:47 UTC, CertainLach commented on tests/src/util/playgrounds/unique.ts
> +    return (props != null) ? (props as any).consumedSpace : 0;
=> props?.a ?? 0

2023-10-13 10:42 UTC, mrshiposha commented on pallets/common/src/lib.rs
> +	InProgress(PhantomData<sp_std::cell::Cell<T>>),
Я это поставил, чтобы Sync убрать. Я понимаю, что сейчас рантайм однопоточный, но мне не нравятся весящие unreachable, до которых теоретически можно дотянуться.
По идее `FnOnce() -> T` ему уже должно быть достаточно, чтобы заключить, что T используется

2023-10-13 10:45 UTC, mrshiposha commented on pallets/common/src/lib.rs
> +				// InProgress is ruled out by not implementing Sync and absence of recursion
Рекурсии нет в этом методе, соот-но, попасть сюда мы не можем, ибо InProgress никогда не будет возвращено из replace. И так как есть гарантия, что это вызывается только из одного потока, то можно заключать, что это unreachable.

2023-10-13 10:58 UTC, CertainLach requested changes

2023-10-13 10:58 UTC, CertainLach commented on pallets/nonfungible/src/common.rs
> +	tokens: impl Iterator<Item = u32> + Clone,
```suggestion
	token_properties: impl Iterator<Item = u32> + Clone,
```
Не сразу сообразил что это, пришлось в вызов смотреть
По хорошему ко всем этим вычислительным методам нужны doccomments, поскольку из-за того как оно размазано очень сложно следить за логикой

2023-10-13 10:58 UTC, CertainLach commented on pallets/refungible/src/common.rs
> +				+ <SelfWeightOf<T>>::write_token_properties(amount)
saturating_add просто для консистентности

2023-10-13 10:58 UTC, CertainLach commented on pallets/refungible/src/common.rs
> +pub(crate) fn mint_with_props_weight<T: Config>(
Может вообще заинлайнить этот метод?) В nonfungible тоже

2023-10-13 10:58 UTC, CertainLach commented on pallets/refungible/src/erc.rs
Кажется мне что для эфира будет читабельнее вместо CommonWeights везде использовать газомер...
Но допустим пока так.

2023-10-13 10:58 UTC, CertainLach commented on pallets/refungible/src/erc.rs
Минтинг refungible намного лучше выглядел бы через бюджеты

2023-10-13 10:59 UTC, CertainLach commented on pallets/common/src/lib.rs
> +				// InProgress is ruled out by not implementing Sync and absence of recursion
Её могут снаружи вызвать, если у нас f() вдруг решит тот же Lazy исполнить

2023-10-13 10:59 UTC, CertainLach commented on pallets/common/src/lib.rs
> +				// InProgress is ruled out by not implementing Sync and absence of recursion
Это надо извратиться, но это не unreachable.

2023-10-13 11:01 UTC, CertainLach commented on pallets/common/src/lib.rs
> +				// InProgress is ruled out by not implementing Sync and absence of recursion
```rust
let mut a = RefCell::new(None);
*a.borrow_mut() = LazyVal::new(|| {
    a.borrow().force();
});
a.borrow().force();
```

2023-10-13 11:01 UTC, CertainLach commented on pallets/common/src/lib.rs
> +	InProgress(PhantomData<sp_std::cell::Cell<T>>),
У нас тут от многопоточности защищает требование &mut)

2023-10-13 11:02 UTC, CertainLach commented on pallets/common/src/lib.rs
> +	InProgress(PhantomData<sp_std::cell::Cell<T>>),
До unreachable можно дотянуться другим способом, и я его отписал, и Cell тут не поможет

2023-10-13 11:05 UTC, mrshiposha commented on pallets/common/src/lib.rs
> +	InProgress(PhantomData<sp_std::cell::Cell<T>>),
&mut -- good point

2023-10-13 11:07 UTC, mrshiposha commented on pallets/common/src/lib.rs
> +				// InProgress is ruled out by not implementing Sync and absence of recursion
Походу, мне очень нужны выходные)
Да, действительно

2023-10-13 11:51 UTC, CertainLach commented on pallets/common/src/lib.rs
> +	InProgress(PhantomData<sp_std::cell::Cell<T>>),
Вообще, любые сложные требования находящиеся в PhantomData не нужны в отсутствие unsafe кода, у Rust везде гарантии достаточно строгие

2023-10-13 14:14 UTC, CertainLach approved these changes

2023-10-13 14:15 UTC, merged