Refactor/foreign assets as thin proxy
UniqueNetwork/unique-chain pull request #1024
Opened 2023-10-23 17:49 UTC by mrshiposha

2023-10-27 12:23 UTC, CertainLach requested changes
Забыл отправить, возможно устарело

2023-10-27 12:29 UTC, mrshiposha commented on pallets/balances-adapter/src/common.rs
> +impl<T: Config> pallet_common::XcmExtensions<T> for NativeFungibleHandle<T> {
Mutate используется исключительно в NativeFungible (коллекция №0).
Больши нигде он не используется. Соот-но, не вижу необходимости выносить это в CommonCollectionOperations

2023-10-27 12:33 UTC, mrshiposha commented on pallets/common/src/dispatch.rs
> +		is_special_collection: bool,
Потому что я решил не менять публичный интерфейс, частью которого является CreateCollectionData.
Тут вопрос можно ли выставлять специальные флаги или нет. Пользователю обычно этого делать нельзя.

Возможно, стоит это как-то поменять и специальные флаги вообще убрать из публичного интерфейса...
В общем, я не уверен как тут лучше

2023-11-24 13:06 UTC, CertainLach commented on pallets/common/src/dispatch.rs
> +		is_special_collection: bool,
Как насчёт
```rust
enum Issuer {
    User,
    Internals
}
```
Где флаги может устанавливать только Internals?
А остальное пробрасывать как есть
Можно в User передавать CrossAccountId, чтобы с него деньги списывались заодно

2023-11-24 15:24 UTC, CertainLach commented on pallets/common/src/lib.rs
> +	#[transactional]
Мне кажется что стоит в контракте описать что реализация этого трейта должна исполняться транзакционно
Однако я так понял что это временно, и транзакций тут не будет после принятия https://github.com/paritytech/polkadot-sdk/pull/1222?
Или у нас высокоуровневая реализация требует тут транзакции? Короче нужно описание почему тут транзакции)

2023-11-24 15:30 UTC, CertainLach commented on pallets/foreign-assets/src/lib.rs
> +			<CollectionToForeignAsset<T>>::insert(collection_id, *asset_id);
Избыточно с проперти `reserve_location`, лучше бы оставить только одно

2023-11-24 15:44 UTC, CertainLach commented on pallets/foreign-assets/src/lib.rs
> +			CollectionLocality::Local(_) => Self::local_asset_instance_to_token_id(asset_instance),
А не нужно ли тут возвращать None при отсутствии токена? Для foreign у нас `OptionQuery` и отсутствующие токены не сконвертируются.
Почти везде где вызывается `deposit_asset_instance` у нас идёт предположение что токен существует
Оно конечно везде после этого упадёт, однако причина падения будет уже не `AssetNotFound`, а `FailedToTransactAsset`(?), что как я понял не совсем соответствует контракту, поскольку утверждает что токен существует

2023-11-24 16:29 UTC, mrshiposha commented on pallets/foreign-assets/src/lib.rs
> +			<CollectionToForeignAsset<T>>::insert(collection_id, *asset_id);
Тут пока непонятно какой механизм лучше. По-хорошему, все должно операться на проперти (притом за PropertyScope'ом). Тогда юзеры будут пользоваться единым интерфейсом для узнавания информации об НФТ. И чейн использовал бы то же самое хранилище.
Но сейчас читать проперти -- дорого по PoV.

Могу убрать проперти, так как оно все равно не за скоупом. Когда будет нужно -- можно будет перенести нужные данные из этого стореджа.

2023-11-24 16:39 UTC, mrshiposha commented on pallets/foreign-assets/src/lib.rs
> +			CollectionLocality::Local(_) => Self::local_asset_instance_to_token_id(asset_instance),
По-хорошему, нужно возвращать ошибку `XcmExecutorError::AccountIdConversionFailed` (который превратиться в FailedToTransactAsset("AccountIdConversionFailed")), а не AssetNotFound.
Потому что существование токена проверяют наши внутренние паллеты и, по-хорошему, нам бы уметь конвертировать ошибки из низ в ошибки XCM. И там уже должен появляться AssetNotFound.

Главная задача этой паллеты -- не дублировать логику и опираться на нашу логику, которая уже давно есть и глубоко протестирована. Собственно, отдельно проверять существование вместо внутренней паллеты -- очень не хочется. Кроме того, реализации в других чейнах обычно (так конечно нет разговора про NFT, но тем не менее), обычно опираются на FailedToTransactAsset в итоге.

2023-11-24 16:43 UTC, mrshiposha commented on pallets/foreign-assets/src/lib.rs
> +			CollectionLocality::Local(_) => Self::local_asset_instance_to_token_id(asset_instance),
На самом деле, использовать AssetNotFound при отстуствии нужного AssetInstance семантически неверно. Asset'ом в XCM называют не отдельный токен, а всю коллекцию.

2023-11-24 16:50 UTC, CertainLach commented on pallets/foreign-assets/src/lib.rs
> +			<CollectionToForeignAsset<T>>::insert(collection_id, *asset_id);
Лучше тогда отдельный storage, просто подобное дублировать как-то некрасиво

2023-11-24 16:51 UTC, CertainLach commented on pallets/foreign-assets/src/lib.rs
> +			CollectionLocality::Local(_) => Self::local_asset_instance_to_token_id(asset_instance),
Энивей, асимметрия возвращаемых ошибок для foreign и наших ассетов выглядит как-то странно

2023-11-24 16:53 UTC, mrshiposha commented on pallets/foreign-assets/src/lib.rs
> +			CollectionLocality::Local(_) => Self::local_asset_instance_to_token_id(asset_instance),
Я как-то это пропустил. А вот реализации для Акалы Павел использовал правильные ошибки из XcmExecutorError.

2023-11-24 16:56 UTC, mrshiposha commented on pallets/common/src/lib.rs
> +	#[transactional]
Добавлю описание. Вкратце -- потому что прибывающие сообщения обрабатываются ВНЕ рамок транзакции. А нам она нужна, ибо мы внутри обращаемся к логике наших паллет, которые сами по себе не транзакционны и больше не делают всех проверок до изменения стореджа.

2023-11-24 16:56 UTC, mrshiposha commented on pallets/common/src/lib.rs
> +	#[transactional]
И да, это временно. Потом надо будет в одном месте убрать эти `#[transactional]`

2023-11-24 17:05 UTC, mrshiposha commented on pallets/foreign-assets/src/lib.rs
> +			<CollectionToForeignAsset<T>>::insert(collection_id, *asset_id);
Убрал проперти

2023-11-24 17:05 UTC, mrshiposha commented on pallets/foreign-assets/src/lib.rs
> +			CollectionLocality::Local(_) => Self::local_asset_instance_to_token_id(asset_instance),
Пофиксил

2023-11-28 21:05 UTC, CertainLach approved these changes

2023-11-29 09:07 UTC, merged