Unique polkadot 1.14
UniqueNetwork/unique-chain pull request #1096
Opened 2024-11-15 16:30 UTC by vklachkov

Much-anticipated update of **Unique** to Polkadot **1.14**.

This update has been prepared through the joint efforts of @fairax, @BuddyGlas, myself, and @mrshiposha.

**In this update**

- Updated all dependencies
- Setuped async backing 
- Fixed migrations issues that have persisted since 0.9 versions
- Fixed a lot of tests
- Revived our CI

Despite the release of version 1.16.1, we decided to keep the SDK version at 1.14 as it has already been tested and works great.

Regarding the previous PR https://github.com/UniqueNetwork/unique-chain/pull/1091, I have restructured the commit history and corrected all messages, as well as added the missing changes.

**Update note №1**

The node in this release with Async Backing performs very poorly. To address this, it was decided to update the node separately to the latest Polkadot SDK to enable Fork Aware Tx Pool in [a separate branch](https://github.com/UniqueNetwork/unique-chain/blob/v20241016-node). After the new release from Parity, the branches may be merged.

**Update note №2**

The release has been delayed so much that many outdated branches with intermediate changes have formed during the process. After a successful release, we need to remember to clean up.

2024-11-15 16:57 UTC, CertainLach requested changes

2024-11-15 16:57 UTC, CertainLach commented on .baedeker/up.sh
> +RUST_LOG=info ./baedeker --spec=docker -J$BDK_DIR/vendor/ --generator=docker_compose=$BDK_DIR/.bdk-env --generator=docker_compose_discover=$BDK_DIR/.bdk-env/discover.env --secret=file=$BDK_DIR/.bdk-e
```suggestion
RUST_LOG=info baedeker --spec=docker -J$BDK_DIR/vendor/ --generator=docker_compose=$BDK_DIR/.bdk-env --generator=docker_compose_discover=$BDK_DIR/.bdk-env/discover.env --secret=file=$BDK_DIR/.bdk-env/secret  --tla-str=relay_spec=rococo-local --tla-code=assethub_spec="import 'assethub-spec.json'" --input-modules='lib:baedeker-library/ops/nginx.libsonnet' --input-modules='lib:baedeker-library/ops/devtools.libsonnet' --tla-str=repoDir=$(realpath $BDK_DIR/..) $@ $BDK_DIR/rewrites.jsonnet
```

Зачем его не из PATH?

2024-11-15 16:57 UTC, CertainLach commented on .baedeker/xcm-quartz.jsonnet
> +		for name in ['alice', 'bob', 'charlie', 'dave', 'eve', 'ferdie', 'gregory', 'holly', 'iggy', 'john', 'kurt']
Не многовато ли для локального запуска? 
Осталось от отладки?

2024-11-15 16:57 UTC, CertainLach commented on .env
> +HYDRADX_BUILD_BRANCH=latest
Давайте хоть частично фиксированные теги использовать(

Если у них нет нормальных - то текущий хеш сюда можно, latest@sha256:fafa...fafa

2024-11-15 16:57 UTC, CertainLach commented on .github/workflows/codestyle.yml
> +        run: cargo clippy --features=quartz-runtime,unique-runtime,try-runtime --tests -- -Dwarnings
```suggestion
        run: cargo clippy --features=quartz-runtime,unique-runtime,try-runtime,runtime-benchmarks --tests -- -Dwarnings
```

Зачем?

2024-11-15 16:57 UTC, CertainLach commented on .github/workflows/node-only-update.yml
> +            snippet:(import 'baedeker-library/ops/rewrites.libsonnet').rewriteNodePaths({'bin/unique':{dockerImage:'${{ steps.mainnet.outputs.name }}'}}, extra_node_mixin={extraArgs: []})
Таким образом у вас не проверяется обновлённая нода, переписать путь нужно только один раз при начальном запуске, и не сохранять это переписывание на следующий запуск
```suggestion
            ephemeral:snippet:(import 'baedeker-library/ops/rewrites.libsonnet').rewriteNodePaths({'bin/unique':{dockerImage:'${{ steps.mainnet.outputs.name }}'}}, extra_node_mixin={extraArgs: []})
```

2024-11-15 16:57 UTC, CertainLach commented on js-packages/package.json
> +    "patch-package": "8.0.0",
TODO: Надо было ставить Deno...

2024-11-15 16:57 UTC, CertainLach commented on js-packages/tests/creditFeesToTreasury.seqtest.ts
> +    const tolerance = 0.001471945777320835;
Лучше бенчмарки перегоните, tolerance тут достаточный, ошибка у вас от того что целевые показатели уплыли
```suggestion
    const tolerance = 0.001; // Do not touch, rerun benchmarks instead
```

2024-11-15 16:57 UTC, CertainLach commented on node/cli/src/service.rs
> +pub type ParachainHostFunctions = frame_benchmarking::benchmarking::HostFunctions;
По моему я уже в прошлом ревью говорил, не нужно смешивать HostFunctions и ExtendHostFunctions

2024-11-15 16:57 UTC, CertainLach commented on node/cli/src/service.rs
> +	EthTask, StorageOverride, StorageOverrideHandler,
На проверить - у нас тесты проверяют у нас работу rpc eth_getCode для наших контрактов? (= Возвращаются ли стабы) Для старых overrides я делал его обработку специальную, нужно проверить правильно ли она сделана в StorageOverrideHandler

2024-11-15 16:57 UTC, CertainLach commented on pallets/common/src/benchmarking.rs
>  use core::convert::TryInto;
Оно и так в prelude в Rust 2021 edition

2024-11-15 16:57 UTC, CertainLach commented on pallets/evm-coder-substrate/src/execution.rs
> -use std::string::{String, ToString};
По идее оно нужно, проверьте генерацию стабов

2024-11-15 16:57 UTC, CertainLach commented on runtime/opal/build.rs
> +		.enable_metadata_hash("WND", 12)
Смените префикс
Мы пока ledger не умеем, но не надо путать сканеры что это смотрят

2024-11-15 16:57 UTC, CertainLach commented on runtime/quartz/build.rs
> +		.enable_metadata_hash("WND", 12)
Сменить

2024-11-15 16:57 UTC, CertainLach commented on runtime/unique/build.rs
> +		.enable_metadata_hash("WND", 12)
Сменить

2024-11-15 16:58 UTC, CertainLach commented on .github/workflows/node-only-update.yml
> +            snippet:(import 'baedeker-library/ops/rewrites.libsonnet').rewriteNodePaths({'bin/unique':{dockerImage:'${{ steps.mainnet.outputs.name }}'}}, extra_node_mixin={extraArgs: []})
ephemeral переписывания сохраняются на текущий вызов экшона, не-ephemeral запоминаются и используются дальше

2024-11-15 18:32 UTC, vklachkov commented on runtime/common/mod.rs
> +	pub const PalletMembershipTargetStorageVersion: StorageVersion = StorageVersion::new(4);
nit: Можно ли избавиться от параметров и прописать номера версий сразу в PalletVersionMigration в Unreleased?

2024-11-15 18:32 UTC, vklachkov commented on runtime/common/mod.rs
> +pub type Unreleased = (
nit: Можно ли не удалять Unreleased после каждого обновления и сделать все миграции идемпотентными? Как правильно организовать миграции в Unique для будущего?

2024-11-15 18:40 UTC, CertainLach commented on runtime/common/mod.rs
> +pub type Unreleased = (
Они не похожи на идемпотентные, там всё равно нужно везде проверять версии хранилищ

2024-11-18 04:34 UTC, BuddyGlas commented on .baedeker/xcm-quartz.jsonnet
> +		for name in ['alice', 'bob', 'charlie', 'dave', 'eve', 'ferdie', 'gregory', 'holly', 'iggy', 'john', 'kurt']
У меня есть убеждение, что для корректной работы коллаторов валидаторов должно быть как минимум на 1 больше.

2024-11-18 04:38 UTC, BuddyGlas commented on .baedeker/up.sh
> +RUST_LOG=info ./baedeker --spec=docker -J$BDK_DIR/vendor/ --generator=docker_compose=$BDK_DIR/.bdk-env --generator=docker_compose_discover=$BDK_DIR/.bdk-env/discover.env --secret=file=$BDK_DIR/.bdk-e
Согласен! нужно запускать из PATH. 
у меня ещё вопрос: нужно ли вот это прописывать здесь --tla-code=assethub_spec="import 'assethub-spec.json'". Запуск Ассетхаба - это частный случай.

2024-11-18 05:50 UTC, vklachkov commented on .baedeker/up.sh
> +RUST_LOG=info ./baedeker --spec=docker -J$BDK_DIR/vendor/ --generator=docker_compose=$BDK_DIR/.bdk-env --generator=docker_compose_discover=$BDK_DIR/.bdk-env/discover.env --secret=file=$BDK_DIR/.bdk-e
> Зачем его не из PATH?

Случайно попало в коммит. Я всегда у себя в up.sh заменяю `baedeker` на `./baedeker`, так как не храню его в PATH.

Может быть, в идеале было бы сделать что-то такое:

```bash
if [ -x "./baedeker" ]; then
	./baedeker bla-bla
elif [ -x "$(command -v baedeker)" ]; then
	baedeker bla-bla
else
	echo "Baedeker is not installed"
fi
``` 

> Запуск Ассетхаба - это частный случай

Это удобно для запуска xcm*.jsonnet. Давайте оставим

2024-11-18 05:52 UTC, BuddyGlas commented on .baedeker/up.sh
Точно нужно здесь прописывать частный случай импортирования спеки для запуска ассетхаба?

2024-11-18 05:53 UTC, vklachkov commented on .github/workflows/codestyle.yml
> +        run: cargo clippy --features=quartz-runtime,unique-runtime,try-runtime --tests -- -Dwarnings
Зачем убрали runtime-benchmarks? На этом фичефлаге сломана сборка

2024-11-26 17:49 UTC, mrshiposha requested changes

2024-11-26 17:49 UTC, mrshiposha commented on runtime/common/config/xcm.rs
> +#[allow(deprecated)]
Пусть ругается. Нам это надо будет убрать в следующем релище окончательно

```suggestion
```

2024-11-26 23:41 UTC, CertainLach commented on .docker/Dockerfile-unique-release
> +    CARGO_INCREMENTAL=0; cargo build --release --features="${FEATURES}" --locked && \
Тут ; сработает не как положено, т.к оно имеет меньший precedence чем &&

a && b ; c && d == (a && b) ; (c && d)

VAR=VALUE cmd

работает аналогично

env VAR=VALUE cmd

Если тут читаемость не нравится

2024-11-26 23:42 UTC, CertainLach commented on .docker/Dockerfile-unique
> +    CARGO_INCREMENTAL=0; WASM_BUILD_TYPE=integration-tests; cargo build --profile integration-tests --features=fast-inflation,"${FEATURES}" --locked && \
Аналогично тут, не надо так делать когда аргументы для одной команды задаёшь.

2024-11-28 12:21 UTC, CertainLach commented on .baedeker/up.sh
> +RUST_LOG=info baedeker --spec=docker -J$BDK_DIR/vendor/ --generator=docker_compose=$BDK_DIR/.bdk-env --generator=docker_compose_discover=$BDK_DIR/.bdk-env/discover.env --secret=file=$BDK_DIR/.bdk-env
Перенесите этот дефолт для assethub_spec в .jsonnet файлы для видимости

2024-11-28 12:24 UTC, CertainLach commented on .github/workflows/codestyle.yml
> +        run: cargo clippy --features=quartz-runtime,unique-runtime,try-runtime --tests -- -Dwarnings
Значит надо чинить, бенчмарки нам нужны, это не повод выключать флаги)

2024-11-28 12:31 UTC, vklachkov commented on .github/workflows/codestyle.yml
> +        run: cargo clippy --features=quartz-runtime,unique-runtime,try-runtime --tests -- -Dwarnings
@mrshiposha ты починил runtime-benchmarks? Можно для него включать clippy?

2024-11-28 14:31 UTC, mrshiposha commented on .github/workflows/codestyle.yml
> +        run: cargo clippy --features=quartz-runtime,unique-runtime,try-runtime --tests -- -Dwarnings
Нет. Моей задачей было взвесить как угодно. Я взвесил на отдельной ветке базе ветки Григория, которая 1.16.1. Там были все изменения с этой ветки, поэтому веса адекватные.

Григорий каким-то образом починил бенчмарки на 1.16.1. 

На 1.14 я просто не успевал починить бенчи. frame-benchmarking у себя не находит alloc, что указывает на непрокинутый std где-то. По отдельности я локально правил паллеты Юника. Во всех паллетах Юника эту ошибку я устранил локально. Перепроверил паллету спонсоринга, все зависимости orml и фронтир. Нигде эта ошибка по отдельности не проявляется. А вот если компилить всё целиком -- появляется. Я долго возился с `cargo tree`, пытаясь понять где было пропущено std, но не нашёл.

Возможно, стоит посмотреть на diff с веткой Григория, коль на его ветке всё было хорошо.

2024-12-05 14:41 UTC, CertainLach commented on .baedeker/xcm-quartz.jsonnet
> +		for name in ['alice', 'bob', 'charlie', 'dave', 'eve', 'ferdie', 'gregory', 'holly', 'iggy', 'john', 'kurt']
А? Нет
Одна реле нода может валидировать несколько кандидатов одновременно, лишь бы времени хватило
И с таким числом нод процессорного времени хватит если валидаторов будет меньше)

2024-12-16 11:27 UTC, CertainLach requested changes

2024-12-16 11:27 UTC, CertainLach commented on .baedeker/xcm-quartz.jsonnet
> +		for name in ['alice', 'bob', 'charlie', 'dave', 'eve', 'ferdie', 'gregory', 'holly', 'iggy', 'john', 'kurt']
+ пропущена конфигурация async-backing, для последней версии реле она требуется

2024-12-16 11:27 UTC, CertainLach commented on .docker/Dockerfile-unique-base-image
> +    curl -sL https://apt.llvm.org/llvm.sh | bash - && \
Это parity так делает? В случае с debian лучше использовать системный линковщик, lld слишком bleeding edge

2024-12-16 11:27 UTC, CertainLach commented on .docker/Dockerfile-unique-release
> +    cd target/release/wbuild && find . -name "*.wasm" -exec sh -c 'mkdir -p "../../../wasm/$(dirname {})"; cp {} "../../../wasm/{}"' \;
Для /wasm давайте абсолютный путь использовать, а то читать тяжело)

2024-12-16 11:27 UTC, CertainLach commented on .github/workflows/forkless-update-data.yml
> +            snippet:(import 'baedeker-library/ops/rewrites.libsonnet').rewriteNodePaths({'bin/unique':{dockerImage:'${{ steps.node.outputs.name }}'}}, extra_node_mixin={extraArgs: []}, for_chain = fa
Внимание: тут ОЧИЩАЕТСЯ extraArgs, не уверен что нам это нужно

2024-12-16 11:27 UTC, CertainLach commented on .github/workflows/just-tests-without-update.yml
> +            snippet:(import 'baedeker-library/ops/rewrites.libsonnet').rewriteNodePaths({'bin/unique':{dockerImage:'${{ steps.node.outputs.name }}'}}, extra_node_mixin={extraArgs: []})
Очищается extraArgs, перепроверьте что это нам нужно

2024-12-16 11:27 UTC, CertainLach commented on .github/workflows/main-process-update.yml
> +            ephemeral:snippet:(import 'baedeker-library/ops/rewrites.libsonnet').rewriteNodePaths({'bin/unique':{dockerImage:'${{ steps.mainnet.outputs.name }}'}}, extra_node_mixin={extraArgs: []})
Очистка extraArgs

2024-12-16 12:26 UTC, BuddyGlas commented on .baedeker/xcm-unique.jsonnet
> +		for name in ['alice', 'bob', 'charlie', 'dave', 'eve', 'ferdie', 'gregory', 'holly', 'iggy', 'john', 'kurt', 'larry', 'mike', 'norman', 'osvald']
Это уже поправлено в ветке Даниила. В этой ветке xcm не запускаем пока.

2024-12-16 12:26 UTC, BuddyGlas commented on .baedeker/just-tests.jsonnet
> +				genesis+: {
это тестовый файл, на него не обращай внимания.

2024-12-16 12:28 UTC, BuddyGlas commented on .github/workflows/just-tests-without-update.yml
> +            snippet:(import 'baedeker-library/ops/rewrites.libsonnet').rewriteNodePaths({'bin/unique':{dockerImage:'${{ steps.node.outputs.name }}'}}, extra_node_mixin={extraArgs: []})
Этот воркфлоу будет удалён

2024-12-16 12:29 UTC, BuddyGlas commented on .github/workflows/main-process-update.yml
> +            ephemeral:snippet:(import 'baedeker-library/ops/rewrites.libsonnet').rewriteNodePaths({'bin/unique':{dockerImage:'${{ steps.mainnet.outputs.name }}'}}, extra_node_mixin={extraArgs: []})
Очистка extra-args при СТАРТЕ чейна является обязательным условием, в данном случае, поскольку старая версия ноды ещё не знает параметров запуска 
 ```
                               '--increase-future-pool',
                                '--pool-type=fork-aware',
```

2025-03-13 13:34 UTC, closed without merging

2025-03-13 13:35 UTC, vklachkov commented
Superseded by stable2412