Feature/divide runtimes into 3
UniqueNetwork/unique-chain pull request #307
Opened 2022-03-10 10:48 UTC by MrShiposha

### The changes
* Split the runtime into 3 runtimes: Unique, Quartz, and Opal
* Moved common types and constants into the corresponding modules of the `common` crate.
* Moved runtime APIs to common
* Adjusted the `unique-node` and `unique-rpc` to newly defined runtimes
* Added new build methods description to the README (how to build the project with Quartz/Opal runtime)

2022-03-14 10:01 UTC, CertainLach reviewed
Ничего критичного, nitpicks

2022-03-14 10:01 UTC, CertainLach commented on node/cli/src/chain_spec.rs
> +	fn is_unique(&self) -> bool;
Думаю тут лучше сделать 

```rs
enum RuntimeId {
    Unique,
    Quartz,
    Opal,
    Unknown(Id),
}

fn id(&self) -> RuntimeId
```

И feature флаги проверять на ветках в match

```rs
match spec.id() {
  #[cfg(feature = "unique-runtime")]
  RuntimeId::Unique => {}
  id => { bail!("unknown runtime: {id}") }
}
```

2022-03-14 10:51 UTC, MrShiposha commented on node/cli/src/service.rs
> +		unique_runtime::api::dispatch(method, data)
Это ошибка копипасты. В каждой из реализаций должен вызываться соотвествующий рантайм.

2022-03-14 10:53 UTC, MrShiposha commented on node/cli/src/command.rs
> +			let chain_spec = Box::new(chain_spec::UniqueChainSpec::from_json_file(path.clone())?)
Здесь нужно только вытащить `chain_spec.id()`, поэтому здесь буду использовать просто `GenericChainSpec` вместо runtime-specific.

2022-03-14 10:54 UTC, MrShiposha commented on node/cli/src/chain_spec.rs
> +	fn is_unique(&self) -> bool;
Хорошо, сделаю

2022-03-14 10:58 UTC, MrShiposha commented on node/cli/src/service.rs
> +		unique_runtime::api::dispatch(method, data)
+ это все должно быть под `cfg(feature = "<runtime>")`

2022-03-15 09:15 UTC, CertainLach commented on runtime/common/src/runtime_apis.rs
> +            #![custom_apis]
В таком случае ок, пусть будет

2022-03-15 09:17 UTC, CertainLach requested changes

2022-03-15 09:17 UTC, CertainLach commented on node/rpc/src/lib.rs.exp
> +// Copyright 2019-2022 Unique Network (Gibraltar) Ltd.
Я так понимаю, этот файл в репу не должен был попасть

2022-03-15 09:18 UTC, MrShiposha commented on node/rpc/src/lib.rs.exp
> +// Copyright 2019-2022 Unique Network (Gibraltar) Ltd.
Ох, совсем не должен был. Спасибо!

2022-03-15 09:19 UTC, MrShiposha commented on node/rpc/src/lib.rs.exp
> +// Copyright 2019-2022 Unique Network (Gibraltar) Ltd.
Removed

2022-03-15 09:20 UTC, CertainLach approved these changes

2022-03-22 03:43 UTC, kozyrevdev commented on node/cli/src/command.rs
> +		"Unique Node".into()
try to use RuntimeId

2022-03-22 03:43 UTC, kozyrevdev commented on node/cli/src/command.rs
> +		"Unique Node\n\nThe command-line arguments provided first will be \
try to use RuntimeId

2022-03-22 04:09 UTC, merged