[WIP] Collator Selection
UniqueNetwork/unique-chain pull request #324
Opened 2022-03-30 09:41 UTC by Fahrrader

2022-04-01 16:07 UTC, CertainLach commented on runtime/opal/src/lib.rs
> +	pub const ExistentialDeposit: u128 = EXISTENTIAL_DEPOSIT;
Мы пока не поддерживаем non-zero-existential deposit, и у frontier тоже с этим проблемы

2022-04-01 16:08 UTC, CertainLach commented on runtime/opal/src/lib.rs
> +		AuraExt: cumulus_pallet_aura_ext::{Pallet, Config} = 26,
Не стоит менять idшники палет

2022-04-04 08:29 UTC, CertainLach commented on runtime/opal/src/lib.rs
> +		AuraExt: cumulus_pallet_aura_ext::{Pallet, Config} = 26,
```
		Authorship: pallet_authorship::{Pallet, Call, Storage} = 24,
		CollatorSelection: pallet_collator_selection::{Pallet, Call, Storage, Event<T>, Config<T>} = 25,
		Session: pallet_session::{Pallet, Call, Storage, Event, Config<T>} = 26,
		Aura: pallet_aura::{Pallet, Config<T>} = 22,
		AuraExt: cumulus_pallet_aura_ext::{Pallet, Config} = 23,
```

2022-04-04 08:30 UTC, CertainLach commented on runtime/opal/src/lib.rs
> +		AuraExt: cumulus_pallet_aura_ext::{Pallet, Config} = 26,
Не очень красиво, однако имеем новый порядок, и старые idшники

2022-04-04 08:32 UTC, Fahrrader commented on runtime/opal/src/lib.rs
> +	pub const ExistentialDeposit: u128 = EXISTENTIAL_DEPOSIT;
Не проблема, я только вынес 0 в отдельную константу для соблюдения однородности данных с новым генезисом и миграцией

2022-04-04 08:52 UTC, Fahrrader commented
> @MrShiposha посмотри, пожалуйста, можно ли уменьшить дублирование вынесением в common?

@kozyrevdev Посмотрел на другие парачейны ещё раз, никто не выносит подобные детали в константы в common. Единственное, стоит изменить PotId с дефолтного на что-то вроде PalletId(*b"py/cpot") (у нас уже есть PalletId py/trsry, но не знаю, что означает "py", или откуда это взято)

2022-12-28 11:16 UTC, CertainLach requested changes

2022-12-28 11:16 UTC, CertainLach commented on pallets/identity/src/lib.rs
> +		pub fn set_identities(
Может, завести задачу этот код в substrate пененести, и от форка палеты отказаться?

2022-12-28 11:16 UTC, CertainLach commented on runtime/common/construct_runtime/mod.rs
> +                Identity: pallet_identity::{Pallet, Call, Storage, Event<T>} = 27,
Перемести это ниже vesting, у нас тут комментариев на это нет, но в самом верху у нас только критичные для существования чейна палеты, а уже потом начинаются палеты substrate

2022-12-28 11:24 UTC, CertainLach commented on Makefile
> +bench-data-management:
Либо тут переименование откатить, либо в самой палете новое название финализировать

2022-12-28 11:24 UTC, CertainLach commented on Makefile
> +bench-collator-selection:
Добавь это в зависимости задачи bench, и ещё нужны бенчмарки для identity

2022-12-28 16:14 UTC, Fahrrader commented on pallets/identity/src/lib.rs
> +		pub fn set_identities(
Если ты о методе к ним залить, то очень сомневаюсь, что они будут как-то за. Текущая простая имплементация обходит все механизмы, в том числе и безопасности, и позволила бы пытаться вернуть себе несуществующие депозиты, т.д. Даже если бы мы сделали всё красиво, сомневаюсь, что такой режим тоже их не устроил бы, судя по тому, как палета предназначена как свободная книга записей саморегистрации, а потенциальные губернаторы чейнов будут сидеть на шее с судо и угрозами перезаписи кого угодно

2022-12-28 16:15 UTC, Fahrrader commented on runtime/common/construct_runtime/mod.rs
> +                Identity: pallet_identity::{Pallet, Call, Storage, Event<T>} = 27,
40 будет хорошо?

2022-12-28 16:24 UTC, Fahrrader commented on Makefile
> +bench-data-management:
Мне кажется, тебе не в тот коммит занесло)

2022-12-28 16:28 UTC, CertainLach commented on runtime/common/construct_runtime/mod.rs
> +                Identity: pallet_identity::{Pallet, Call, Storage, Event<T>} = 27,
+

2022-12-28 17:39 UTC, CertainLach commented on pallets/identity/src/lib.rs
> +		pub fn set_identities(
А, да, тут же проверок нет.

2022-12-28 22:49 UTC, CertainLach requested changes

2022-12-28 22:49 UTC, CertainLach commented on pallets/collator-selection/src/benchmarking.rs
>  		<LicenseBond<T>>::get() > 0u32.into(),
А зачем это отключать? Это же правильная проверка, т.к make_free_balance_be не будет ничего писать, если баланс и так 0

2022-12-28 22:49 UTC, CertainLach commented on pallets/collator-selection/src/mock.rs
> +	type WeightInfo = ();
Направь на сгенерированные веса
Мок веса (`()`) не учитывают DbWeight указанный для рантайма, и зависят от константы

2022-12-28 22:49 UTC, CertainLach commented on pallets/configuration/src/benchmarking.rs
> +		assert_ok!(
Когда название метода идентично названию бенчмарка можно писать просто
`: _(Root, ...)`

2022-12-28 22:49 UTC, CertainLach commented on pallets/configuration/src/lib.rs
> +		#[pallet::weight(T::WeightInfo::set_weight_to_fee_coefficient_override())]
В таких методах DbWeight в принципе хватало, т.к тут видно весь код... Но энивей, спасибо, лучше если оно будет)

2022-12-28 22:49 UTC, CertainLach commented on pallets/identity/src/lib.rs
> -		pub fn set_identities(
Метод нужно было тот же оставить, он и так умел что писать, что удалять, зачем ты его разделил?

2022-12-28 22:49 UTC, CertainLach commented on tests/src/util/identitySetter.ts
> +        // 2) it is our own identity, we don't want to delete it.
Мы же вроде решили что своих identity мы не хотим пока?

2022-12-28 22:49 UTC, CertainLach commented on tests/src/util/identitySetter.ts
> +      await helper.getSudo().executeExtrinsic(superuser, 'api.tx.identity.forceInsertIdentities', [identitiesToAdd]);
А это вообще правильно что мы тут ссылаемся на id регистраторов реле?
В случае если чейн захочет найти регистратора для identity по id, там не будет паники/чего-то другого плохого?

2022-12-28 22:49 UTC, CertainLach commented on tests/src/util/identitySetter.ts
> +      await helper.getSudo().executeExtrinsic(superuser, 'api.tx.identity.forceInsertIdentities', [identitiesToAdd]);
!Важно

2022-12-28 22:49 UTC, CertainLach commented on pallets/identity/src/lib.rs
> -		pub fn set_identities(
!Важно

2022-12-28 22:50 UTC, CertainLach commented on pallets/configuration/src/lib.rs
> +		#[pallet::weight(T::WeightInfo::set_weight_to_fee_coefficient_override())]
Просто заметка, не требует действий

2022-12-28 22:50 UTC, CertainLach commented on pallets/configuration/src/benchmarking.rs
> +		assert_ok!(
Пусть пока так остаётся

2022-12-28 22:50 UTC, CertainLach commented on pallets/collator-selection/src/mock.rs
> +	type WeightInfo = ();
!Важно

2022-12-28 22:50 UTC, CertainLach commented on pallets/collator-selection/src/benchmarking.rs
>  		<LicenseBond<T>>::get() > 0u32.into(),
!Важно

2022-12-29 09:13 UTC, Fahrrader commented on tests/src/util/identitySetter.ts
> +        // 2) it is our own identity, we don't want to delete it.
Хотим, Игорь говорил пример, где он хочет добавить условную ноду Митровича

2022-12-29 09:18 UTC, Fahrrader commented on pallets/configuration/src/benchmarking.rs
> +		assert_ok!(
Да, так было в set_invulnerables, решил уж оставить по примеру

2022-12-29 09:20 UTC, Fahrrader commented on tests/src/util/identitySetter.ts
> +      await helper.getSudo().executeExtrinsic(superuser, 'api.tx.identity.forceInsertIdentities', [identitiesToAdd]);
У нас этих регистраторов вообще нет и не будет в ближайшее время) Всегда будем ссылаться на реле

2022-12-29 09:21 UTC, Fahrrader commented on pallets/collator-selection/src/benchmarking.rs
>  		<LicenseBond<T>>::get() > 0u32.into(),
Что-то оно падает, надо было дебажить и эту, и ещё несколько проблем, но не было времени вечером, отключил. Раскомменчу обратно, но с выключенным прогоном

2022-12-29 10:04 UTC, CertainLach commented on tests/src/util/identitySetter.ts
> +      await helper.getSudo().executeExtrinsic(superuser, 'api.tx.identity.forceInsertIdentities', [identitiesToAdd]);
В том и дело что у нас будут записи, ссылающиеся на несуществующих регистраторов)

2022-12-29 10:05 UTC, CertainLach commented on tests/src/util/identitySetter.ts
> +      await helper.getSudo().executeExtrinsic(superuser, 'api.tx.identity.forceInsertIdentities', [identitiesToAdd]);
Для реле нужно завести отдельного регистратора, и маппить все записи с реле на него
Это также решит проблему с "it is our own identity, we don't want to delete it."

2022-12-29 10:07 UTC, CertainLach commented on runtime/common/config/pallets/collator_selection.rs
> +	type WeightInfo = ();
Пропиши тут тоже правильный WeightInfo, и я принимаю этот PR в develop

2022-12-29 10:08 UTC, Fahrrader commented on tests/src/util/identitySetter.ts
> +      await helper.getSudo().executeExtrinsic(superuser, 'api.tx.identity.forceInsertIdentities', [identitiesToAdd]);
Это было бы решением, да - но потом

2022-12-29 10:17 UTC, CertainLach approved these changes

2022-12-29 10:44 UTC, merged