Feature/core 325
UniqueNetwork/unique-chain pull request #336
Opened 2022-04-07 11:08 UTC by bugrazoid

2022-04-08 08:17 UTC, CertainLach requested changes

2022-04-08 08:17 UTC, CertainLach commented on pallets/nonfungible/src/erc.rs
> +		if let SchemaVersion::ImageURL = self.schema_version {
```rs
if matches!(self.schema_version, ImageURL) {
  return Err(error_unsupported_shema_version())
}
```

2022-04-08 08:17 UTC, CertainLach commented on pallets/nonfungible/src/erc.rs
> +		if let SchemaVersion::ImageURL = self.schema_version {
Тоже лучше early return

2022-04-08 08:17 UTC, CertainLach commented on pallets/nonfungible/src/erc.rs
> +		if let SchemaVersion::ImageURL = self.schema_version {
Early return

2022-04-08 08:17 UTC, CertainLach commented on tests/src/eth/metadata.test.ts
> +    ).send({from: caller})).to.be.rejected;
Предлагаю во всех новых тестах использовать `.rejectedWith`, т.к я уже сталкивался с тем, что старые тесты у нас падали не по тем причинам, по которым ожидали

2022-04-08 13:45 UTC, kozyrevdev requested changes
implement Yaroslav requirements

2022-04-13 08:02 UTC, CertainLach approved these changes

2022-04-21 16:32 UTC, merged