Feature/core 412 Helper for create RFT collection
UniqueNetwork/unique-chain pull request #391
Opened 2022-06-16 08:34 UTC by bugrazoid

2022-06-16 08:51 UTC, CertainLach commented on pallets/unique/src/eth/mod.rs
> +	let data = CreateCollectionData {
Нужно ставить mode, по дефолту он nonfungible

2022-06-17 05:47 UTC, kozyrevdev commented
@bugrazoid switch PR to develop and implement Yaroslav's notes, please

2022-06-17 05:48 UTC, kozyrevdev requested changes
switch PR to develop and implement Yaroslav's notes, please

2022-06-22 13:31 UTC, bugrazoid commented on pallets/unique/src/eth/mod.rs
> +		let collection_id = <pallet_refungible::Pallet<T>>::init_collection(caller.clone(), data)
Тогда его надо доработать, т.к. метод create не возвращает id коллекции. Или есть другие варианты?

2022-06-30 08:15 UTC, CertainLach commented on pallets/unique/src/eth/mod.rs
> +		let collection_id = <pallet_refungible::Pallet<T>>::init_collection(caller.clone(), data)
Да, нужно доработать в таком случае

2022-07-12 04:10 UTC, kozyrevdev requested changes
@ut-akuznetsov @bugrazoid все изменения внутри пакетов(crates, pallets, runtimes, etc) в рамках PR 1)версионируются 2)заносятся в Changelog

2022-07-25 12:03 UTC, CertainLach requested changes

2022-07-25 12:03 UTC, CertainLach commented on pallets/refungible/src/erc.rs
>  impl<T: Config> RefungibleHandle<T> where T::AccountId: From<[u8; 32]> {}
```suggestion
impl<T: Config> RefungibleHandle<T> {}
```
Тут нет методов которые на это полагаются

2022-07-25 12:03 UTC, CertainLach commented on pallets/unique/src/eth/mod.rs
> +fn error_feild_too_long(feild: &str, bound: usize) -> Error {
```suggestion
fn error_field_too_long(feild: &str, bound: usize) -> Error {
```

2022-07-25 15:21 UTC, CertainLach commented on pallets/refungible/src/erc.rs
>  impl<T: Config> RefungibleHandle<T> where T::AccountId: From<[u8; 32]> {}
А, точно

2022-07-25 15:24 UTC, CertainLach requested changes

2022-07-26 06:04 UTC, bugrazoid commented on pallets/nonfungible/CHANGELOG.md
> +      If the collection has a `url` property and it is not empty, it is returned.
Не понял.

2022-07-26 08:03 UTC, CertainLach commented on pallets/nonfungible/CHANGELOG.md
> +      If the collection has a `url` property and it is not empty, it is returned.
Проперти url у нас на токене, не на коллекции

2022-07-26 08:05 UTC, CertainLach commented on pallets/nonfungible/src/erc.rs
> +	///      Else If the collection does not have a property with key `schemaName` or its value is not equal to `ERC721Metadata`, it return an error `tokenURI not set`.
В эфире это не выравнивают по @dev, продолжение идёт просто начиная с одного пробела

```
/// @dev foo
///  bar
```

2022-07-27 06:33 UTC, CertainLach approved these changes

2022-07-27 06:33 UTC, merged