Feature/rmrk resources refactor
UniqueNetwork/unique-chain pull request #392
Opened 2022-06-16 15:19 UTC by MrShiposha

### The changes
* Benchmarks can be run with any runtime:
   - Opal: `make bench`
   - Quartz: `RUNTIME=quartz-runtime make bench`
   - Unique: `RUNTIME=unique-runtime make bench`
* Added "system" properties for NFTs
* RMRK resources refactored: they are stored in the system properties now
* Added benchmarks for proxy RMRK equip
* Added `equippable` extrinsic
* Fix dup parts in `create_base` extrinsic

2022-06-17 13:22 UTC, CertainLach commented on node/cli/Cargo.toml
> +    'opal-runtime/runtime-benchmarks',
Может лучше все рантаймы опциональными сделаем, чтобы с --no-default-features можно было лишь один собирать?)
Не относится к этому PR, просто предложение на размышление

2022-06-17 13:24 UTC, CertainLach commented on runtime/quartz/src/lib.rs
>  		fn nft_resources(collection_id: RmrkCollectionId, nft_id: RmrkNftId) -> Result<Vec<RmrkResourceInfo>, DispatchError> {
Думаю что логику для подобных методов стоит вынести в палету, дабы не дублировать её между рантаймами
Опять же, просто предложение

2022-06-17 13:26 UTC, MrShiposha commented on node/cli/Cargo.toml
> +    'opal-runtime/runtime-benchmarks',
Я, честно говоря, не помню почему нужен был обязательный Opal, надо подумать. Можно будет отдельным PR-ом сделать улучшение

2022-06-17 13:27 UTC, MrShiposha commented on runtime/quartz/src/lib.rs
>  		fn nft_resources(collection_id: RmrkCollectionId, nft_id: RmrkNftId) -> Result<Vec<RmrkResourceInfo>, DispatchError> {
Да, после выделения из common api, имеет смысл убрать в паллету

2022-06-17 13:28 UTC, CertainLach requested changes

2022-06-17 13:28 UTC, CertainLach commented on pallets/nonfungible/src/lib.rs
> +	pub type TokenSysProperties<T: Config> = StorageNMap<
Не нравится мне нейминнг "системные проперти", может всё же AuxProperties/LargeProperties/подобным образом?
Системные properties у нас и в обычных properties лежать могут

2022-06-17 13:29 UTC, MrShiposha commented on pallets/nonfungible/src/lib.rs
> +	pub type TokenSysProperties<T: Config> = StorageNMap<
Хмм, окей. Давай тогда `AuxProperties`

2022-06-17 14:35 UTC, MrShiposha commented on pallets/nonfungible/src/lib.rs
> +	pub type TokenSysProperties<T: Config> = StorageNMap<
Готово

2022-06-17 14:35 UTC, MrShiposha commented on runtime/quartz/src/lib.rs
>  		fn nft_resources(collection_id: RmrkCollectionId, nft_id: RmrkNftId) -> Result<Vec<RmrkResourceInfo>, DispatchError> {
Готово

2022-06-17 15:05 UTC, CertainLach approved these changes

2022-06-21 08:58 UTC, kozyrevdev commented
![image](https://user-images.githubusercontent.com/73348153/174760339-6007d209-c2a3-4f12-b31f-e8002d3d0cf4.png)

@MrShiposha `cargo build --features=quartz-runtime --release`

2022-06-21 10:07 UTC, merged