Add rpc method for total_pieces
UniqueNetwork/unique-chain pull request #411
Opened 2022-06-29 14:12 UTC by bugrazoid

2022-06-29 21:37 UTC, fairax commented on pallets/refungible/src/lib.rs
> +		<Balance<T>>::iter_prefix((collection_id, token_id)).fold(0, |total, piece| total + piece.1)
Can't we just check TotalSupply?

2022-06-30 08:35 UTC, bugrazoid commented on pallets/refungible/src/lib.rs
> +		<Balance<T>>::iter_prefix((collection_id, token_id)).fold(0, |total, piece| total + piece.1)
Для u128 не реализован трейт Sum

2022-06-30 08:36 UTC, bugrazoid commented on pallets/refungible/src/lib.rs
> +		<Balance<T>>::iter_prefix((collection_id, token_id)).fold(0, |total, piece| total + piece.1)
Да, лучше TotalSupply использовать

2022-06-30 14:17 UTC, CertainLach requested changes

2022-06-30 14:17 UTC, CertainLach commented on primitives/data-structs/src/lib.rs
> +	pub pieces: Option<u128>,
А почему тут Option?
Если токен существует - то у него всегда есть pieces

2022-07-05 15:08 UTC, CertainLach requested changes

2022-07-05 15:08 UTC, CertainLach commented on runtime/common/src/runtime_apis.rs
> +                        pieces: Self::total_pieces(collection, token_id)?.expect("Token pieces always must have some value"),
В данном случае поставь лучше .unwrap_or(0), чтобы не полагаться на то, что оба других поля при получении проверяют существование токена

2022-07-06 06:41 UTC, merged