ERC20 API for refungible tokens
UniqueNetwork/unique-chain pull request #413
Opened 2022-06-30 10:17 UTC by fairax

2022-06-30 12:00 UTC, CertainLach requested changes

2022-06-30 12:18 UTC, CertainLach commented on pallets/refungible/src/erc20.rs
> +		Ok(if let CollectionMode::Fungible(decimals) = &self.mode {
UPD: гриша сказал что decimals всегда нулевой

2022-06-30 13:01 UTC, fairax commented on pallets/refungible/src/lib.rs
> +pub mod erc20;
Сделал 
mod erc_token
mod erc

2022-06-30 14:30 UTC, CertainLach approved these changes
Перегенерируй abi/sol (Они изменились, т.к rft token больше не is rft collection), и можно мержить

2022-07-01 09:29 UTC, bugrazoid approved these changes

2022-07-01 12:57 UTC, kozyrevdev commented on pallets/refungible/src/erc.rs
> +extern crate alloc;
@fairax верни лицензию в шапку

2022-07-12 04:09 UTC, kozyrevdev requested changes

2022-07-12 04:09 UTC, kozyrevdev commented on Makefile
> +REFUNGIBLE_EVM_STUBS=./pallets/refungible/src/stubs
@ut-akuznetsov @fairax все изменения внутри пакетов(crates, pallets, runtimes, etc) в рамках PR 1)версионируются 2)заносятся в Changelog

2022-07-21 10:13 UTC, CertainLach requested changes
При repartition нужно добавить эвент сжигания токенов при уменьшении числа pieces, и эвент создания токенов при увеличении
Например

repartition 20 => 60

Должен произвести эвент создания 40 токенов

А

repartition 60 => 20

Сжигания 40 токенов

Аналогичное нужно сделать с субстратными эвентами

2022-07-21 10:18 UTC, fairax commented
Нужно использовать ERC20 Transfer event для этого?

2022-07-22 07:19 UTC, CertainLach approved these changes

2022-07-22 07:24 UTC, CertainLach requested changes

2022-07-22 07:24 UTC, CertainLach commented on tests/src/eth/reFungibleToken.test.ts
> +    expect(events).to.include.deep.members([
А почему .to.include.deep, если мы знаем какие эвенты там происходят, и можем делать .to.deep.equal?

2022-07-22 07:24 UTC, CertainLach commented on tests/src/eth/reFungibleToken.test.ts
> +    expect(events).to.include.deep.members([
.equal

2022-07-22 08:04 UTC, CertainLach approved these changes

2022-07-22 08:05 UTC, merged