Feature/core 410 Properties for RFT
UniqueNetwork/unique-chain pull request #422
Opened 2022-07-08 09:34 UTC by bugrazoid

2022-07-12 04:09 UTC, kozyrevdev requested changes

2022-07-12 04:09 UTC, kozyrevdev commented on pallets/common/src/lib.rs
> +				owner.as_sub(),
@ut-akuznetsov @bugrazoid все изменения внутри пакетов(crates, pallets, runtimes, etc) в рамках PR 1)версионируются 2)заносятся в Changelog

2022-07-13 16:28 UTC, ut-akuznetsov commented on pallets/common/src/lib.rs
> +				owner.as_sub(),
Это просто первый изменнный файл. 
Чейнжлог в данном случае имеется ввиду по refungible паллете. Хотя в будущем, я так понимаю, нам даже на такие мелкие изменения нужно будет поднимать версию паллеты, для версионирования.

2022-07-19 09:22 UTC, CertainLach commented on pallets/refungible/src/common.rs
> +		let weight = <CommonWeights<T>>::set_collection_properties(properties.len() as u32);
Цену задания properties нужно добавить также в create_item/create_multiple_items

2022-07-20 12:54 UTC, CertainLach commented on pallets/refungible/src/common.rs
>  		max_weight_of!(burn_item_partial(), burn_item_fully())
Стоимость задания property нужно учесть в методе `create_multiple_items_ex`

2022-07-20 12:56 UTC, CertainLach commented on pallets/refungible/src/common.rs
> +						.sum::<u64>()
Не уверен возможно ли тут вызвать переполнение, но давай на всякий
```rust
.fold(0u64, |a, b| a.saturating_add(b))
```

2022-07-20 14:22 UTC, CertainLach commented on pallets/refungible/src/common.rs
> +				.sum::<u64>(),
Тут тоже fold

2022-07-20 14:24 UTC, CertainLach commented on pallets/refungible/src/common.rs
> +use sp_runtime::{DispatchError, traits::Saturating};
Импортировать ничего не нужно, у u64 оно и так реализовано:
https://doc.rust-lang.org/core/primitive.u64.html#method.saturating_add

2022-07-21 08:05 UTC, CertainLach approved these changes

2022-07-21 09:00 UTC, merged