feat: Add RPC token_owners method
UniqueNetwork/unique-chain pull request #426
Opened 2022-07-11 07:02 UTC by PraetorP

2022-07-12 04:07 UTC, kozyrevdev requested changes

2022-07-12 04:07 UTC, kozyrevdev commented on client/rpc/src/lib.rs
> +
@ut-akuznetsov @PraetorP все изменения внутри пакетов(crates, pallets, runtimes, etc) в рамках PR 1)версионируются 2)заносятся в Changelog

2022-07-18 05:56 UTC, PraetorP commented on client/rpc/src/lib.rs
> +
Добавил версионирование и ченджлоги + тест для фангбл паллеты.

2022-07-22 07:36 UTC, CertainLach commented on pallets/fungible/src/lib.rs
> +	/// can lead to impact memory allocation + sorting with  `n * log (n)`.
С top-k у нас сложность `O(nlogk)`, а вообще не думаю что стоит писать гипотетические решения проблем в доку)
На практике нам ничего не мешает поддерживать отдельную мапу с Identity хешером, просто в чейне для этого нет необходимости, и мы предлагаем делать это офчейн

2022-07-22 08:14 UTC, CertainLach requested changes

2022-07-22 08:14 UTC, CertainLach commented on tests/src/rpc.test.ts
> +  it('RPC method tokenOnewrs for fungible collection and token', async () => {
```suggestion
  it('RPC method tokenOwners for fungible collection and token', async () => {
```

2022-07-22 08:14 UTC, CertainLach commented on tests/src/refungible.test.ts
> +      expect(owners.length == 10).to.be.true;
```suggestion
      expect(owners.length).to.be.equal(10);
```

2022-07-22 08:14 UTC, CertainLach commented on runtime/common/Cargo.toml
> +version = '0.9.25'
Тут у нас пока версия зависит от polkadot, мы её не бампаем

2022-07-22 08:14 UTC, CertainLach commented on pallets/fungible/src/lib.rs
> +		if res.len() == 0 {
```suggestion
		if res.is_empty() {
```

2022-07-22 08:14 UTC, CertainLach commented on pallets/refungible/src/lib.rs
> +		if res.len() == 0 {
```suggestion
		if res.is_empty() {
```

2022-07-22 08:14 UTC, CertainLach commented on primitives/rpc/src/lib.rs
> +		fn token_owners(collection: CollectionId, token: TokenId) -> Result<Vec::<CrossAccountId>>;
```suggestion
		fn token_owners(collection: CollectionId, token: TokenId) -> Result<Vec<CrossAccountId>>;
```

2022-07-22 08:14 UTC, CertainLach commented on pallets/fungible/src/common.rs
> +		<Pallet<T>>::token_owners(self.id, token).unwrap_or_else(|| vec![])
```suggestion
		<Pallet<T>>::token_owners(self.id, token).unwrap_or_default()
```

2022-07-22 08:15 UTC, CertainLach commented on pallets/refungible/src/common.rs
> +		<Pallet<T>>::token_owners(self.id, token).unwrap_or_else(|| vec![])
```suggestion
		<Pallet<T>>::token_owners(self.id, token).unwrap_or_default()
```

2022-07-22 08:17 UTC, CertainLach commented on runtime/common/Cargo.toml
> +version = '0.9.25'
```suggestion
version = '0.9.24'
```

2022-07-22 08:17 UTC, CertainLach approved these changes

2022-07-22 08:23 UTC, merged

2022-07-22 08:30 UTC, PraetorP commented on runtime/common/Cargo.toml
> +version = '0.9.25'
Принял. Спасибо !