[CORE-124] Doc: architectural changes
UniqueNetwork/unique-chain pull request #427
Opened 2022-07-11 08:54 UTC by Fahrrader

2022-07-11 09:13 UTC, CertainLach commented on pallets/common/src/lib.rs
> +		///
Переносов строк между элементами списка не делают, пруф:
https://doc.rust-lang.org/src/core/slice/mod.rs.html#597

2022-07-11 09:13 UTC, CertainLach commented on pallets/common/src/lib.rs
> +		///
Также название и описание разделяют через ` - `

2022-07-11 09:13 UTC, CertainLach commented on pallets/common/src/lib.rs
> +		/// Only ASCII letters, digits, and symbols '_', '-', and '.' are allowed
Символы стоит обернуть в ``, особенно `_`, т.к в markdown он отвечает за italic

2022-07-11 09:13 UTC, CertainLach commented on pallets/unique/src/lib.rs
> +		///.
Лишняя точка

2022-07-11 09:16 UTC, CertainLach commented on pallets/common/src/lib.rs
> +		///
Названия ещё обычно оборачивают в ``, но в std почему-то так не делают

2022-07-11 10:01 UTC, Fahrrader commented on pallets/common/src/lib.rs
> +		///
Все эти пункты были в старой документации, поправил стиль повсеместно

2022-07-11 10:26 UTC, CertainLach commented on pallets/common/src/lib.rs
> +		///
У нас сейчас новой документации станет больше чем есть старой, и есть смысл адаптироваться под будущий правильный стиль

2022-07-13 11:29 UTC, Maksandre commented on pallets/fungible/src/lib.rs
> +		/// Not default id passed as TokenId argument.
This is only fungible tokens error? What is the default id should be?

2022-07-13 11:29 UTC, Maksandre commented on pallets/fungible/src/lib.rs
> +	/// todo:doc
will todo be fixed here and elsewhere?

2022-07-13 11:29 UTC, Maksandre commented on pallets/nonfungible/src/lib.rs
> +/// Token data, stored independently from other data used to describe it.
Why is this data separated from others? And how to get full data?

2022-07-13 11:29 UTC, Maksandre commented on pallets/nonfungible/src/lib.rs
> +	/// Scoped, auxiliary properties of a token, primarily used for on-chain operations.
Where can it be useful?

2022-07-13 11:29 UTC, Maksandre commented on pallets/scheduler/src/lib.rs
> +		/// Reserve the maximum spendings on a call.
Will this balance become locked? How does this calculate?

2022-07-13 11:29 UTC, Maksandre commented on pallets/scheduler/src/lib.rs
> +		/// Release reserved funds.
In what case will funds released?

2022-07-13 11:29 UTC, Maksandre commented on pallets/structure/src/lib.rs
> +		/// While searching for the owner, reached the depth limit.
What exactly is the depth limit?

2022-07-13 11:29 UTC, Maksandre commented on pallets/structure/src/lib.rs
> +		/// While iterating over children, reached the breadth limit.
What exactly is the breadth limit?

2022-07-13 11:29 UTC, Maksandre commented on primitives/data-structs/src/lib.rs
>  // When adding/removing fields from this struct - don't forget to also update clamp_limits
What are clamp_limits and how can they be updated?

2022-07-13 11:29 UTC, Maksandre commented on primitives/data-structs/src/lib.rs
> +	/// Maximum size of data of a sponsored transaction
In bytes for one transaction?

2022-07-13 11:29 UTC, Maksandre commented on primitives/data-structs/src/lib.rs
> +	/// Can a token be transferred at all
Maybe we can reveal effective limits here, or add a link where they are defined?

2022-07-15 06:46 UTC, Fahrrader commented on client/rpc/src/lib.rs
> +	/// Get effective collection limits
I'm not sure I understand what you mean :) "Effective" means "current", "those that are in effect", these limits are simply the only limits that are currently enforced for a collection AND are able to be changed via an extrinsic. That is not including the numerous constants and other, harder limitations, of course, but they are far too numerous to include in an RPC call. If that was indeed the issue, could you help rephrase it for more clarity? And if it wasn't, please clarify :)

2022-07-15 06:49 UTC, Fahrrader commented on pallets/fungible/src/lib.rs
> +	/// todo:doc
Not in this PR

2022-07-15 10:53 UTC, Maksandre commented on client/rpc/src/lib.rs
> +	/// Get effective collection limits
As I know, if the collection owner didn't set collection limits explicitly, they will be set with default values. So, for example, sponsorTransferTimeout can be ```null``` but the actual (effective) limit will be 5 or so. 

Do you think it's worth clarifying this moment here?

2022-07-15 12:15 UTC, Fahrrader commented on client/rpc/src/lib.rs
> +	/// Get effective collection limits
Yes, that's the point of "effective limits", if a limit is not set, a chain default will be served instead. Okay, will clarify that

2022-07-18 07:56 UTC, CertainLach commented on pallets/unique/src/lib.rs
> +		/// * `amount`: Number of approved transactions overwriting the current number,
amount - это какое количество pieces `spender` может потратить, в случае с NFT валидными значениями будет 0/1, в случае с fungible/refungible - сколько угодно, это не количество транзакций

2022-07-18 14:04 UTC, CertainLach commented on pallets/unique/src/lib.rs
> +		/// An invitation must be pending, see [`set_collection_sponsor`](Call::set_collection_sponsor).
А зачем все такие случаи ты делаешь с кастомным именем? Мне кажется тут логичнее будет писать именно ``[`Call::set_collection_sponsor`]``

2022-07-18 14:07 UTC, CertainLach commented on pallets/unique/src/lib.rs
> +		/// DEPRECATED - use createCollectionEx. Create a Collection of tokens.
А почему тут нейминг с `camelCase`, мы же Rust документируем, и тут принято `snake_case`

2022-07-18 14:09 UTC, CertainLach commented on pallets/unique/src/lib.rs
> +		/// An invitation must be pending, see [`set_collection_sponsor`](Call::set_collection_sponsor).
Ну и также коррктнее будет ссылаться на `Pallet::set_collection_sponsor`

2022-07-18 14:22 UTC, Fahrrader commented on pallets/unique/src/lib.rs
> +		/// DEPRECATED - use createCollectionEx. Create a Collection of tokens.
Это для PolkadotJS apps, первый абзац - это то, что они видят, а в JS названия функций отображаются уже как camelCase.

2022-07-18 14:55 UTC, Fahrrader commented on pallets/unique/src/lib.rs
> +		/// * `token_prefix`: UTF-8 string with token prefix.
UCS-2, наверное?

2022-07-18 15:04 UTC, Fahrrader commented on pallets/unique/src/lib.rs
> +		/// An invitation must be pending, see [`set_collection_sponsor`](Call::set_collection_sponsor).
> с кастомным именем

Чтобы не писать лишних Call::/Pallet::, особенно если ссылаемое находится в том же scope.

2022-07-18 19:14 UTC, CertainLach commented on pallets/unique/src/lib.rs
> +		/// DEPRECATED - use createCollectionEx. Create a Collection of tokens.
Если это только для polkadot.js - то там первой строкой обычно пишут что этот метод делает, чтобы в логах красиво отображалось, и про деприкейт тут не особо уместно

2022-07-18 19:15 UTC, CertainLach commented on pallets/unique/src/lib.rs
> +		/// * `token_prefix`: UTF-8 string with token prefix.
UCS-2, да. Но лучше wide string, кмк такая формулировка известна большему числу людей

2022-07-19 07:33 UTC, CertainLach commented on pallets/unique/src/lib.rs
> +		/// Deprecated! Prefer [`create_collection_ex`][`Pallet::create_collection_ex`] instead.
Причину можно указать прямо в `#[deprecated(note = "...")]`: https://github.com/rust-lang/rfcs/blob/master/text/1270-deprecation.md

2022-07-19 07:38 UTC, Fahrrader commented on pallets/unique/src/lib.rs
> +		/// Deprecated! Prefer [`create_collection_ex`][`Pallet::create_collection_ex`] instead.
Проблема со всем этим, почему всё хочу иметь это в описании - `#[deprecated]` никак не показывается в документации Call, только Pallet

2022-07-19 07:51 UTC, CertainLach commented on pallets/unique/src/lib.rs
> +		/// Deprecated! Prefer [`create_collection_ex`][`Pallet::create_collection_ex`] instead.
Call всё таки про другое, по нему обычно только матчат, вызовы через него не конструируют
Ветку в match для deprecated экстринзика всё равно нужно будет иметь

Поэтому деприкейтить имеет смысл только методы из Pallet

2022-07-22 13:09 UTC, Maksandre approved these changes

2022-07-22 13:41 UTC, CertainLach requested changes

2022-07-22 13:41 UTC, CertainLach commented on primitives/data-structs/src/lib.rs
> +	/// Timeout for sponsoring a token transfer in passed blocks. Chain default: [`MAX_SPONSOR_TIMEOUT`]
Default is either `NFT_SPONSOR_TRANSFER_TIMEOUT`, `FUNGIBLE_SPONSOR_TRANSFER_TIMEOUT`, or `REFUNGIBLE_SPONSOR_TRANSFER_TIMEOUT`. It depends on the collection type

2022-07-22 16:51 UTC, CertainLach approved these changes

2022-07-22 16:51 UTC, merged