feature/CORE-434
UniqueNetwork/unique-chain pull request #430
Opened 2022-07-11 17:15 UTC by andrewsonin

2022-07-12 04:05 UTC, kozyrevdev requested changes

2022-07-12 04:05 UTC, kozyrevdev commented on pallets/foreing-assets/src/lib.rs
> +	//foreign-assets pallet
@str-mv @andrewsonin все изменения внутри пакетов(crates, pallets, runtimes, etc) в рамках PR 1)версионируются 2)заносятся в Changelog

2022-07-13 08:58 UTC, andrewsonin commented on pallets/foreing-assets/src/lib.rs
> +	//foreign-assets pallet
@str-mv убрал это изменение

2022-07-13 09:02 UTC, str-mv commented on pallets/foreing-assets/src/lib.rs
> +	//foreign-assets pallet
Ок. Хотя я не это имел ввиду)
Я про это:
1)версионируются 2)заносятся в Changelog

И первое и второе не имеет смысла т.к. у палеты не было ни одной версии

2022-07-14 08:33 UTC, merged