Doc/struct versioning
UniqueNetwork/unique-chain pull request #434
Opened 2022-07-12 20:59 UTC by str-mv

2022-07-12 21:05 UTC, CertainLach commented
Мне кажется что стоит добавить информацию о том, какой нейминг у версионированных структур будет, слово про first_version (миграции мы будем удалять), а ещё про удаление полей

2022-07-13 12:30 UTC, Maksandre approved these changes

2022-07-14 11:09 UTC, pasynkov approved these changes

2022-07-14 13:43 UTC, CertainLach requested changes

2022-07-14 13:48 UTC, CertainLach commented on crates/struct-versioning/src/lib.rs
> +//! When version become 3 `#[struct_versioning::versioned(version = 3, upper)]` this field will be removed.
Посмотри как выглядит генерируемый код, если не понятно)

2022-08-16 12:21 UTC, CertainLach approved these changes

2022-08-16 12:21 UTC, merged