Doc: Nonfungible pallet
UniqueNetwork/unique-chain pull request #442
Opened 2022-07-19 07:01 UTC by fairax

2022-07-19 07:48 UTC, CertainLach requested changes

2022-07-19 07:48 UTC, CertainLach commented on pallets/nonfungible/src/erc.rs
> +	/// @param key Property key.
Пропущен @return

2022-07-19 07:48 UTC, CertainLach commented on pallets/nonfungible/src/common.rs
> +/// Implementation of `CommonCollectionOperations` for `NonfungibleHandle`. It wraps Nonfungible Pallete
Такое есть смысл документировать?)

2022-07-19 07:48 UTC, CertainLach commented on pallets/nonfungible/src/erc.rs
> +	/// @notice A descriptive name for a collection of NFTs in this contract
Если у первой строки нет префикса - то она считается за @notice

2022-07-19 07:48 UTC, CertainLach commented on pallets/nonfungible/src/lib.rs
> +//! * Total number of tokens of all types shouldn't be greater than `up_data_structs::MAX_TOKEN_PREFIX_LENGTH`.
`MAX_TOKEN_PREFIX_LENGTH` - максимальная длина token_prefix в коллекции, подобного ограничения тут нет

2022-07-19 07:48 UTC, CertainLach commented on pallets/nonfungible/src/lib.rs
> +//! * Sender should be in collection's allow list to perform operations on tokens.
Не обязательно, если у человека есть токен - то он сможет управлять им, даже если он не в allowlist
Мне кажется что для подобных глобальных прав стоит просто сослаться на pallet-common, т.к подобные ограничения у нас везде одинаковы

2022-07-20 05:38 UTC, fairax commented on pallets/nonfungible/src/erc.rs
> +	/// @notice A descriptive name for a collection of NFTs in this contract
https://erc721.org/ тут например `@notice` всё равно пишут.

2022-07-20 06:00 UTC, fairax commented on pallets/nonfungible/src/lib.rs
> +//! * Sender should be in collection's allow list to perform operations on tokens.
Судя по коду все основные операции обязательно проверяют allowlist, и там нет исключения для владельца токена.

И кстати, это нормально что в `create_multiple_items` нет проверки `collection.permissions.access() == AccessMode::AllowList` перед `check_allowlist`?

2022-07-20 06:09 UTC, fairax commented on pallets/nonfungible/src/lib.rs
> +//! * Sender should be in collection's allow list to perform operations on tokens.
Куда можно сослаться в `pallet-common`? Я там не вижу описания того как работает `allowlist`.

2022-07-20 11:42 UTC, Maksandre commented on pallets/nonfungible/src/lib.rs
> +	/// Custom data that is serialized to bytes and attached to a token property.
В чем разница между custom data и не-custom data? В какой момент она появляется у токена

2022-07-20 11:42 UTC, Maksandre commented on pallets/nonfungible/src/lib.rs
> +	/// Create ТFT collection
NFT?

2022-07-20 11:42 UTC, Maksandre commented on pallets/nonfungible/src/lib.rs
> +	/// Destroy ТFT collection
NFT?

2022-07-20 12:02 UTC, CertainLach commented on pallets/nonfungible/src/lib.rs
> +//! * Sender should be in collection's allow list to perform operations on tokens.
Если у алисы есть токен, то она может затрансферить его бобу, даже если она не добавлена в allowlist (при условии если AccessMode не Allowlist, по дефолту он Normal)

2022-07-21 07:34 UTC, Maksandre commented on pallets/nonfungible/src/lib.rs
> +	/// Custom data that is serialized to bytes and attached to a token property.
Т.е custom data это просто значение проперти? Или что то еще может быть?

2022-07-21 09:59 UTC, fairax commented on pallets/nonfungible/src/lib.rs
> +	/// Custom data that is serialized to bytes and attached to a token property.
Это некие дополнительные данные, они добавляются в дополнение к обычному значению property.

2022-07-21 10:07 UTC, CertainLach commented on pallets/nonfungible/src/erc.rs
> +///
Лишняя пустая строка

2022-07-21 10:08 UTC, CertainLach approved these changes

2022-07-21 11:01 UTC, Maksandre approved these changes

2022-07-21 11:08 UTC, merged