Feature: ERC 721 for RFT
UniqueNetwork/unique-chain pull request #452
Opened 2022-07-27 07:48 UTC by fairax

2022-07-27 08:13 UTC, CertainLach requested changes

2022-07-27 08:13 UTC, CertainLach commented on pallets/refungible/src/erc.rs
> +	/// @dev This event emits when RFTs are created (`from` == 0).
При сжигании последней части токена он тоже должен быть

2022-07-27 08:13 UTC, CertainLach commented on pallets/refungible/src/erc.rs
> +	fn transfer_from(
Если владелец токена один - то этот метод можно реализовать
Для эфира кмк это стоит реализовать, т.к у нас там и так create и repartition отдельно

2022-07-27 08:13 UTC, CertainLach commented on pallets/refungible/src/erc.rs
> +	fn burn(&mut self, _caller: caller, _token_id: uint256, _value: value) -> Result<void> {
Для единственного владельца реализация также возможна

2022-07-27 08:43 UTC, bugrazoid commented on Makefile
> +UniqueRefungible.sol:
Уже есть ниже на 45й строке.

2022-07-27 08:43 UTC, bugrazoid commented on Makefile
> +UniqueRefungible: UniqueRefungible.sol
Уже есть ниже на 77й строке.

2022-07-27 08:43 UTC, bugrazoid commented on tests/src/eth/reFungible.test.ts
> +    const contract = new web3.eth.Contract(reFungibleAbi as any, collectionIdAddress, {from: caller, ...GAS_ARGS});
```suggestion
    const contract = evmCollection(web3, caller, collectionIdAddress, {type: 'Refungible'});
```

2022-07-27 08:43 UTC, bugrazoid commented on tests/src/eth/reFungible.test.ts
> +    const contract = evmCollection(web3, owner, collectionIdAddress);
```suggestion
    const contract = evmCollection(web3, caller, collectionIdAddress, {type: 'Refungible'}
```

2022-07-28 06:40 UTC, fairax commented on Makefile
> +UniqueRefungible.sol:
Похоже криво смержилось

2022-07-28 08:05 UTC, bugrazoid approved these changes

2022-08-01 08:31 UTC, CertainLach requested changes

2022-08-01 08:31 UTC, CertainLach commented on pallets/refungible/src/erc.rs
> +		<PalletEvm<T>>::deposit_log(
Эвент должен происходить из кода палеты, не отсюда
На substrate пользователь же тоже может остатки токена перевести

Правда тогда возникает ещё одна проблема: в случае когда у токена был один владелец, а стало 2 - нужн делать трансфер токена на какой-то адрес, т.к у него больше нет sole owner

Как это делают в других реализациях refungible под эфиром?

2022-08-01 08:31 UTC, CertainLach commented on pallets/refungible/src/erc.rs
> +		<PalletEvm<T>>::deposit_log(
Аналогично верхнему вопросу

2022-08-02 06:23 UTC, fairax commented on pallets/refungible/src/erc.rs
> +		<PalletEvm<T>>::deposit_log(
В эвире как я понимаю бросаются только ERC20 события, т.к. ERC721 контракт уходит во владение ERC1633 контракту

2022-08-03 11:29 UTC, CertainLach commented on tests/src/eth/reFungible.test.ts
> +    expect(events).to.deep.equal([
Почему бы не
```diff
-    let transfer;
-    contract.events.Transfer({}, function(_error: any, event: any){ transfer = event;});
-    await tokenContract.methods.transfer(receiver, 1).send();
-    const events = normalizeEvents([transfer]);
-    expect(events).to.deep.equal([
+    const result = await tokenContract.methods.transfer(receiver, 1).send();
+    expect(result.events).to.deep.equal([
```
?

2022-08-03 11:30 UTC, CertainLach commented on tests/src/eth/reFungible.test.ts
> +    expect(events).to.deep.equal([
Аналогичный вопрос по получению ивентов

2022-08-03 11:33 UTC, fairax commented on tests/src/eth/reFungible.test.ts
> +    expect(events).to.deep.equal([
Потому что `tokenContract` это не тот контракт. И нужное событие в result не попадает. Соответственно я жду событие на контракте `contract`.

2022-08-03 11:33 UTC, fairax commented on tests/src/eth/reFungible.test.ts
> +    expect(events).to.deep.equal([
Ответил выше

2022-08-03 11:34 UTC, CertainLach commented on tests/src/eth/reFungible.test.ts
> +    expect(events).to.deep.equal([
В result должны попадать все события вызванные транзакцией, даже если они вылетают из других контрактов

2022-08-03 11:36 UTC, CertainLach commented
Раз уж у нас теперь всё так сделано с частичным владением - create_multiple_items_ex с несколькими пользователями должен тоже так работать -
Если токен создаётся для нескольких пользователей, то ERC721Events::Transfer должен идти на адрес 0xffff...ffff

2022-08-03 11:41 UTC, CertainLach commented
Не обрабатывается burn:
1. Алиса имеет 20 pieces, totalSupply = 20 (owner_of == Alice)
2. Алиса передаёт бобу 10 pieces (owner_of == 0xffff...ffff)
3. Боб сжигает 10 pieces (owner_of == 0xffff...ffff, а должна быть алиса, т.к теперь она единственный владелец)

Это я про owner_of, который будет видеть внешний наблюдатель по событиям, на шаге 3 должен быть трансфер с 0xffff...ffff на алису

2022-08-03 11:43 UTC, CertainLach commented
События при полном сжигании токена
https://github.com/UniqueNetwork/unique-chain/blob/bb6d71bbdc4d5eaa6f6f22b79de3b125297f1712/pallets/refungible/src/lib.rs#L457-L470

По идее должны переехать в метод burn_token_unchecked

2022-08-03 15:30 UTC, fairax commented
Перенёс только `ERC721Events::Transfer`, иначе нужно добавлять дополнительные параметры в `burn_token_unchecked`

2022-08-03 16:04 UTC, CertainLach approved these changes

2022-08-04 07:04 UTC, ut-akuznetsov approved these changes

2022-08-04 12:21 UTC, merged