fix: disbaled pallets
UniqueNetwork/unique-chain pull request #462
Opened 2022-08-01 10:06 UTC by PraetorP

Rmrk, RFT, Scheduler for Quartz
RFT, Scheduler for Unique
Added the logic of checking the availability of pallets necessary for their execution in tests

2022-08-03 07:36 UTC, CertainLach commented on runtime/common/src/runtime_apis.rs
> +                    return Ok(Default::default());
Не лучше ли будет возвращать тут ошибки?

2022-08-03 07:41 UTC, CertainLach commented on runtime/quartz/src/lib.rs
> +#[cfg(feature = "rmrk")]
Мне кажется что подобное стоит просто удалить, а когда понадобится - скопировать обратно из опала
Потому что никто не будет проверять что оно рабочее, и это будет всё такой же мёртвый код

2022-08-11 06:59 UTC, CertainLach requested changes

2022-08-11 06:59 UTC, CertainLach commented on common-types/Cargo.toml
> +[package]
Не надо такое в корень репы выносить, убери это в директорию runtime

2022-08-11 06:59 UTC, CertainLach commented on common-types/Cargo.toml
> +[package]
Также мне не понятно зачем оно вынесено из runtime/common

2022-08-11 06:59 UTC, CertainLach commented on runtime/common/construct_runtime/mod.rs
> +                #[runtimes(opal)]
Почему тут это сделано по рантаймам, когда везде в других местах это сделано по фичам?

2022-08-11 06:59 UTC, CertainLach commented on tests/src/util/helpers.ts
> +    console.log('\x1b[38:5:208m%s\x1b[0m', skipMsg);
Лучше выводить такое в console.error (stderr), т.к это ломает tap reporter, который используется расширением в vscode

2022-08-11 07:40 UTC, MrShiposha commented on common-types/Cargo.toml
> +[package]
Оно вынесено из runtime/common потому что оно должно использоваться в самой ноде, но runtime/common перестал быть крейтом, а стал просто модулем. Не хотелось использовать #[path = "..."] в самой ноде.

Хотелось выделить вещи, которые используются одновременно рантаймами и нодой

2022-08-11 07:41 UTC, MrShiposha commented on runtime/common/construct_runtime/mod.rs
> +                #[runtimes(opal)]
Я с удовольствием бы сделал с фичами -- было бы отлично. Это можно сделать, но поддержку для этого надо сделать прямо в самом макросе `construct_runtime!`. Надо делать PR в Parity

2022-08-11 07:44 UTC, CertainLach commented on common-types/Cargo.toml
> +[package]
Обычно такое в примитивы выносят

2022-08-11 07:45 UTC, CertainLach commented on common-types/Cargo.toml
> +[package]
Перенеси тогда эту директорию туда, только не в up-data-structs

2022-08-11 09:54 UTC, MrShiposha commented on common-types/Cargo.toml
> +[package]
Перенес в `up-common`. Туда же убрал константы, потому что некоторые из них могут использоваться и в паллетах. Например, в app promotion.

2022-08-11 09:54 UTC, MrShiposha commented on tests/src/util/helpers.ts
> +    console.log('\x1b[38:5:208m%s\x1b[0m', skipMsg);
Done.

2022-08-11 13:18 UTC, merged