Feature/refactor contract sponsoring
UniqueNetwork/unique-chain pull request #469
Opened 2022-08-04 14:09 UTC by bugrazoid

Refactor contract sponsoring to allow set defined sponsor.

2022-08-05 13:10 UTC, CertainLach requested changes

2022-08-05 13:10 UTC, CertainLach commented on pallets/common/src/eth.rs
> +	uint256::from_big_endian(slice)
CrossAccountId можно закодировать либо как тип аккаунта + u256, либо прибегнуть к каким-нить хитростям

Например, как насчёт такого:
Если получаем CrossAccountId::Substrate - то просто перекодируем адрес в uint256
Если получаем CrossAccountId::Ethereum - то последние 20 байт заполняем оригинальным адресом, а первые 12 - чем-то, что помешает сгенерировать для адреса приватный ключ, но позволит проверить что это у нас не substrate адрес на входе, а эфирный, например генерировать хеш из входящего блока 256бит, и брать от него первые 96

Таким образом при декодировании мы проверяем совпадение хеша, и если хеш не валидный - то значит это substrate аккаунт, иначе - эфирный

2022-08-05 13:10 UTC, CertainLach commented on pallets/evm-contract-helpers/src/lib.rs
> +			let storage_version = StorageVersion::get::<Pallet<T>>();
Зачем это?

2022-08-05 13:10 UTC, CertainLach commented on pallets/evm-contract-helpers/src/eth.rs
> +	fn get_sponsor(&self, contract_address: address) -> Result<(address, uint256)> {
Не возвращается каноничная форма, оригинальный адрес пришёл из эфира или из субстрата?
Ну и думаю что излишне возвращать обе формы, см как я предлагаю кодировать адрес в convert_cross_account_to_eth_uint256

2022-08-05 13:10 UTC, CertainLach commented on pallets/evm-contract-helpers/src/eth.rs
> +			None => return None,
self-sponsoring мы точно хотим убрать? В большинстве случаев кмк его будет хватать пользователям

2022-08-05 13:10 UTC, CertainLach commented on pallets/evm-contract-helpers/src/eth.rs
> +	fn set_sponsor(
Добавь документацию на новые методы

2022-08-05 13:10 UTC, CertainLach commented on pallets/common/src/eth.rs
> +	let slice = from.as_sub().as_ref();
Нужна проверка что слайс действительно 32 байта
А ещё лучше - на уровне системы типов не пускать сюда адреса других размеров

У AccountId32 нет реализации `Into<H256>`?

2022-08-05 13:10 UTC, CertainLach commented on pallets/evm-contract-helpers/src/lib.rs
> +					Sponsoring::<T>::mutate_exists(contract, |state| {
Sponsoring::set, mutate нужен когда мы одновременно читаем и пишем
В данном случае можно вместе с верхним Sponsoring::get заменить это на try_mutate, однако в данном случае читаемее будет именно get+set (Тем более что семантика одинаковая)

2022-08-05 15:58 UTC, bugrazoid commented on pallets/common/src/eth.rs
> +	let slice = from.as_sub().as_ref();
Нет, у AccountId32 нет реализации Into<H256>.

2022-08-23 09:00 UTC, CertainLach requested changes

2022-08-23 09:00 UTC, CertainLach commented on pallets/common/src/eth.rs
> +	if slice.len() != 32 {
Лучше такие ограничения на уровне системы типов ловить, проброшены же уже везде баунды необходимые

2022-08-23 09:00 UTC, CertainLach commented on pallets/evm-contract-helpers/src/eth.rs
> +	fn self_sponsored_enable(&mut self, caller: caller, contract_address: address) -> Result<void> {
Для всех пишущих методов нужен либо атрибут weight, либо соответствующие вызовы .consume_

2022-08-23 09:00 UTC, CertainLach commented on pallets/evm-contract-helpers/src/eth.rs
> +	fn get_sponsor(&self, contract_address: address) -> Result<(address, uint256)> {
Не возвращается каноничная форма, нужно добавление метода в апи CrossAccountId (frontier)

2022-08-23 09:00 UTC, CertainLach commented on pallets/evm-contract-helpers/src/lib.rs
> +	pub(super) type Sponsoring<T: Config> = StorageMap<
У нас будущей задачей стоит добавление лимитов спонсоринга/ограничения спонсорства по методам
Надо предусмотреть это в структуре, дабы фронтам потребовалось меньше миграций
value должен быть структурой, текущий sponsorshipstate можно там поставить как поле default_sponsor (слово default в js - reserved)

2022-08-24 13:58 UTC, CertainLach requested changes

2022-08-24 13:58 UTC, CertainLach commented on pallets/evm-contract-helpers/src/eth.rs
> +		self.recorder().consume_sload()?;
Это надо делать до чтений/записей, т.к оно кидает ошибку в случае если газа не хватит

2022-08-24 13:58 UTC, CertainLach commented on pallets/evm-contract-helpers/src/eth.rs
> +		self.recorder().consume_sload()?;
Аналогично в остальных местах

2022-08-25 08:52 UTC, CertainLach commented
Не хватает только вызова cargo fmt, CI жалуется)

2022-08-25 09:00 UTC, merged