Feature: fractionalizer contract
UniqueNetwork/unique-chain pull request #471
Opened 2022-08-04 14:56 UTC by fairax

2022-08-04 20:06 UTC, ut-akuznetsov commented on tests/src/eth/fractionalizer/Fractionalizer.sol
> +            "Fractionalizer contract should be an admin of the collection"
typo?

2022-08-05 08:37 UTC, CertainLach commented on pallets/nonfungible/src/common.rs
> +		0 //<SelfWeightOf<T>>::token_owner()
А зачем бенчмарк, если тут 0?

2022-08-05 08:41 UTC, CertainLach requested changes

2022-08-05 08:41 UTC, CertainLach commented on pallets/refungible/src/erc_token.rs
> +		let props = <TokenProperties<T>>::get((self.id, self.1));
У нас parent токен никогда не изменяется, это всегда ERC721 часть refungible токена

2022-08-05 08:41 UTC, CertainLach commented on pallets/refungible/src/erc_token.rs
> +	fn set_parent_nft(
И изменять его нельзя

2022-08-05 08:43 UTC, fairax commented on pallets/nonfungible/src/common.rs
> +		0 //<SelfWeightOf<T>>::token_owner()
Не понял вопрос. Тут 0, а в других имплементациях нет.

2022-08-05 09:52 UTC, Maksandre approved these changes

2022-08-05 09:52 UTC, Maksandre commented on pallets/nonfungible/src/weights.rs
> +		(20_909_000 as Weight)
Как высчитываются эти числа?

2022-08-05 10:59 UTC, fairax commented on pallets/fungible/src/stubs/UniqueFungible.sol
> +// Selector: 942e8b22
Это `interface identifier` из ERC165 https://eips.ethereum.org/EIPS/eip-165
`We define the interface identifier as the XOR of all function selectors in the interface`

2022-08-05 11:00 UTC, fairax commented on pallets/nonfungible/src/weights.rs
> +		(20_909_000 as Weight)
Автоматически с помощью бенчмарков. @CertainLach знает про это больше наверное.

2022-08-05 12:21 UTC, CertainLach commented on pallets/nonfungible/src/common.rs
> +		0 //<SelfWeightOf<T>>::token_owner()
Но ты написал бенчмарк, зачем он в таком случае, если его результаты не используются?

2022-08-05 12:22 UTC, CertainLach commented on pallets/nonfungible/src/weights.rs
> +		(20_909_000 as Weight)
weights.rs генерируется автоматически
Это время затраченное на исполнение бенчмарка

2022-08-05 12:22 UTC, CertainLach commented on pallets/fungible/src/stubs/UniqueFungible.sol
> +// Selector: 942e8b22
Эти .sol файлы генерируются автоматически

2022-08-08 07:03 UTC, fairax commented on pallets/nonfungible/src/common.rs
> +		0 //<SelfWeightOf<T>>::token_owner()
Извиняюсь, по не внимательности подумал что это код из fungible палеты. Поправил метод.

2022-08-08 07:43 UTC, CertainLach requested changes

2022-08-08 07:43 UTC, CertainLach commented on .maintain/scripts/compile_fractionalizer.sh
> +mv refungible_input_sol_Fractionalizer.bin $dir/tests/src/eth/fractionalizer/Fractionalizer.bin
Нам не обязательно сохранять этот файл в репу, для stubs это делается чтобы ноду можно было собирать без yarn install

Компилируй этот контракт прямо из кода

2022-08-08 14:14 UTC, CertainLach approved these changes

2022-08-08 14:22 UTC, CertainLach requested changes

2022-08-08 14:22 UTC, CertainLach commented on tests/src/eth/fractionalizer/Fractionalizer.sol
> +        owner = msg.sender;
Для определения владельцев контрактов у нас есть метод в ContractHelpers

2022-08-08 14:22 UTC, CertainLach commented on tests/src/eth/fractionalizer/Fractionalizer.sol
> +            keccak256(bytes(collectionType)) == refungibleCollectionType,
Зачем сравнивать через хеш, если можно сравнить напрямую со строкой?

2022-08-08 14:22 UTC, CertainLach commented on tests/src/eth/fractionalizer/Fractionalizer.sol
> +        rftCollectionContract.transferFrom(msg.sender, address(this), _token);
А зачем мы оставляем этот токен?

2022-08-08 14:23 UTC, CertainLach commented on tests/src/eth/fractionalizer/Fractionalizer.sol
> +        rftCollectionContract.transferFrom(msg.sender, address(this), _token);
В плане, какой смысл от переиспользования токенов для фракционализации?

2022-08-08 15:29 UTC, fairax commented on tests/src/eth/fractionalizer/Fractionalizer.sol
> +            keccak256(bytes(collectionType)) == refungibleCollectionType,
пишут что так меньше газа тратится

2022-08-09 05:57 UTC, fairax commented on tests/src/eth/fractionalizer/Fractionalizer.sol
> +        rftCollectionContract.transferFrom(msg.sender, address(this), _token);
Андрей вроде ответил.

2022-08-09 12:21 UTC, gregzaitsev requested changes

2022-08-09 12:21 UTC, gregzaitsev commented on tests/src/eth/fractionalizer/Fractionalizer.sol
> +    function setRFTCollection(address _collection) public onlyOwner {
Please document all public methods (e.g. with Javadoc format) and public properties

2022-08-09 12:21 UTC, gregzaitsev commented on tests/src/eth/fractionalizer/Fractionalizer.sol
> +        UniqueNFT(nftToken._collection).transferFrom(
Shouldn't we use just `transfer()` instead of `transferFrom()`? Will `transferFrom()` work without `approve()`?

2022-08-09 12:21 UTC, gregzaitsev commented on tests/src/eth/fractionalizer/Fractionalizer.sol
> +        UniqueNFT(nftToken._collection).transferFrom(
Comment 2: What if the NFT collection owner turns transfers off? Will this contract succeed anyway, since there is no `require` around this transfer?

2022-08-09 12:21 UTC, gregzaitsev commented on tests/src/eth/fractionalizer/Fractionalizer.sol
> +        UniqueNFT(_collection).transferFrom(
If collection owner forbids transfers, will this call succeed anyway?

2022-08-10 06:43 UTC, fairax commented on tests/src/eth/fractionalizer/Fractionalizer.sol
> +contract Fractionalizer {
Как я понял контракты по умолчанию себя ведут как будто у них есть default non-payable метод. Добавил onlyOwner reсeive метод, чтобы только владелец мог переводить QTZ/UNQ.

2022-08-10 07:46 UTC, CertainLach commented on tests/src/eth/fractionalizer/Fractionalizer.sol
> +            keccak256(bytes(collectionType)) == refungibleCollectionType,
Хмм, это конечно странно, но предположим, у EVM много странностей

2022-08-10 07:48 UTC, CertainLach commented on tests/src/eth/fractionalizer/Fractionalizer.sol
> +    function setRFTCollection(address _collection) public onlyOwner {
Тот же формат что и для методов в контрактах на стороне Rust*

2022-08-10 07:50 UTC, CertainLach commented on tests/src/eth/fractionalizer/Fractionalizer.sol
> +        UniqueNFT(nftToken._collection).transferFrom(
`transfer()` это нестандартный метод, который мы однако реализуем
Думаю что в наших контрактах мы можем такое использовать, однако это сломает совместимость этого контракта с обычными (не нашими) ERC721 токенами, что ИМХО тоже ок, потому что у нас на чейне предпочтительно использовать наши интерфейсы вместо своих реализаций NFT

2022-08-10 07:50 UTC, fairax commented on tests/src/eth/fractionalizer/Fractionalizer.sol
> +        UniqueNFT(nftToken._collection).transferFrom(
В `UniqueNFT` контракте нет метода `transfer`. Если отправляешь свои токены то для `transferFrom` `approve` не нужен.

2022-08-10 07:51 UTC, CertainLach commented on tests/src/eth/fractionalizer/Fractionalizer.sol
> +        UniqueNFT(nftToken._collection).transferFrom(
transferFrom кидает ошибку (revert) в случае если трансферы выключены

2022-08-10 07:51 UTC, fairax commented on tests/src/eth/fractionalizer/Fractionalizer.sol
> +        UniqueNFT(nftToken._collection).transferFrom(
Контракт упадёт и вернёт субстратную ошибку.

2022-08-10 07:51 UTC, CertainLach commented on tests/src/eth/fractionalizer/Fractionalizer.sol
> +        UniqueNFT(nftToken._collection).transferFrom(
Возврат true нужен по другим причинам, в основном из-за легаси

2022-08-10 07:51 UTC, fairax commented on tests/src/eth/fractionalizer/Fractionalizer.sol
> +        UniqueNFT(_collection).transferFrom(
Контракт упадёт и вернёт субстратную ошибку.

2022-08-10 08:02 UTC, CertainLach commented on tests/src/eth/fractionalizer/Fractionalizer.sol
> +        UniqueNFT(nftToken._collection).transferFrom(
```solidity
    function transferFrom(address _from, address _to, uint256 _tokenId) external payable;
```

В ERC721 этого легаси даже нет уже)

2022-08-10 15:27 UTC, CertainLach commented on tests/src/eth/fractionalizer/Fractionalizer.sol
> +        UniqueNFT(nftToken._collection).transferFrom(
Как же нет, вот он:
https://github.com/UniqueNetwork/unique-chain/blob/master/pallets/nonfungible/src/erc.rs#L455

2022-08-11 07:01 UTC, CertainLach commented on tests/src/eth/fractionalizer/Fractionalizer.sol
> +contract Fractionalizer {
Емнип начиная с какой то версии solidity, фолбек метод стал nonpayable, а до этого его нужно было вручную объявлять

2022-08-11 08:08 UTC, gregzaitsev approved these changes

2022-08-11 08:08 UTC, gregzaitsev commented on tests/src/eth/fractionalizer/Fractionalizer.sol
> +    //TODO: add nonPayable  modifier after Solidity updates to 0.9.
Решили что не нужно, уберите от греха подальше

2022-08-11 10:22 UTC, CertainLach approved these changes

2022-08-11 12:23 UTC, ut-akuznetsov approved these changes

2022-08-11 14:21 UTC, CertainLach requested changes

2022-08-11 14:21 UTC, CertainLach commented on pallets/common/src/erc.rs
> +	fn verify_owner_or_admin(&mut self, _caller: caller, user: address) -> Result<bool> {
Если caller не используется - то этот аргумент можно убрать

2022-08-11 18:27 UTC, CertainLach approved these changes

2022-08-11 18:46 UTC, merged