Ci 40 - Adding Integration test in parachain mode
UniqueNetwork/unique-chain pull request #474
Opened 2022-08-08 09:49 UTC by lzadjsf

Has been added workflow for lunching of integration tests at PR in parachain mode at master branch

2022-08-08 15:19 UTC, kozyrevdev commented on .github/workflows/build-test-master.yml
> +  RUST_TOOLCHAIN: nightly-2022-05-11
бери переменную из корневого .env
иначе мы запутаемся в 100500 обновлять

2022-08-08 15:19 UTC, kozyrevdev commented on .github/workflows/build-test-master.yml
> +  POLKA_VERSION: release-v0.9.24
аналогично, возьми POLKADOT_BUILD_BRANCH из корневого .env

2022-08-08 15:20 UTC, kozyrevdev commented on .github/workflows/build-test-master.yml
> +            POLKA_VERSION=${{ env.POLKA_VERSION }}
rename POLKADOT_BUILD_BRANCH

2022-08-08 15:21 UTC, kozyrevdev requested changes
also please update develop dockers to use .env file

2022-08-09 21:08 UTC, lzadjsf commented on .github/workflows/build-test-master.yml
> +  RUST_TOOLCHAIN: nightly-2022-05-11
Добавил в workflow новый step который читает .env из корневого каталога репозитория.

2022-08-09 21:09 UTC, lzadjsf commented on .github/workflows/build-test-master.yml
> +            POLKA_VERSION=${{ env.POLKA_VERSION }}
сделано.

2022-08-10 07:32 UTC, closed without merging