Feature/playgrounds
UniqueNetwork/unique-chain pull request #479
Opened 2022-08-09 07:45 UTC by Maksandre

2022-08-09 18:12 UTC, ut-akuznetsov requested changes

2022-08-09 18:12 UTC, ut-akuznetsov commented on tests/src/util/playgrounds/unique.ts
> +  /**
Typo

2022-08-09 18:12 UTC, ut-akuznetsov commented on tests/src/util/playgrounds/unique.ts
> +   * @returns instance of UniqueNFTCollection
UniqueFTCollection

2022-08-09 18:12 UTC, ut-akuznetsov commented on tests/src/util/playgrounds/unique.ts
> +   * @returns instance of UniqueNFTCollection
Unique RFTCollection

2022-08-09 18:12 UTC, ut-akuznetsov commented on tests/src/util/playgrounds/unique.ts
> +   * Change ownership of a NFT on behalf of the owner.
Not NFT, any token (include refungible and fungible, see `amount` param)

2022-08-09 18:12 UTC, ut-akuznetsov commented on tests/src/util/playgrounds/unique.ts
> +   * Destroys a concrete instance of NFT.
Any token

2022-08-09 18:12 UTC, ut-akuznetsov commented on tests/src/util/playgrounds/unique.ts
> +   * Destroys a concrete instance of NFT on behalf of the owner
Any token

2022-08-09 18:12 UTC, ut-akuznetsov commented on tests/src/util/playgrounds/unique.ts
> +   * Set, change, or remove approved address to transfer the ownership of the NFT.
Any token

2022-08-09 18:12 UTC, ut-akuznetsov commented on tests/src/util/playgrounds/unique.ts
> +   * Get amount of RFT pieces approved to transfer
Not only RFT, fungible and nonfungible also uses this method. `token` instead of `RFT`

2022-08-09 18:12 UTC, ut-akuznetsov commented on tests/src/util/playgrounds/unique.ts
> +   * Get top 10 token owners
Not token, im not sure how to write this, but it's for collection

2022-08-09 18:12 UTC, ut-akuznetsov commented on tests/src/util/playgrounds/unique.ts
> +   *
Total supply?

2022-08-09 18:12 UTC, ut-akuznetsov commented on tests/src/util/playgrounds/unique.ts
> +  getOneTokenNominal(): bigint {
add doc to this method too

2022-08-09 18:12 UTC, ut-akuznetsov commented on tests/src/util/playgrounds/unique.ts
> +  normalizeSubstrate(address: TSubstrateAccount, ss58Format = 42): TSubstrateAccount {
And to this. This method normalizes address to any ss58 format (42 for default)

2022-08-12 06:00 UTC, ut-akuznetsov approved these changes

2022-08-12 09:42 UTC, CertainLach approved these changes

2022-08-12 09:42 UTC, merged