Feature: Mint for fungible tokens
UniqueNetwork/unique-chain pull request #483
Opened 2022-08-11 09:57 UTC by fairax

2022-08-18 08:39 UTC, CertainLach commented
В #510 некорректный подсчёт размеров
				`let size = if <($($ident,)+)>::is_simple() { Some(0 $(+aligned_size(sp_std::mem::size_of::<$ident>()))+) } else { None };`

Вместо этого кода нужно добавить метод `size_words(&self)` в AbiRead, который возвращает сколько слов в текущем subresult должен съедать текущий тип
Это 1 для всех uint*/bytes (т.к inline хранится только размер)/прочих, и рекурсивный подсчёт для таплов

2022-08-19 17:40 UTC, CertainLach commented on crates/evm-coder/src/abi.rs
> +				0 $(+ {let _ : $ident; ABI_ALIGNMENT})+
```suggestion
				0 $(+ $ident::size())+
```
Для поддержки tuple внутри tuple

2022-08-24 09:37 UTC, bugrazoid commented on crates/evm-coder/src/abi.rs
> +				0 $(+ {let _ : $ident; ABI_ALIGNMENT})+
Только так не получиться, т.к. у нас простые типы не имплементируют трэйт AbiRead

2022-08-24 10:22 UTC, CertainLach commented on crates/evm-coder/src/abi.rs
> +				0 $(+ {let _ : $ident; ABI_ALIGNMENT})+
Это какие?

2022-08-24 10:24 UTC, CertainLach commented on crates/evm-coder/src/abi.rs
> +				0 $(+ {let _ : $ident; ABI_ALIGNMENT})+
Там есть макрос impl_abi_readable, который как раз это реализует

2022-08-29 16:14 UTC, CertainLach requested changes

2022-08-29 16:14 UTC, CertainLach commented on crates/evm-coder/src/abi.rs
> +		impl AbiRead<$ty> for $ty {
Ээээ, а как это работать должно?)
Я думал ты хочешь сделать так:
```rust
impl AbiRead for $ty {
  fn abi_read(reader: &mut AbiReader<'_>) -> Result<Self>;
}
```
И вызывать это надо будет так:
```rust
u32::abi_read(&mut reader)
```

А с таким implом что делать вообще нужно?)

2022-08-30 08:05 UTC, CertainLach approved these changes

2022-08-30 08:06 UTC, merged