Feature: Change collection owner
UniqueNetwork/unique-chain pull request #503
Opened 2022-08-16 08:05 UTC by fairax

2022-08-19 13:53 UTC, CertainLach requested changes

2022-08-19 13:53 UTC, CertainLach commented on pallets/common/src/erc.rs
> +	fn verify_owner_or_admin_substrate(&self, user: uint256) -> Result<bool> {
У эфира есть перегрузки, лучше использовать их

2022-08-19 13:53 UTC, CertainLach commented on pallets/common/src/erc.rs
> +	fn change_owner_substrate(&mut self, caller: caller, new_owner: uint256) -> Result<void> {
Аналогично с перегрузками

2022-08-19 13:53 UTC, CertainLach commented on pallets/common/src/lib.rs
> +		<CollectionById<T>>::insert(self.id, self.collection.clone());
Второй аргумент может быть референсом

2022-08-19 13:53 UTC, CertainLach commented on pallets/common/src/lib.rs
> +		self.save()
Для контракта в common есть автоматическое сохранение
save принимает владение, чтобы хендл сохраняли лишь в одном месте

2022-08-23 08:03 UTC, fairax commented on pallets/common/src/lib.rs
> +		self.save()
Не совсем понял как нужно исправить. Удаление строки self.save() ломает тесты, т.е. изменения не сохраняются.

2022-08-23 08:18 UTC, fairax commented on pallets/common/src/erc.rs
> +	fn verify_owner_or_admin_substrate(&self, user: uint256) -> Result<bool> {
Заменил на перегрузку, но мне не очень нравится как теперь метод вызывается в typescript.

2022-08-23 08:28 UTC, bugrazoid commented on pallets/common/src/erc.rs
> +where
В моем параллельном ПР я это вынес сюда: https://github.com/UniqueNetwork/unique-chain/blob/c93b71a56e0042cc03f8848e72fc01e9d967ca53/pallets/common/src/eth.rs#L54
Сделай так же, что бы в одном месте было, потом при мерже поправим.

2022-08-23 08:48 UTC, CertainLach requested changes

2022-08-23 08:48 UTC, CertainLach commented on pallets/common/src/erc.rs
> +			.map(|_| true)
`.is_ok()`
А лучше сконвертировать ошибку в evm через dispatch_to_evm, метод же verify называется
Либо префикс названия на is_ поменять

2022-08-23 08:48 UTC, CertainLach commented on pallets/common/src/erc.rs
> +	fn change_owner(&mut self, caller: caller, new_owner: address) -> Result<void> {
set_owner для консистентности нейминга

2022-08-23 09:42 UTC, CertainLach commented on pallets/common/src/erc.rs
> +	fn verify_owner_or_admin_substrate(&self, user: uint256) -> Result<bool> {
В ethers с этим всё лучше, а в solidity так вообще замечательно)
В web3.js такое себе, согласен, однако и там есть более удобные способы на подобные случаи, например в данном случае нам подойдёт такое:
```
// У перегруженных методов есть ключи с типами, если верить докам:
contract.methods.verifyOwnerOrAdmin.uint256(...)
```

2022-08-23 09:46 UTC, CertainLach commented on pallets/common/src/lib.rs
> +		self.save()
Да, понял.
Не нравится мне вся наша история с сохранением, однако лучше ничего придумать не могу, и пока мы в коде не взаимодействуем с несколькими коллекциями одновременно, а методы атомарны - пусть остаётся так

Проблемы начнутся когда мы начнём дёргать из коллекций методы других контрактов, и при этом ещё как-то сохранять сами метаданные коллекций. Хорошо что я пока юзкейсов на горизонте не вижу)

2022-08-23 13:47 UTC, ut-akuznetsov commented on pallets/common/src/erc.rs
> +	fn verify_owner_or_admin_substrate(&self, user: uint256) -> Result<bool> {
Отдельные названия - это запрос от бизнеса, давайте не будем перегружать в случае субстрата

2022-08-24 09:02 UTC, CertainLach approved these changes

2022-08-24 09:42 UTC, bugrazoid approved these changes

2022-08-24 10:20 UTC, merged