path: Fix parsing simple values.
UniqueNetwork/unique-chain pull request #510
Opened 2022-08-17 06:59 UTC by bugrazoid

2022-08-17 08:22 UTC, CertainLach requested changes
Добавь юнит тест на базе mint_bulk

2022-08-17 08:22 UTC, CertainLach commented on crates/evm-coder/src/abi.rs
> +		let is_pad_zeroed = !buf[pad_start..pad_size].iter().all(|&v| v == 0);
Условие тут обратное

2022-08-17 08:22 UTC, CertainLach commented on crates/evm-coder/src/abi.rs
> +				let size = if <($($ident,)+)>::is_simple() { Some(0 $(+aligned_size(sp_std::mem::size_of::<$ident>()))+) } else { None };
Разве там нигде размер массива не закодирован?

2022-08-17 12:00 UTC, bugrazoid commented on crates/evm-coder/src/abi.rs
> +				let size = if <($($ident,)+)>::is_simple() { Some(0 $(+aligned_size(sp_std::mem::size_of::<$ident>()))+) } else { None };
Тут не размер массива, а размер списка.

2022-08-18 08:30 UTC, CertainLach commented on crates/evm-coder/src/abi.rs
> +				let size = if <($($ident,)+)>::is_simple() { Some(0 $(+aligned_size(sp_std::mem::size_of::<$ident>()))+) } else { None };
Тип элементов мы знаем, и можем подсчитать размер на этапе компиляции, лучше так чем смотреть выравнивание

2022-08-18 08:30 UTC, CertainLach commented on crates/evm-coder/src/abi.rs
> +				let size = if <($($ident,)+)>::is_simple() { Some(0 $(+aligned_size(sp_std::mem::size_of::<$ident>()))+) } else { None };
Наверное надо глянуть как в другом коде это реализуют)

2022-08-18 08:34 UTC, merged