Feature/add collection sponsor substrate
UniqueNetwork/unique-chain pull request #535
Opened 2022-08-24 09:32 UTC by bugrazoid

Принимать после https://github.com/UniqueNetwork/unique-chain/pull/469

2022-08-24 10:19 UTC, CertainLach approved these changes
Я не вижу зависимости от ПРа с контрактами, но ок
Этот можно в теории быстрее принять, если оно нужно, т.к с контрактами мне например пока не совсем понятно как новое апи будет дружить с будущими фичами, а в этом всё просто

2022-08-24 10:19 UTC, CertainLach commented on pallets/common/src/erc.rs
> +		let sponsor = match self.collection.sponsorship {
collection.sponsorship.sponsor()

2022-08-24 10:19 UTC, CertainLach commented on pallets/common/src/eth.rs
> +	let mut new_admin_arr: [u8; 32] = Default::default();
let var = [0; 32];

2022-08-25 05:47 UTC, bugrazoid commented
@CertainLach 

> Я не вижу зависимости от ПРа с контрактами, но ок
> Этот можно в теории быстрее принять, если оно нужно, т.к с контрактами мне например пока не совсем понятно как новое апи будет дружить с будущими фичами, а в этом всё просто

Там реализован возврат таплов, тут это тоже используется.

2022-08-25 08:49 UTC, CertainLach requested changes
Ну и выше 2 мелких замечания, после чего я сразу сливаю

2022-08-25 08:49 UTC, CertainLach commented on crates/evm-coder/CHANGELOG.md
> -<!-- bureaucrate goes here -->
Оставь эту строку для бюрократа (github.com/CertainLach/bureaucrate)
Он вставляет новые чейнжлоги сразу после этой строки

2022-08-25 14:07 UTC, CertainLach approved these changes
Новые конфликты с develop сам исправлю при мерже
Я так понял что это уже можно мержить?

2022-08-25 15:04 UTC, merged