Feature/multi assets redone
UniqueNetwork/unique-chain pull request #548
Opened 2022-08-30 12:37 UTC by str-mv

2022-09-02 13:11 UTC, lzadjsf commented
Test

2022-09-07 12:06 UTC, CertainLach commented on pallets/foreign-assets/src/impl_fungibles.rs
> +				let value: u128 = match parent_amount.try_into() {
Меня тут больше вероятное последствие возврата 0 волнует, как и в дальнейших методах

2022-09-07 12:13 UTC, CertainLach commented on pallets/foreign-assets/src/impl_fungibles.rs
> +					&Unlimited,
К слову, а где подсчитывается вес всего этого?

2022-09-07 12:24 UTC, CertainLach commented on pallets/fungible/src/lib.rs
> +	pub type ForeignCollection<T: Config> =
Если флаг для ремарка недостаточно гибок, то можно то однобайтовое bool поле превратить в битфлаги без миграций

2022-09-07 12:26 UTC, CertainLach commented on runtime/common/config/pallets/foreign_asset.rs
> +	type WeightInfo = ();
Не проброшена структура с весом

2022-09-07 12:27 UTC, CertainLach commented on runtime/common/config/xcm/foreignassets.rs
> +	fn convert_ref(id: impl Borrow<MultiLocation>) -> Result<AssetId, ()> {
Это в их трейте такие аргументы стоят?..
Почему не AsRef какой-нибудь?..

2022-09-07 12:29 UTC, CertainLach commented on runtime/common/config/xcm/mod.rs
> +		match transact_inst {
if transact_inst.is_some()

2022-09-07 12:30 UTC, CertainLach commented on runtime/common/construct_runtime/mod.rs
>                  // Vesting: pallet_vesting::{Pallet, Call, Config<T>, Storage, Event<T>} = 37,
Давайте этот комментарий удалим, раз зарезервированные id уже заняли)

2022-09-07 12:33 UTC, CertainLach commented on tests/scripts/readyness.js
> +  await api.disconnect();
По хорошему это в finally надо, т.к getHeader может ошибку пинуть

2022-09-07 12:36 UTC, CertainLach commented on tests/src/substrate/substrate-api.ts
> +          console.log(`Something went wrong with transaction. Status: ${status}\nModule error: ${moduleError}`);
Когда нужно ловить moduleError - лучше сразу переходить на метод executeTransaction, т.к массив эвентов вместо ошибки нам по хорошему никогда не нужен, и вообще submitTransaction стоит выпилить

2022-09-07 12:36 UTC, CertainLach commented on tests/src/util/helpers.ts
> +    return '0.' + numberStr;
Перед numberStr нужно ещё нули вставить

2022-09-07 12:37 UTC, CertainLach commented on tests/src/util/helpers.ts
> +    const siblingPrefix = '0x7369626c';
А что это за магические константы?)

2022-09-07 12:38 UTC, CertainLach commented on tests/src/util/helpers.ts
> +        console.log(`Event \`${eventIdStr}\` is found`);
Такие логи убрать стоит, не?

2022-09-07 12:40 UTC, CertainLach commented on tests/src/util/helpers.ts
> +const keyringEth = new Keyring({type: 'ethereum'});
Перед созданием инстанса Keyring нужно дожидаться загрузки wasm из polkadot-js, иначе в случае иного порядка загрузки модулей можно попасть на сложноотлаживаемую ошибку

2022-09-07 12:44 UTC, CertainLach commented on pallets/foreign-assets/src/weights.rs
> +			.saturating_add(RocksDbWeight::get().writes(1 as Weight))
В мейкфайле используется правильный шаблон

2022-09-07 12:49 UTC, MrShiposha commented on tests/src/substrate/substrate-api.ts
> +          console.log(`Something went wrong with transaction. Status: ${status}\nModule error: ${moduleError}`);
Мб тогда `@deprecated` поставить на `submitTransactionAsync`?

2022-09-07 12:50 UTC, MrShiposha commented on tests/src/util/helpers.ts
> +    return '0.' + numberStr;
Oops :(

2022-09-07 12:52 UTC, MrShiposha commented on tests/src/util/helpers.ts
> +    const siblingPrefix = '0x7369626c';
0x7369626c = b"sibl"

2022-09-07 13:08 UTC, str-mv commented on pallets/foreign-assets/src/impl_fungibles.rs
> +				let value: u128 = match parent_amount.try_into() {
Это не одинаковые BalanceOf . А как будет лучше?
Последствие возврата zero? Выведет в лог событие что total_issuance = 0 и так далее

2022-09-07 13:10 UTC, str-mv commented on pallets/foreign-assets/src/impl_fungibles.rs
> +					Ok(_) => Ok(amount),
т.к. другой тип, не хочется конвертировать. Если burn завершился без ошибок значит сожжено то самое количество, разве нет?

2022-09-07 13:47 UTC, MrShiposha commented on runtime/common/config/orml.rs
> +pub type Amount = i128;
```rust
impl orml_tokens::Config for Runtime {
	type Event = Event;
	type Balance = Balance;
	type Amount = Amount;
...
```

2022-09-07 13:50 UTC, MrShiposha commented on runtime/common/config/xcm/foreignassets.rs
> +	fn convert_ref(id: impl Borrow<MultiLocation>) -> Result<AssetId, ()> {
Да, это из Paity пришло: https://github.com/paritytech/polkadot/blob/575628502fd06ef162d36e707f183f3de3d5405a/xcm/xcm-executor/src/traits/conversion.rs#L35-L37

2022-09-07 13:58 UTC, MrShiposha commented on tests/src/util/helpers.ts
> +const keyringEth = new Keyring({type: 'ethereum'});
Done

2022-09-07 13:58 UTC, MrShiposha commented on tests/src/util/helpers.ts
> +        console.log(`Event \`${eventIdStr}\` is found`);
Done

2022-09-07 13:58 UTC, MrShiposha commented on tests/src/util/helpers.ts
> +    const siblingPrefix = '0x7369626c';
Добавил объясняющий коммент

2022-09-07 13:58 UTC, MrShiposha commented on tests/src/util/helpers.ts
> +    return '0.' + numberStr;
Done

2022-09-07 13:58 UTC, MrShiposha commented on tests/scripts/readyness.js
> +  await api.disconnect();
Done

2022-09-07 13:58 UTC, MrShiposha commented on runtime/common/construct_runtime/mod.rs
>                  // Vesting: pallet_vesting::{Pallet, Call, Config<T>, Storage, Event<T>} = 37,
Done

2022-09-07 13:58 UTC, MrShiposha commented on runtime/common/config/xcm/mod.rs
> +		match transact_inst {
Done

2022-09-07 13:59 UTC, MrShiposha commented on pallets/foreign-assets/src/lib.rs
> +		WeightToFee: WeightToFeePolynomial<Balance = Currency::Balance>,
Исправил

2022-09-07 13:59 UTC, MrShiposha commented on pallets/foreign-assets/src/lib.rs
> +		#[transactional]
Done

2022-09-07 13:59 UTC, MrShiposha commented on pallets/foreign-assets/src/impl_fungibles.rs
> +		match asset {
Done

2022-09-07 14:16 UTC, CertainLach commented on runtime/common/config/orml.rs
> +pub type Amount = i128;
Ой, да

2022-09-07 14:16 UTC, CertainLach commented on runtime/common/config/xcm/foreignassets.rs
> +	fn convert_ref(id: impl Borrow<MultiLocation>) -> Result<AssetId, ()> {
Очень странное описание, но ладно тогда)

2022-09-07 14:17 UTC, CertainLach commented on tests/src/substrate/substrate-api.ts
> +          console.log(`Something went wrong with transaction. Status: ${status}\nModule error: ${moduleError}`);
Да, надо бы

2022-09-07 14:24 UTC, MrShiposha commented on pallets/fungible/src/lib.rs
> +	pub fn create_multiple_items_foreign(
Немного отличается запись, как я вижу. Не уверен какой из вариантов верный -- в одном случае логируется значение до обновления (`amount`), а в другом случае логируется новое (в этом случае `amount == updated_balance`).

Нужен комментарий @str-mv

2022-09-07 15:15 UTC, CertainLach commented on pallets/foreign-assets/src/impl_fungibles.rs
> +				let value: u128 = match parent_amount.try_into() {
В случае с NativeAssetId и pallet_balances - это должны быть одинаковые BalanceOf)

А в случае с реле - в рантайме они тоже отличаются, не выйдет повесить баунд

```rust
trait Config
where RelayBalanceOf<Self>: From<BalanceOf<Self>>
```
?

2022-09-07 15:16 UTC, str-mv commented on pallets/fungible/src/lib.rs
> +	pub fn create_multiple_items_foreign(
create_multiple_items - здесь код после исправления бага с неправильным событием
Ок. Думаю, не смотря что это костыль нужно вынести общую логику.

2022-09-07 15:18 UTC, CertainLach commented on pallets/foreign-assets/src/impl_fungibles.rs
> +					WithdrawConsequence::NoFunds => WithdrawConsequence::NoFunds,
```rust
use WithdrawConsequence::*;
match ... {
    cons @ (NoFunds | WouldDie | UnknownAsset | ...) => cons,
    _ => NoFunds,
}
```

2022-09-07 15:19 UTC, CertainLach commented on pallets/foreign-assets/src/impl_fungibles.rs
> +					Ok(_) => Ok(amount),
Ну судя по коду pallet_balances может убрать меньше чем ему передали
https://github.com/paritytech/substrate/blob/master/frame/balances/src/lib.rs#L1113-L1133

2022-09-08 09:34 UTC, MrShiposha commented on pallets/foreign-assets/src/impl_fungibles.rs
> +					WithdrawConsequence::NoFunds => WithdrawConsequence::NoFunds,
К сожалению, `WithdrawConsequence`  -- обобщенный. Он несет тип `Balance`, компилятор не понимает, что в итоге это один и тот же тип, он лишь видит, что мы берем ассоциированный тип из соот-ей паллеты. Поэтому так не получается, и никакого `impl From` для `WithdrawConsequence` тоже нет.

2022-09-08 11:39 UTC, CertainLach commented on pallets/foreign-assets/src/impl_fungibles.rs
> +					WithdrawConsequence::NoFunds => WithdrawConsequence::NoFunds,
Можно повесить баунд
Balance1: From<Balance2>

Он будет работать, т.к есть импла
From<T> for T

2022-09-14 07:48 UTC, str-mv commented on pallets/foreign-assets/src/impl_fungibles.rs
> +				let value: u128 = match parent_amount.try_into() {
Готово

2022-09-14 07:48 UTC, str-mv commented on pallets/foreign-assets/src/impl_fungibles.rs
> +					Ok(_) => Ok(amount),
Готово

2022-09-14 07:50 UTC, str-mv commented on pallets/foreign-assets/src/impl_fungibles.rs
> +					&Unlimited,
Это выполняется внутри xcm. Вес в таких случаях не считается отдельно

2022-09-14 07:51 UTC, str-mv commented on pallets/foreign-assets/src/impl_fungibles.rs
> +					&Unlimited,
По Unlimited. Не знаком, что там нужно написать?

2022-09-14 07:53 UTC, str-mv commented on pallets/foreign-assets/src/weights.rs
> +			.saturating_add(RocksDbWeight::get().writes(1 as Weight))
Готово

2022-09-14 07:54 UTC, str-mv commented on pallets/fungible/src/lib.rs
> +	pub type ForeignCollection<T: Config> =
Мы обсуждали это несколько дней на дейлике. Переиспользовать нельзя. Это не со мной нужно обсуждать.

2022-09-14 07:54 UTC, str-mv commented on runtime/common/config/pallets/foreign_asset.rs
> +	type WeightInfo = ();
Готово

2022-09-14 08:13 UTC, CertainLach commented on pallets/foreign-assets/src/impl_fungibles.rs
> +					&Unlimited,
Есть budget::Value
https://github.com/UniqueNetwork/unique-chain/blob/master/primitives/data-structs/src/budget.rs#L21

Экстринзики текущие у нас по дефолту имеют лимит 4, т.е `budget::Value::new(4)`

2022-09-14 08:17 UTC, CertainLach requested changes

2022-09-14 08:17 UTC, CertainLach commented on pallets/foreign-assets/src/impl_fungibles.rs
> +type BalanceRelay<T> =
А чем это отличается от BalanceOf?

2022-09-14 08:18 UTC, CertainLach commented on pallets/foreign-assets/src/weights.rs
> +			.saturating_add(RocksDbWeight::get().writes(1 as Weight))
Перезапусти бенчмарки в таком случае, чтобы этот файл с новым шаблоном создало

2022-09-14 08:34 UTC, str-mv commented on pallets/foreign-assets/src/impl_fungibles.rs
> +type BalanceRelay<T> =
Готово

2022-09-19 12:58 UTC, merged