evm-coder: conditional interface inheritance
UniqueNetwork/unique-chain pull request #569
Opened 2022-09-08 08:12 UTC by CertainLach

Add new configuration option for #[solidity_interface] is attribute: if($expr)

This expression will be executed during ERC165 supports_interface call, and during normal call execution (but not during parsing), allowing to conditionally disable some inherited interfaces based on contract data

2022-09-08 08:34 UTC, CertainLach commented
Пример использования:
https://github.com/UniqueNetwork/unique-chain/pull/569/files#diff-aa303ea9af2d20791c5258dbe8e9cd1df1b65cba78f14de2bc4d0db3f8ef8a85

2022-09-08 08:50 UTC, CertainLach commented
У нас нет в коде документации для `via` и `if` в `is`, и я не уверен как это оформить, т.к синтаксис нетривиальный, как и семантика)

2022-09-12 10:08 UTC, MrShiposha requested changes

2022-09-12 10:08 UTC, MrShiposha commented on pallets/fungible/src/erc.rs
> +		Collection(via(common_mut, CollectionHandle<T>)),
Мб устроить такой синтаксис?

```rust
Collection(via(CollectionHandle<T>::common_mut))
```

Просто из этого контекста непонятно, что common_mut -- это функция из CollectionHandle.

2022-09-12 10:08 UTC, MrShiposha commented on crates/evm-coder/procedural/src/solidity_interface.rs
> +				pub fn supports_interface(this: &#name, interface_id: ::evm_coder::types::bytes4) -> bool {
А зачем тут `this`? Вроде он тут не используется

2022-09-12 10:08 UTC, MrShiposha commented on crates/evm-coder/procedural/src/solidity_interface.rs
> +				if ({let this = &self; (#condition)})
Почему бы не оставить просто `self`?

2022-09-12 10:45 UTC, CertainLach commented on pallets/fungible/src/erc.rs
> +		Collection(via(common_mut, CollectionHandle<T>)),
Не, тут наоборот, первый аргумент - вызываемая функция, а второй - возвращаемый тип, т.к внутри тайп инференс не работает

2022-09-12 10:46 UTC, CertainLach commented on pallets/fungible/src/erc.rs
> +		Collection(via(common_mut, CollectionHandle<T>)),
Я хотел common_mut() -> CollectionHandle<T>, но это плохо, т.к аргументы оно принимать не умеет, да и вообще это метод на self, и синтаксис странный выходит

2022-09-12 10:47 UTC, CertainLach commented on crates/evm-coder/procedural/src/solidity_interface.rs
> +				pub fn supports_interface(this: &#name, interface_id: ::evm_coder::types::bytes4) -> bool {
Он может использоваться в if:

is(Iface(if(this.enabled)))

См пример

2022-09-12 10:47 UTC, CertainLach commented on crates/evm-coder/procedural/src/solidity_interface.rs
> +				if ({let this = &self; (#condition)})
Потому что в supports_interface у нас this

2022-09-12 10:50 UTC, CertainLach commented on crates/evm-coder/procedural/src/solidity_interface.rs
> +				loop {
Мне хотелось обработку trailing comma иметь там же где и обработку конца, но видимо да, тут лучше так

2022-09-12 10:51 UTC, MrShiposha commented on pallets/fungible/src/erc.rs
> +		Collection(via(common_mut, CollectionHandle<T>)),
Ага, да, действительно. Я не так понял.

Мб тогда можно `via(common_mut returns CollectionHandle<T>)`?
Просто правда смотря только на этот код сложно понять что тут имеется в виду.

2022-09-12 10:51 UTC, CertainLach commented on crates/evm-coder/procedural/src/solidity_interface.rs
> +				if ({let this = &self; (#condition)})
Ну и this в self не переименовать)

2022-09-12 10:53 UTC, CertainLach commented on pallets/fungible/src/erc.rs
> +		Collection(via(common_mut, CollectionHandle<T>)),
Можно так, да

2022-09-12 10:56 UTC, MrShiposha commented on crates/evm-coder/procedural/src/solidity_interface.rs
> +				pub fn supports_interface(this: &#name, interface_id: ::evm_coder::types::bytes4) -> bool {
Ага, сложилось

2022-09-19 13:49 UTC, MrShiposha approved these changes

2022-09-19 14:44 UTC, merged