Add description of the sponsoring flow
UniqueNetwork/unique-chain pull request #572
Opened 2022-09-08 11:02 UTC by CertainLach

2022-09-08 13:08 UTC, MrShiposha requested changes

2022-09-08 13:08 UTC, MrShiposha commented on doc/sponsoring.md
> +For both examples, you can take a look at `UniqueSponsorshipHandler` struct inside of common runtime
> For both examples
`UniqueSponsorshipHandler` реализует только первый вариант. Второй вариант можно подсмотреть в `UniqueEthSponsorshipHandler`

2022-09-08 13:10 UTC, CertainLach commented on doc/sponsoring.md
> +# Sponsoring
Все прочие обработчики я показываю как EVM calls/Extrinsics, отдельно я выделяю лишь BridgeSponsorshipHandler, т.к он является мостом

2022-09-13 09:46 UTC, MrShiposha approved these changes

2022-09-13 10:19 UTC, CertainLach commented
А, так я переименовал это уже)

2022-09-13 10:19 UTC, merged