Feature/eth passthrought
UniqueNetwork/unique-chain pull request #574
Opened 2022-09-09 05:42 UTC by bugrazoid

2022-09-11 21:07 UTC, CertainLach requested changes

2022-09-11 21:07 UTC, CertainLach commented on pallets/common/src/erc.rs
> +		self.consume_store_reads_and_writes(1, 1)?;
Такое я предлагал в случае с тривиальными методами, для которых при этом нет бенчмарков

На этот метод есть бенчмарк, поэтому тут лучше использовать его результат

2022-09-12 08:42 UTC, bugrazoid commented on pallets/common/src/erc.rs
> +		self.consume_store_reads_and_writes(1, 1)?;
Бэнчмарк есть на set_collection_propert**ies** а тут set_collection_propert**y**.

2022-09-12 08:48 UTC, CertainLach commented on pallets/common/src/erc.rs
> +		self.consume_store_reads_and_writes(1, 1)?;
Так _ies бенчмарк покрывает этот юзкейс, для назначения одного property ему единицу можно передать

2022-09-12 22:48 UTC, CertainLach requested changes

2022-09-12 22:48 UTC, CertainLach commented on pallets/common/src/erc.rs
> +	#[weight(<SelfWeightOf<T>>::set_collection_properties(1_u32))]
Разве без _u32 оно не работает?

Энивей, CI жалуется на форматирование

2022-09-14 07:10 UTC, CertainLach approved these changes

2022-09-14 07:10 UTC, merged