added `doc` to app promotion
UniqueNetwork/unique-chain pull request #579
Opened 2022-09-12 13:35 UTC by PraetorP

2022-09-12 22:46 UTC, CertainLach requested changes

2022-09-12 22:46 UTC, CertainLach commented on pallets/app-promotion/src/lib.rs
> +			// cheks that we can lock `amount` on the `staker` account.
typo

2022-09-12 22:46 UTC, CertainLach commented on pallets/app-promotion/src/lib.rs
> +			// in which it is necessary to accrue remuneration for the stake.
typos

2022-09-12 22:46 UTC, CertainLach commented on pallets/app-promotion/src/lib.rs
> +		/// * `contract_id`: ID of the contract that is sponsored by `pallet_id`
В эфире это называют адресом

2022-09-12 22:46 UTC, CertainLach commented on pallets/app-promotion/src/lib.rs
> +				// this closure is uded to perform some of the actions if we break the loop because we reached the number of stakers for recalculation,
typo

2022-09-12 22:46 UTC, CertainLach commented on pallets/app-promotion/src/lib.rs
> +	/// - `staker`: staker ID.
Мне кажется в доках для субстрата тоже терминологию стоит чуть другую
Вместо ID использовать account например

У меня id тут создаёт ощущение что у нас есть какой-то ещё маппинг из id в аккаунт)

2022-09-12 22:46 UTC, CertainLach commented on pallets/app-promotion/src/lib.rs
> +	/// **Note**: This `fn` has been added to implement RPC
Зачем такие заметки?
Это же просто геттер, его не обязательно RPC вызывать

Если же метод дорогой - то имхо стоит это прямо написать, что его не стоит из блока вызывать

2022-09-12 22:46 UTC, CertainLach commented on pallets/evm-contract-helpers/src/lib.rs
> +		/// it doesn't require consent from the `owner` of the contract.
Как-то забыл об этом:
<PalletEvm<T>>::deposit_log

Создаёт на стороне субстрата события evm.Log, стоит тут использовать метод log_mirrored, т.к для субстрата было добавлено новое событие

Не критично, просто красивее логи

2022-09-13 06:00 UTC, PraetorP commented on pallets/app-promotion/src/lib.rs
> +			// in which it is necessary to accrue remuneration for the stake.
accrue 
remuneration?

2022-09-13 06:15 UTC, PraetorP commented on pallets/app-promotion/src/lib.rs
> +	/// - `staker`: staker ID.
В целом согласен :) Однако , если посмотреть под другим адрес нечто иное как очень большое число (u256)  :) ,

2022-09-13 06:27 UTC, ut-akuznetsov commented on pallets/app-promotion/src/lib.rs
> +	/// - `staker`: staker ID.
Исправь лучше на account или accountId, это действительно понятнее в терминологии

2022-09-13 07:27 UTC, PraetorP commented on pallets/app-promotion/src/lib.rs
> +	/// - `staker`: staker ID.
Уже исправил на аккаунт

2022-09-13 09:26 UTC, gregzaitsev approved these changes

2022-09-13 09:38 UTC, CertainLach commented on pallets/app-promotion/src/lib.rs
>  	///
Пустые строки бы убрать ещё

2022-09-13 09:39 UTC, CertainLach commented on pallets/app-promotion/src/lib.rs
>  	/// **Note**: This `fn` has been added to implement RPC
Комментарии про RPC я имел в виду все

2022-09-13 09:46 UTC, CertainLach approved these changes

2022-09-13 09:46 UTC, merged