Test/app promotion refactor
UniqueNetwork/unique-chain pull request #592
Opened 2022-09-15 08:10 UTC by Maksandre

2022-09-15 08:24 UTC, ut-akuznetsov requested changes

2022-09-15 08:24 UTC, ut-akuznetsov commented on tests/src/eth/util/playgrounds/unique.dev.ts
> +    contract Flipper {
```
// SPDX-License-Identifier: UNLICENSED
    pragma solidity ^0.8.6;
```

Add this before code

2022-09-15 08:24 UTC, ut-akuznetsov commented on tests/src/app-promotion.test.ts
> +    expect((await helper.api!.query.evmContractHelpers.sponsoring(flipper.options.address)).toJSON()).to.deep.equal({
`(await helper.callRpc('api.query.evmContractHelpers.sponsoring', [flipper.options.address])).toJSON()`

2022-09-15 08:24 UTC, ut-akuznetsov commented on tests/src/app-promotion.test.ts
> +    await expect(helper.signTransaction(palletAdmin, helper.api!.tx.appPromotion.stopSponsoringCollection(999999999))).to.be.rejected;
`helper.executeExtrinsic(palletAdmin, 'api.tx.appPromotion.stopSponsoringCollection', [999_999_999])`

2022-09-15 09:05 UTC, ut-akuznetsov approved these changes

2022-09-16 12:49 UTC, CertainLach commented on .docker/docker-compose.tmp-dev.j2
> +    command: cargo run --release --features={{ FEATURE }} -- --dev -linfo --unsafe-ws-external --rpc-cors=all --unsafe-rpc-external
Если фича есть в environment - то тут можно и через $FEATURE её использовать

2022-09-16 13:14 UTC, lzadjsf commented on .docker/docker-compose.tmp-dev.j2
> +    command: cargo run --release --features={{ FEATURE }} -- --dev -linfo --unsafe-ws-external --rpc-cors=all --unsafe-rpc-external
не срабатывает так. так было сделано.

2022-09-16 13:15 UTC, lzadjsf commented on .docker/docker-compose.tmp-dev.j2
> +    command: cargo run --release --features={{ FEATURE }} -- --dev -linfo --unsafe-ws-external --rpc-cors=all --unsafe-rpc-external
сейчас уберу из environment. чтобы не смущало.

2022-09-16 13:42 UTC, lzadjsf commented on .docker/docker-compose.tmp-dev.j2
> +    command: cargo run --release --features={{ FEATURE }} -- --dev -linfo --unsafe-ws-external --rpc-cors=all --unsafe-rpc-external
убрал environment.
таким образом у нас command после генерации имеет конечный вид:
 command: cargo run --release --features=имя_сети-runtime -- --dev -linfo --unsafe-ws-external --rpc-cors=all --unsafe-rpc-external

2022-09-16 13:58 UTC, merged