Tests: thorough event logging + a few more tests refactored
UniqueNetwork/unique-chain pull request #601
Opened 2022-09-19 14:13 UTC by Fahrrader

2022-09-19 14:31 UTC, ut-akuznetsov requested changes

2022-09-19 14:31 UTC, ut-akuznetsov commented on tests/src/util/playgrounds/unique.ts
> +    if (data.entries)
А мы можем так не делать? Стремно без скобочек

2022-09-19 14:31 UTC, ut-akuznetsov commented on tests/src/util/playgrounds/unique.ts
> +  async executeExtrinsic(sender: TSigner, extrinsic: string, params: any[], expectSuccess=true/*, failureMessage='expected success'*/) {
Давай сюда добавим проброс аргументов к signTransaction еще, чтобы два раза не вставать. Чтобы тот же nonce можно было передать как helper.executeExtrinsic(alice, 'api.balances.transfer', [bob.address, 1_000n], true, {none: 25})

2022-09-19 14:31 UTC, ut-akuznetsov commented on tests/src/util/playgrounds/types.ts
> +        phase: any, // {ApplyExtrinsic: number} | 'Initialization',
Вот тут вот я не совсем понял. У нас и event содержи phase и тут то же самое? И не совсем понимаю где по коду это получается, вроде везде речь про IEvent, не могу найти место где дополнительно прописывается phase

2022-09-19 17:24 UTC, Fahrrader commented on tests/src/util/playgrounds/types.ts
> +        phase: any, // {ApplyExtrinsic: number} | 'Initialization',
phase передаётся в обёртке эвента (который у нас IEvent) в signAndSend, поэтому, чтобы логировать его тоже, я даю его внутреннему IEvent тоже

2022-09-20 07:45 UTC, ut-akuznetsov approved these changes

2022-09-20 10:41 UTC, merged