Tests: Refactored Nesting and Properties to use playgrounds
UniqueNetwork/unique-chain pull request #607
Opened 2022-09-22 15:03 UTC by Fahrrader

2022-09-23 01:24 UTC, ut-akuznetsov requested changes

2022-09-23 01:24 UTC, ut-akuznetsov commented on tests/src/util/playgrounds/unique.ts
> +  static getNestingTokenAddressRaw(token: IToken) {
Я бы сделал в обратную сторону tokenAddressObj: {Ethereum: string} и tokenAddress: string

2022-09-23 01:24 UTC, ut-akuznetsov commented on tests/src/util/playgrounds/unique.ts
> +export class UniqueNFTCollection extends UniqueCollectionBase {
А зачем мы эти классы экспортируем? Изначально они намеренно скрытые были

2022-09-23 01:24 UTC, ut-akuznetsov commented on tests/src/util/playgrounds/types.ts
> +    mutable?: boolean;
Это мне видится тоже не очень здорово, т.к. в тестах лучше писать полную запись для наглядности.
Я понимаю что тут видимо нужно для поведения какого-либо теста на умолчательные false, но может лучше там на месте ts обмануть?

2022-09-23 01:24 UTC, ut-akuznetsov commented on tests/src/util/playgrounds/types.ts
> +  //nestingAddress: () => {Ethereum: string};
Артефакт?

2022-09-23 08:08 UTC, Fahrrader commented on tests/src/util/playgrounds/unique.ts
> +export class UniqueNFTCollection extends UniqueCollectionBase {
Это хорошо для внешних функций, чтобы прокидывать токены или коллекции и работать с ними вместо возни с helper'ами и id'шниками. Обилие повторяющих одно какое-то тело тестов только этому способствует. А есть другой путь?)

2022-09-23 08:17 UTC, ut-akuznetsov commented on tests/src/util/playgrounds/unique.ts
> +export class UniqueNFTCollection extends UniqueCollectionBase {
Так они же все-равно инициализируются хелпером и без него не работают.
helper.(nft|rft|ft).(getCollectionOobject|getTokenObject) их возвращает инициализованными уже

2022-09-23 08:37 UTC, Fahrrader commented on tests/src/util/playgrounds/unique.ts
> +export class UniqueNFTCollection extends UniqueCollectionBase {
Ну да, но

2022-09-23 08:41 UTC, Fahrrader commented on tests/src/util/playgrounds/unique.ts
> +export class UniqueNFTCollection extends UniqueCollectionBase {
Ну да, но

> const collection = await helper.nft.mintCollection(alice)
> await doStuff(collection);
> await doSomethingElse(collection);
> ...
> async function doStuff(collection: UniqueNFTCollection | UniqueRFTCollection) {
> ...
> }

всё равно легче писать, чем

> const collection = await helper.nft.mintCollection(alice);
> await doStuff(helper, collection.collectionId, 'NFT');
> await doSomethingElse(helper, collection.collectionId, 'NFT');

2022-09-23 08:45 UTC, Fahrrader commented on tests/src/util/playgrounds/types.ts
> +    mutable?: boolean;
Не совсем, тут это точно так же, как и для каких-нибудь ICollectionLimits или INestingPermissions - в большинстве тестов не разрешения не переиначиваются, и там лишни повсеместные явные `false`

2022-09-23 15:58 UTC, ut-akuznetsov requested changes

2022-09-23 15:58 UTC, ut-akuznetsov commented on tests/src/util/playgrounds/unique.ts
> +    return {Ethereum: this.getTokenAddress(token).toLowerCase()};
А зачем тут toLowerCase? По-идее это излишне, тем более там до этого специально нормализуется к чексумме

2022-09-23 15:59 UTC, ut-akuznetsov commented on tests/src/util/playgrounds/unique.ts
> +export class UniqueNFTCollection extends UniqueCollectionBase {
Хм, только для типов... Может тогда лучше вывести у них какого-нибудь предка общего, причем в types.ts, а не в самом unique.ts и его для этих целей использовать?

2022-09-26 07:50 UTC, Maksandre approved these changes

2022-09-27 08:01 UTC, ut-akuznetsov requested changes

2022-09-27 08:01 UTC, ut-akuznetsov commented on tests/src/util/playgrounds/types.ts
> +export interface ICollectionBase {
Ох, ну с такой детализацией это мы точно погрязнем в изменениях. Я думал просто тип, общий, без указания методов. Давай тогда уж лучше вернем export.

2022-09-27 08:01 UTC, Fahrrader commented on tests/src/util/playgrounds/unique.ts
> +    return {Ethereum: this.getTokenAddress(token).toLowerCase()};
Эфирные адреса при скармливании в вызов минта переводятся в нижний регистр, то есть, хранятся на чейне уже так

2022-09-27 08:03 UTC, Fahrrader commented on tests/src/util/playgrounds/unique.ts
> +export class UniqueNFTCollection extends UniqueCollectionBase {
Как много тавтологии там теперь)

2022-09-27 08:04 UTC, ut-akuznetsov commented on tests/src/util/playgrounds/unique.ts
> +    return {Ethereum: this.getTokenAddress(token).toLowerCase()};
Однако в библиотечных целях нам лучше иметь именно приведенный к чексумме вариант, чтобы можно было метамаском переводить

2022-09-27 08:06 UTC, ut-akuznetsov commented on tests/src/util/playgrounds/unique.ts
> +export class UniqueNFTCollection extends UniqueCollectionBase {
Да, такой вариант еще хуже. Возвращай export тогда

2022-09-27 08:59 UTC, ut-akuznetsov approved these changes

2022-09-27 08:59 UTC, merged