Feature: make create collection methods payable
UniqueNetwork/unique-chain pull request #608
Opened 2022-09-23 11:28 UTC by fairax

2022-09-23 11:38 UTC, CertainLach commented on crates/evm-coder/procedural/src/solidity_interface.rs
> +		for arg in args.iter() {
Старый код мне тут больше нравился)
is_payable лучше сделай через `args.iter().any(|a| a.is_value)`

2022-09-23 11:40 UTC, CertainLach commented on pallets/unique/src/eth/mod.rs
> +			.map_err(|_| "collection creation price should be convertible to u128".into());
Вопросительный знак лучше сюда перенести, + можно не делать map_err, а просто `.expect("price is convertible")`, т.к это ошибка конфигурации палеты, а не юзера

2022-09-23 11:41 UTC, CertainLach commented on tests/src/eth/payable.test.ts
> +      contract Flipper {
Не понял зачем тут это)

2022-09-23 11:42 UTC, CertainLach requested changes
Нужен эфирный метод для получения цены создания коллекции

2022-09-23 11:44 UTC, fairax commented on pallets/unique/src/eth/mod.rs
> +			.map_err(|_| "collection creation price should be convertible to u128".into());
ок, просто там компилятор ругался и недавал expect сделать, поэтому я пока такой вариант сделал

2022-09-28 13:32 UTC, bugrazoid approved these changes

2022-09-30 15:16 UTC, merged