build: upgrade to polkadot-v0.9.29
UniqueNetwork/unique-chain pull request #614
Opened 2022-09-28 15:57 UTC by mrshiposha

2022-09-29 03:18 UTC, CertainLach commented on crates/evm-coder/Cargo.toml
> +frame-support = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.29" }
evm-coder должен быть абстрактным, без привязки к субстрату, но в данном случае я не уверен что делать в weight

Я пробрасывал это в ассоциированный тип, однако хардкодил его в субстратовый из макроса

2022-09-29 11:25 UTC, mrshiposha commented on crates/evm-coder/Cargo.toml
> +frame-support = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.29" }
Можем оставить там Weight = u64, И использовать только `ref_time` в кодере пока что.

2022-10-03 08:58 UTC, CertainLach requested changes
Вижу обновление результатов бенчмарков, но не вижу обновления их шаблона из .maintain

Попробуй также их перепрогнать, мне кажется что они могли сломаться
Результат перепрогона не коммить, перепрогон только для проверки работоспособности

2022-10-03 08:58 UTC, CertainLach commented on crates/evm-coder/procedural/src/solidity_interface.rs
> +						Self::ERC165Call(::evm_coder::ERC165Call::SupportsInterface {..}, _) => frame_support::weights::Weight::from_ref_time(100).into(),
В генерируемом коде ссылаться на другие крейты лучше через module namespace, т.е через `::frame_support`
В данном случае вероятность коллизии мала, однако для консистентности лучше так.

2022-10-03 08:58 UTC, CertainLach commented on node/cli/Cargo.toml
> +fc-rpc-core = { git = "https://github.com/uniquenetwork/frontier", branch = "unique-polkadot-v0.9.29-fee-limit" }
Суффиксы у версий держим только для одной версии, это у нас именованный аналог ver-1, ver-2

2022-10-03 14:10 UTC, CertainLach commented on crates/evm-coder/Cargo.toml
> +frame-support = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.29" }
Пока пусть остаётся так, пофиксили когда будем выносить из нашей репы.

2022-10-03 14:10 UTC, CertainLach approved these changes

2022-10-04 07:59 UTC, merged