added `destroyCollection`method  to `CollectionHelpers`
UniqueNetwork/unique-chain pull request #644
Opened 2022-10-10 12:44 UTC by PraetorP

2022-10-10 12:47 UTC, PraetorP commented on pallets/unique/src/eth/mod.rs
> +	#[weight(<SelfWeightOf<T>>::destroy_collection())]
@CertainLach, что скажешь , чтобы не дубилровать код вынести это в отдельный метод в lib.rs , и уже его использовать при вызjве как из субстрата , так и EVM? Пока оставил как есть , чтобы не трогать код в lib.rs

2022-10-10 13:11 UTC, CertainLach commented on pallets/unique/src/eth/mod.rs
> +	#[weight(<SelfWeightOf<T>>::destroy_collection())]
А как тут вынесение поможет?

2022-10-10 13:28 UTC, PraetorP commented on pallets/unique/src/eth/mod.rs
> +	#[weight(<SelfWeightOf<T>>::destroy_collection())]
@CertainLach ,я больше про переиспользование кода + если изменится логика удаления коллекции , код надо будет менять только в одном месте а не как сейчас (для субстрата в lib.rs и для эфира в одноименном методе). 
Сейчас у нас по фатку один и тот же код в двух разных местах.

2022-10-12 08:22 UTC, CertainLach commented on pallets/unique/src/eth/mod.rs
> +	#[weight(<SelfWeightOf<T>>::destroy_collection())]
Речь шла о теле метода, а не весе
В этом случае одобряю

2022-10-12 10:32 UTC, PraetorP commented on pallets/unique/src/eth/mod.rs
> +	#[weight(<SelfWeightOf<T>>::destroy_collection())]
@CertainLach , извини! Я не совсем верно сделал , что решил прокомментировать именно эту строку, чем ввел тебя изначально в заблуждение.

2022-10-17 08:43 UTC, CertainLach requested changes

2022-10-17 08:43 UTC, CertainLach commented on pallets/unique/src/eth/mod.rs
> +	#[solidity(rename_selector = "destroyCollection")]
А зачем ренейм? По дефолту идёт преобразование из snake_case в camelCase, и в данном случае неоднозначностей нет

2022-10-17 08:43 UTC, CertainLach commented on pallets/unique/src/eth/mod.rs
> +			.map_err(pallet_evm_coder_substrate::dispatch_to_evm::<T>)?;
Строковые ошибки изначально конвертируются в Evm
```
.ok_or("msg")?
```

2022-10-17 09:28 UTC, merged