Feature: supports interface for erc721 metadata
UniqueNetwork/unique-chain pull request #647
Opened 2022-10-12 15:45 UTC by fairax

2022-10-12 15:58 UTC, ut-akuznetsov commented on tests/src/util/playgrounds/unique.ts
> +    collectionOptions.properties = collectionOptions.properties || [{key: 'ERC721Metadata', value: '1'}];
Вот этого лучше не делать, для субстрата по-умолчанию этого ключа добавляться не должно в нашей библиотеке (playgrounds)

2022-10-12 15:59 UTC, ut-akuznetsov commented on tests/src/util/playgrounds/unique.ts
> +    collectionOptions.properties = collectionOptions.properties || [{key: 'ERC721Metadata', value: '1'}];
Лучше его явно проставлять в тех тестах, где это требуется

2022-10-12 16:42 UTC, CertainLach requested changes

2022-10-12 16:42 UTC, CertainLach commented on pallets/refungible/src/erc.rs
> -		ERC721Metadata,
Поставь этот интерфейс последним ещё, чтобы чтения пропертей не трогали другие проверки
В идеале потом нужно добавить возможность вес за такое увеличивать

2022-10-12 16:42 UTC, CertainLach commented on pallets/refungible/src/lib.rs
> +impl<T: Config> RefungibleHandle<T> {
Убери в erc.rs, т.к это эфир-специфичный код

2022-10-12 17:57 UTC, fend25 commented on pallets/refungible/src/erc.rs
> -		ERC721Metadata,
насчет веса - точно надо?

2022-10-12 17:57 UTC, fend25 commented on pallets/unique/src/eth/mod.rs
> +				key: key::url(),
оно не конфликтует со 105 строкой? и похоже что правильный вариант тут

2022-10-12 17:57 UTC, fend25 commented on tests/src/deprecated-helpers/helpers.ts
> +  properties: [{key: 'ERC721Metadata', value: '1'}],
извините, а оно тут нужно? я не очень понимаю, но похоже что это про вообще любую NFT коллекцию, нет?

2022-10-12 18:09 UTC, fairax commented on pallets/unique/src/eth/mod.rs
> +				key: key::url(),
судя по тестам не конфликтует, но это косяк да

2022-10-12 19:02 UTC, CertainLach commented on pallets/refungible/src/erc.rs
> -		ERC721Metadata,
Чтения хранилища едят вес, а тут мы это потребление игнорируем

2022-10-13 07:32 UTC, CertainLach commented on pallets/nonfungible/src/erc.rs
> +		if !self.supports_metadata() {
Нет смысла проверять, этот интерфейс нельзя вызвать, т.к он перекрыт через if()

2022-10-13 10:25 UTC, CertainLach approved these changes

2022-10-18 14:54 UTC, merged