Eth named structures
UniqueNetwork/unique-chain pull request #670
Opened 2022-10-19 14:04 UTC by bugrazoid

2022-10-19 21:43 UTC, CertainLach requested changes

2022-10-19 21:43 UTC, CertainLach commented on tests/src/eth/api/UniqueNFT.sol
> +	/// @dev EVM selector for this function is: 0xa8106d4a,
Почему изменился?

2022-10-19 21:43 UTC, CertainLach commented on crates/evm-coder/src/abi.rs
> +impl AbiRead<EthCrossAccount> for AbiReader<'_> {
Теперь нет футгана с использованием stringify! типа, и можно сделать impl AbiRead for Struct

2022-10-19 21:43 UTC, CertainLach commented on crates/evm-coder/procedural/src/solidity_interface.rs
>  	fn expand_const(&self) -> proc_macro2::TokenStream {
Старую логику вычисления селекторов нужно выпилить

2022-10-19 21:44 UTC, CertainLach commented on crates/evm-coder/src/abi.rs
> +impl AbiRead<EthCrossAccount> for AbiReader<'_> {
Ну и вынести эту структуру из evm-coder

2022-10-27 11:01 UTC, CertainLach requested changes

2022-10-27 11:01 UTC, CertainLach commented on crates/evm-coder/src/custom_signature.rs
> +	// This test must NOT compile with "index out of bounds"!
Было бы неплохо для подобных тестов подключить к нам
https://docs.rs/trybuild/latest/trybuild/

Потому как у нас в evm-coder есть много проверок, валящих компиляцию, на которые у нас нет тестов

2022-10-27 11:03 UTC, CertainLach commented on crates/evm-coder/procedural/src/solidity_interface.rs
> +			AbiType::Array(_, _) => todo!("Array eth signature"),
Возможно реализовать через
```
impl<T, const S: usize> Signature for [T; S]
```

2022-10-27 11:04 UTC, CertainLach commented on crates/evm-coder/procedural/src/solidity_interface.rs
> +					quote! { (<Vec<#vec_token>>::SIGNATURE) }
Мне не понятно зачем оно лезет внутрь AbiType, когда может получить ::SIGNATURE прямо у типа

2022-10-27 11:11 UTC, bugrazoid commented on crates/evm-coder/src/custom_signature.rs
> +	// This test must NOT compile with "index out of bounds"!
Да, как раз хотел эту штуку попробовать.

2022-11-02 17:01 UTC, CertainLach commented
Superseeded by #698

2022-11-02 17:01 UTC, closed without merging