Feature/derive_Solidity
UniqueNetwork/unique-chain pull request #729
Opened 2022-11-21 05:41 UTC by bugrazoid

2022-11-24 09:14 UTC, CertainLach requested changes

2022-11-24 09:14 UTC, CertainLach commented on crates/evm-coder/procedural/src/abi_derive.rs
> +				let is_dynamic = <Self as ::evm_coder::abi::AbiType>::is_dynamic();
Предлагаю переиспользовать реализацию таплов: `(&self.1, &self.2).abi_read(reader)`

2022-11-24 09:14 UTC, CertainLach commented on crates/evm-coder/procedural/src/abi_derive.rs
> +				if <Self as ::evm_coder::abi::AbiType>::is_dynamic() {
Аналогично, предлагаю переиспользовать тапл

2022-11-24 09:14 UTC, CertainLach commented on crates/evm-coder/src/abi/mod.rs
> -			self.subresult_offset += size;
А зачем отделять чтение от перемотки?

2022-11-24 11:53 UTC, CertainLach commented on crates/evm-coder/procedural/src/abi_derive.rs
> +				let is_dynamic = <Self as ::evm_coder::abi::AbiType>::is_dynamic();
`impl AbiWrite for &T where T: AbiWrite` у нас есть в актуальном develop

2022-11-24 11:53 UTC, CertainLach commented on crates/evm-coder/src/abi/mod.rs
> -			self.subresult_offset += size;
Дубликат вопроса, уже отписал это выше

2022-11-29 20:27 UTC, mrshiposha approved these changes

2022-11-29 20:31 UTC, merged