Feature/pov estimate api
UniqueNetwork/unique-chain pull request #730
Opened 2022-11-22 10:46 UTC by mrshiposha

Added PoV estimate RPC API

2022-11-24 16:16 UTC, CertainLach approved these changes

2022-11-25 12:32 UTC, CertainLach approved these changes

2022-11-25 12:35 UTC, CertainLach requested changes

2022-11-25 12:35 UTC, CertainLach commented on tests/src/util/playgrounds/unique.dev.ts
> +        '-e', 'function(data) cql.dump(cql.chain("wss://ws-opal.unique.network:443").latest._meta, data, {omit_empty:true})',
Стоит заменить тут url опала на реальный url текущей сети
Со старой метой оно не будет работать в случае если пользователь хочет посмотреть изменения новых ключей
По хорошему метадату вообще стоит из polkadot-js передавать, но такой возможности пока нет, форматы метаданных несовместимы между polkadot.js и chainql

2022-11-25 12:56 UTC, mrshiposha commented on tests/src/util/playgrounds/unique.dev.ts
> +        '-e', 'function(data) cql.dump(cql.chain("wss://ws-opal.unique.network:443").latest._meta, data, {omit_empty:true})',
Добавил URL, использованный при подключении плейграундов

2022-11-25 13:08 UTC, CertainLach approved these changes

2022-12-21 19:03 UTC, mrshiposha commented
depends on https://github.com/UniqueNetwork/unique-chain/pull/794

2022-12-23 14:07 UTC, CertainLach approved these changes

2022-12-23 15:37 UTC, merged