Feature: add ApproveForAll to Eth and Sub
UniqueNetwork/unique-chain pull request #739
Opened 2022-11-28 10:49 UTC by fairax

2022-11-28 12:28 UTC, ut-akuznetsov approved these changes

2022-11-29 08:51 UTC, ut-akuznetsov approved these changes

2022-11-29 14:08 UTC, mrshiposha requested changes

2022-11-29 14:08 UTC, mrshiposha commented on pallets/unique/src/lib.rs
> +		pub fn set_approval_for_all(
Я поговорил с Андреем, он одобрил переименование этого экстринзика на `set_allowance_for_all`, чтобы в субстрате сохранялась непротиворечивость с экстринзиком `set_allowance`. А в эфире оставляем название `set_approval_for_all` для соответствия ERC-721.

2022-11-29 14:08 UTC, mrshiposha commented on primitives/rpc/src/lib.rs
> +		fn is_approved_for_all(collection: CollectionId, owner: CrossAccountId, operator: CrossAccountId) -> Result<bool>;
В соответствии с переименованием `set_allowance_for_all`, этот метод RPC следует назвать `allowance_for_all`.

2022-11-29 14:13 UTC, mrshiposha commented
NOTE: Для многих замечаний для NFT паллеты есть аналоги в паллете RFT.

Нужно отребейзиться и перегенерить Solidity stubs. Я слил PR Павла, там были изменения в стабах.

2022-11-30 07:18 UTC, fairax commented on pallets/nonfungible/src/lib.rs
> +	/// An operator is allowed to transfer all token pieces of the sender on their behalf.
Почему `pieces` лишнее? Аккаунт же может не владеть токеном полностью, а только его частью. И тогда странно говорить что это его токен.

2022-11-30 07:59 UTC, mrshiposha commented on pallets/nonfungible/src/lib.rs
> +	/// An operator is allowed to transfer all token pieces of the sender on their behalf.
Здесь же идет речь об NFT. Частями можно владеть только у RFT. NFT как таковой это атом

2022-11-30 09:29 UTC, fairax commented on pallets/refungible/src/lib.rs
> +		if <WalletOperator<T>>::get((collection.id, from, spender)) == Some(true) {
Прочитанное значение используется в обеих проверках. И передвигать эту проверку ниже вроде не правильно, это сломает логику.

2022-11-30 09:38 UTC, mrshiposha commented on pallets/refungible/src/lib.rs
> +		if <WalletOperator<T>>::get((collection.id, from, spender)) == Some(true) {
Эм, да вижу

2022-12-06 17:08 UTC, mrshiposha requested changes

2022-12-06 17:08 UTC, mrshiposha commented on pallets/nonfungible/src/benchmarking.rs
> +			operator: cross_from_sub(owner); owner: cross_sub;
Тут все еще надо исправить

2022-12-06 22:28 UTC, fairax commented on pallets/nonfungible/src/benchmarking.rs
> +			operator: cross_from_sub(owner); owner: cross_sub;
Очень странно, я вроде даже перепроверял что тут исправлено...

2022-12-08 11:25 UTC, mrshiposha commented on pallets/fungible/src/lib.rs
> +		/// Setting approval for all is not allowed.
```suggestion
		/// Setting allowance for all is not allowed.
```

2022-12-08 11:34 UTC, mrshiposha commented on pallets/nonfungible/src/lib.rs
> +		}
Если `access() != AccessMode::AllowList` какие права должны быть проверены? Сейчас выглядит так, что в таком случае вообще кто угодно может сделать `set_allowance_for_all`.

2022-12-08 11:38 UTC, mrshiposha commented on pallets/nonfungible/src/lib.rs
> +	/// Operator set by a wallet owner that could perform certain transactions on all tokens in the wallet.
Что значит `wallet owner`? Это collection admin?

2022-12-08 13:26 UTC, mrshiposha approved these changes

2022-12-08 13:26 UTC, merged