added `mintCross` function for `UniqueExtensoins` interfaces
UniqueNetwork/unique-chain pull request #743
Opened 2022-12-01 08:27 UTC by PraetorP

2022-12-08 16:49 UTC, mrshiposha requested changes

2022-12-08 16:49 UTC, mrshiposha commented on pallets/common/src/erc.rs
> +	fn collection_sponsor(&self) -> Result<EthCrossAccount> {
Коль начали править такие штуки, надо поправить еще в `pallets/evm-contract-helpers/src/eth.rs` в функции `fn sponsor`

2022-12-08 16:49 UTC, mrshiposha commented on pallets/common/src/eth.rs
>  	pub fn from_sub_cross_account<T>(cross_account_id: &T::CrossAccountId) -> Self
Тут внутри используется функция `convert_cross_account_to_uint256`. После правки возвращаемых значений `EthCrossAccount` эту функцию можно совсем выпиливать и использовать твою `from_substrate`

2022-12-08 16:49 UTC, mrshiposha commented on pallets/common/src/eth.rs
>  	pub fn from_sub_cross_account<T>(cross_account_id: &T::CrossAccountId) -> Self
И функцию `convert_cross_account_to_tuple` тоже можно выпилить

2022-12-08 16:49 UTC, mrshiposha commented on pallets/fungible/CHANGELOG.md
> +## [0.1.9] - 2022-12-01
Ох, наверное, лучше перед релизом бюрократа прогнать

2022-12-08 16:49 UTC, mrshiposha commented on pallets/nonfungible/src/erc.rs
> +	/// @notice Function to mint token.
```suggestion
	/// @notice Function to a mint token.
```

2022-12-08 16:49 UTC, mrshiposha commented on tests/src/eth/nonFungible.test.ts
> +import exp from 'constants';
unused

2022-12-08 16:49 UTC, mrshiposha commented on tests/src/eth/nonFungible.test.ts
> +    const permissions: ITokenPropertyPermission[] = properties.map(p => { return {key: p.key, permission: {tokenOwner: true,
Надо бы как-то отформатировать

2022-12-08 16:49 UTC, mrshiposha commented on tests/src/eth/nonFungible.test.ts
> +    expect(await contract.methods.properties(tokenId, []).call()).to.be.like(properties
По-хорошему, надо дублировать проверку выше. Все-таки аргумент изменился и, по-хорошему, все еще надо проверять, что все эвенты верные

2022-12-08 16:49 UTC, mrshiposha commented on tests/src/eth/reFungible.test.ts
> +import { ITokenPropertyPermission } from '../util/playgrounds/types';
Не должно быть пробелов после и перед скобками (eslint)

2022-12-08 16:49 UTC, mrshiposha commented on tests/src/eth/reFungible.test.ts
> +    const permissions: ITokenPropertyPermission[] = properties.map(p => { return {key: p.key, permission: {tokenOwner: true,
Форматирование

2022-12-08 16:49 UTC, mrshiposha commented on tests/src/eth/reFungible.test.ts
> +    expect(await contract.methods.properties(tokenId, []).call()).to.be.like(properties
Аналогично, как и для NFT

2022-12-08 16:49 UTC, mrshiposha commented on pallets/refungible/src/erc.rs
> +		let users = [(to, 1)]
@ut-akuznetsov тут мы "эмулируем" NFT? Типа создаем один токен, но, который, по умолчанию сразу является RFT и его можно переразбить не используя наш контракт-фракционализатор. В этом идея?

2022-12-08 16:49 UTC, mrshiposha commented on tests/src/eth/base.test.ts
> +  itEth.skip('ERC721UniqueExtensions support', async ({helper}) => {
М? Селектор поменялся, но ведь его можно и тут поменять, вроде?..

2022-12-14 12:43 UTC, PraetorP commented on tests/src/eth/base.test.ts
> +  itEth.skip('ERC721UniqueExtensions support', async ({helper}) => {
skip потому что постоянно меняется селектор интерфейса(при добавлении новых фич). @ut-akuznetsov предложил его пока заскипать

2022-12-16 11:05 UTC, bugrazoid approved these changes

2022-12-16 11:08 UTC, bugrazoid commented on tests/src/eth/reFungible.test.ts
> +    expect(event.address).to.be.equal(collectionAddress);
Мне, кажется, тут лучше использовать expect(referenceObject).to.be.like(object)

2022-12-16 15:28 UTC, fairax requested changes

2022-12-16 15:28 UTC, fairax commented on pallets/nonfungible/src/erc.rs
> +	/// @notice Function to a mint token.
```suggestion
	/// @notice Function to mint a token.
```

2022-12-16 15:28 UTC, fairax commented on pallets/nonfungible/src/erc.rs
> +	/// @notice Function to a mint token.
```suggestion
	/// @notice Function to mint a token.
```

2022-12-16 16:04 UTC, PraetorP commented on pallets/nonfungible/src/erc.rs
> +	/// @notice Function to a mint token.
https://github.com/UniqueNetwork/unique-chain/pull/743#discussion_r1043552303

2022-12-16 16:21 UTC, mrshiposha approved these changes

2022-12-16 16:21 UTC, mrshiposha commented on pallets/common/src/eth.rs
>  /// If `address` in the tuple has *default* value, then the canonical form is substrate,
Тут ниже есть функция `convert_tuple_to_cross_account`. Она больше не используется. Давай выпилим ее

2022-12-16 16:48 UTC, fairax approved these changes

2022-12-16 18:36 UTC, merged