Feature: add precompiles
UniqueNetwork/unique-chain pull request #748
Opened 2022-12-05 20:34 UTC by fairax

2022-12-13 19:58 UTC, mrshiposha requested changes

2022-12-13 19:58 UTC, mrshiposha commented on runtime/opal/Cargo.toml
> +fp-evm = { default-features = false, git = "https://github.com/uniquenetwork/frontier", branch = "unique-polkadot-v0.9.30-2" }
Нужен ребейз и во всех таких местах надо поправить на `polkadot-v0.9.33` (с префиксом `unique-` где нужно)

2022-12-13 19:58 UTC, mrshiposha commented on runtime/common/ethereum/precompiles/mod.rs
> +use pallet_evm::{Precompile, PrecompileHandle, PrecompileResult, PrecompileSet};
Надо бы добавить лицензию в новые файлы

2022-12-13 19:58 UTC, mrshiposha commented
nitpicks only

2022-12-16 07:00 UTC, PraetorP commented
С точки зрения архитектуры я бы предложил вынести `precompiles` (структкуры и их имлементации)  в отдельный крейт или уже сущуствуюший. В рантайме не должно быть реализации логики.

2022-12-16 09:18 UTC, PraetorP approved these changes

2022-12-16 13:14 UTC, bugrazoid approved these changes

2022-12-16 13:40 UTC, merged