Feature/evm permissions
UniqueNetwork/unique-chain pull request #749
Opened 2022-12-06 12:28 UTC by PraetorP

2022-12-07 08:55 UTC, ut-akuznetsov approved these changes

2022-12-12 07:16 UTC, mrshiposha requested changes

2022-12-12 07:16 UTC, mrshiposha commented on pallets/common/src/erc.rs
> +			(EvmPermissions::CollectionAdmin, nesting.collection_admin),
Выглядит как будто здесь должна быть структура

2022-12-12 07:16 UTC, mrshiposha commented on pallets/common/src/erc.rs
> +			nesting.token_owner,
Не хватает collection_admin. Они НЕ взаимноисключающие

2022-12-12 07:16 UTC, mrshiposha commented on pallets/common/src/erc.rs
> +	fn collection_nesting_permissions(&self) -> Result<Vec<(EvmPermissions, bool)>> {
Мне кажется, что если использовать структуру на выходе, можно обойтись одним методом вместо двух

2022-12-14 08:21 UTC, mrshiposha commented
@PraetorP нужен ребейз

2022-12-14 08:21 UTC, mrshiposha approved these changes

2022-12-14 14:31 UTC, merged