Feature: collection sponsoring for RFT
UniqueNetwork/unique-chain pull request #757
Opened 2022-12-08 22:47 UTC by fairax

2022-12-09 15:58 UTC, mrshiposha requested changes

2022-12-09 15:58 UTC, mrshiposha commented on tests/src/eth/collectionSponsoring.test.ts
> +    const newPermissions = (await collection.getData())!.raw.permissions; // (await getDetailedCollectionInfo(api, collectionId))!.permissions.toHuman();
Судя по всему, лишний коммент

2022-12-09 15:58 UTC, mrshiposha commented on tests/src/eth/collectionSponsoring.test.ts
> +    await expect(collectionEvm.methods.confirmCollectionSponsorship().call()).to.be.rejectedWith('caller is not set as sponsor');
Такая же проверка, как и soft deprecated. Нужна ли она?

2022-12-09 15:58 UTC, mrshiposha commented on tests/src/eth/collectionSponsoring.test.ts
> +    const sponsorCollection = helper.ethNativeContract.collection(collectionAddress, 'rft', sponsor, true);
Почему бы не использовать `collectionEvm` и `send({from: sponsor})`?

2022-12-09 15:58 UTC, mrshiposha commented on tests/src/eth/collectionSponsoring.test.ts
> +describe('evm RFT token sponsoring', () => {
В этой группе тестов похожие вопросы про `collectionEvm` выше

2022-12-12 07:30 UTC, fairax commented on tests/src/eth/collectionSponsoring.test.ts
> +    await expect(collectionEvm.methods.confirmCollectionSponsorship().call()).to.be.rejectedWith('caller is not set as sponsor');
Что спонсорство не может подтвердить кто-то кроме самого спонсора? Мне кажется нужна. Убрал дублирующие проверки.

2022-12-12 07:36 UTC, fairax commented on tests/src/eth/collectionSponsoring.test.ts
> +    await expect(collectionEvm.methods.confirmCollectionSponsorship().call()).to.be.rejectedWith('caller is not set as sponsor');
Одна для `setCollectionSponsorCross` другая для `setCollectionSponsor`. Я бы оставил.

2022-12-12 08:07 UTC, ut-akuznetsov commented on runtime/common/ethereum/sponsoring/refungible.rs
> +		| SetProperties { .. }
Вообще должны, уважая data size лимит. Если сейчас нет, то выписываем в беклог след. релиза. Мне казалось это сделали уже

2022-12-12 08:48 UTC, mrshiposha commented on tests/src/eth/collectionSponsoring.test.ts
> +    await expect(collectionEvm.methods.confirmCollectionSponsorship().call()).to.be.rejectedWith('caller is not set as sponsor');
Мне казалось, что эта проверка уже где-то есть. Ну, пусть будет.

2022-12-14 07:51 UTC, mrshiposha requested changes

2022-12-14 07:51 UTC, mrshiposha commented on tests/src/eth/collectionSponsoring.test.ts
> +  // TODO: Temprorary off. Need refactor
Судя по всему аналогичные тесты, но с Substrate адресами готовились, но не было доделаны

2022-12-14 08:03 UTC, mrshiposha requested changes

2022-12-14 08:03 UTC, mrshiposha commented on tests/src/eth/collectionSponsoring.test.ts
> +  // TODO: Temprorary off. Need refactor
TODO

2022-12-20 11:15 UTC, mrshiposha requested changes

2022-12-20 11:15 UTC, mrshiposha commented on tests/src/eth/collectionSponsoring.test.ts
> +    itEth(`[${testCase}] Check that transaction via EVM spend money from sponsor address`, async ({helper}) => {
Тест скорее проверяет, что транзакции от админа коллекций спонсируются. Надо поправить описание теста.

Что-то вроде: "Check that collection admin EVM transaction spend money from sponsor eth address". И аналогично для теста с субстратным адресом

2022-12-20 11:15 UTC, mrshiposha commented on tests/src/eth/collectionSponsoring.test.ts
> +    expect(await collectionEvm.methods.hasCollectionPendingSponsor().call()).to.be.false;
Нужно добавить проверку спонсора. "Кто был установлен спонсором?"

2022-12-20 11:15 UTC, mrshiposha commented on tests/src/eth/collectionSponsoring.test.ts
> +    await collectionSub.confirmSponsorship(sponsor);
Хорошо бы добавить проверки Unconfirmed + Confirmed, как в аналогичном эфирном тесте

2022-12-20 11:15 UTC, mrshiposha commented on tests/src/eth/collectionSponsoring.test.ts
> +      expect(ownerBalanceBefore).to.be.eq(ownerBalanceAfter);
Нет проверки баланса юзера

2022-12-20 11:15 UTC, mrshiposha commented on tests/src/eth/collectionSponsoring.test.ts
> +    await receiverTokenContract.methods.transferFrom(user, receiver, 1).send();
Хорошо бы использовать здесь tokenContract с `send({from: receiver})`

2022-12-21 14:50 UTC, mrshiposha requested changes

2022-12-21 14:50 UTC, mrshiposha commented on runtime/common/ethereum/sponsoring/refungible.rs
> +			Approve { .. } => None,
Approve мы спонсируем

2022-12-21 14:50 UTC, mrshiposha commented on runtime/common/ethereum/sponsoring/refungible.rs
> +			| MintBulkWithTokenUri { .. } => {
MintBulk* НЕ спонсируем. Только одиночные минты

2022-12-21 14:50 UTC, mrshiposha commented on tests/src/eth/collectionSponsoring.test.ts
> +      await collectionEvm.methods.confirmCollectionSponsorship().send({from: sponsor});
А проверка была добавлена? Я ее не вижу

2022-12-21 14:50 UTC, mrshiposha commented on tests/src/eth/collectionSponsoring.test.ts
> +    const sponsorTuple = await collectionEvm.methods.collectionSponsor().call({from: owner});
Мне казалось, тип уже не tuple, а EthCrossAccountId... Мб нужен ребейз?

2022-12-21 14:50 UTC, mrshiposha commented on tests/src/eth/collectionSponsoring.test.ts
> +    await collectionSub.confirmSponsorship(sponsor);
Проверка была добавлена? Не вижу ее

2022-12-21 14:50 UTC, mrshiposha commented on runtime/common/ethereum/sponsoring/refungible.rs
> +			| SafeTransferFrom { .. }
safe transfer'ы НЕ спонсируем

2022-12-21 14:53 UTC, mrshiposha requested changes

2022-12-21 14:53 UTC, mrshiposha commented on tests/src/eth/collectionSponsoring.test.ts
> +          await tokenContract.methods.transferFrom(user, receiver, 1).send();
Наверное, в случае *from методов, нужно сначала сделать approve, и делать transferFrom от апрувнутого аккаунта

2022-12-22 06:52 UTC, fairax commented on tests/src/eth/collectionSponsoring.test.ts
> +      await collectionEvm.methods.confirmCollectionSponsorship().send({from: sponsor});
Я добавил её в другом методе. Это не принципиально наверное?

2022-12-22 06:53 UTC, fairax commented on tests/src/eth/collectionSponsoring.test.ts
> +    const sponsorTuple = await collectionEvm.methods.collectionSponsor().call({from: owner});
Переименовал переменную, чтобы имя не смущало.

2022-12-22 06:55 UTC, fairax commented on tests/src/eth/collectionSponsoring.test.ts
> +          await tokenContract.methods.transferFrom(user, receiver, 1).send();
Мы тестируем тут спонсоринг, проверка, что апрув с transferFrom работают как надо,  есть в другом месте. Так что я не вижу смысла тут усложнять.

2022-12-22 06:58 UTC, fairax commented on runtime/common/ethereum/sponsoring/refungible.rs
> +			| SafeTransferFrom { .. }
Они ещё не реализованы.

2022-12-22 07:01 UTC, fairax commented on runtime/common/ethereum/sponsoring/refungible.rs
> +			Approve { .. } => None,
Этот метод не поддерживается для Refungible.

2022-12-22 09:16 UTC, mrshiposha commented on runtime/common/ethereum/sponsoring/refungible.rs
> +			| SafeTransferFrom { .. }
И мы их не будем спонсировать в начале в любом случае

2022-12-22 09:19 UTC, mrshiposha commented on runtime/common/ethereum/sponsoring/refungible.rs
> +			Approve { .. } => None,
Хмм, то есть мы поддерживаем approve erc-20, но не поддерживаем approve erc-721?

2022-12-22 15:16 UTC, CertainLach requested changes

2022-12-22 15:16 UTC, CertainLach commented on runtime/common/ethereum/sponsoring.rs
> +			let rft_collection = RefungibleHandle::cast(collection);
Нужна проверка что collection.mode == Refungible
::cast её не проводит, он ожидает что ему передали нужную коллекцию

2022-12-22 15:16 UTC, CertainLach commented on runtime/common/ethereum/sponsoring.rs
> +			let token = RefungibleTokenHandle(rft_collection, token_id);
Существование токена в данном случае тоже стоит проверить, т.к модуль erc20 как будто подразумевает что NFT токен существует
С текущим кодом это может и не быть проблемой, однако не помешает обезопасить себя.

2022-12-23 11:35 UTC, CertainLach commented on pallets/evm-contract-helpers/src/stubs/ContractHelpers.sol
> +	/// TODO: field description
Тут всего пара строк, напиши уж, раз "исправил" ворнинг)

2022-12-23 11:43 UTC, CertainLach commented on runtime/common/ethereum/sponsoring.rs
> +			// Token existance isn't checked at this point and should be checked in `withdraw` method.
Этот комментарий я предлагал над erc20 и прочими повесить

2022-12-23 13:34 UTC, CertainLach approved these changes

2022-12-23 13:34 UTC, merged