Feature/add_evm_events
UniqueNetwork/unique-chain pull request #758
Opened 2022-12-09 09:07 UTC by bugrazoid

2022-12-09 19:15 UTC, mrshiposha requested changes

2022-12-12 07:18 UTC, bugrazoid commented on pallets/common/src/erc.rs
> +		self.consume_store_reads_and_writes(2, 2)?;
Поменялось в toggle_admin

2022-12-12 08:08 UTC, ut-akuznetsov commented on pallets/common/src/erc.rs
> +	CollectionChanged {
Да, это для эфира, только по одному ивенту - collection changed и token changed. Дробления на более конкретные ивенты не нужно

2022-12-12 08:53 UTC, bugrazoid commented on pallets/common/src/lib.rs
> +	/// 2 reads, 2 writes
Точно, забыл.

2022-12-12 09:03 UTC, bugrazoid commented on pallets/unique/src/lib.rs
>  	pub fn force_remove_collection_sponsor(collection_id: CollectionId) -> DispatchResult {
Да, используются

2022-12-12 09:14 UTC, ut-akuznetsov commented on pallets/common/src/lib.rs
> +		CollectionLimitSet(
Не в этом релизе, надо положить в беклог

2022-12-12 19:03 UTC, mrshiposha commented
@ut-akuznetsov в этом PR **переименованы** 2 евента:
* CollectionOwnedChanged -> CollectionOwne**r**Changed
* unique.ConfirmUnsetSponsorFail -> common.ConfirmSponsorshipFail (ибо название не соот-ет действию, непонятно к чему относится Unset. Никакого Unset при неудачной попытке подтверждения спонсоринга не происходит)

2022-12-12 20:04 UTC, mrshiposha requested changes

2022-12-13 06:31 UTC, bugrazoid commented on pallets/common/src/lib.rs
> -			// =========
Не зняю, я впринципе, не люблю такого рода комментарии. Они не информативны, а как разделитель и пустая строка хорошо работает.

2022-12-13 06:33 UTC, bugrazoid commented on tests/src/eth/createFTCollection.test.ts
> +        .setCollectionLimit('accountTokenOwnershipLimit', '1000')
Просто поменялся порядок проверок, и тест заваливался до того как провериться имя лимита.

2022-12-13 06:53 UTC, bugrazoid commented on tests/src/eth/util/playgrounds/unique.dev.ts
> +  createAccount(): TEthCrossAccount {
Просто что бы чуть проще было создавать кроссаккаунты. QOL - изменение.

2022-12-13 09:16 UTC, mrshiposha commented on pallets/common/src/lib.rs
> -			// =========
Не, это надо, ибо у нас везде такое. Я не вводил эти комменты, но альтернативы нет. Сделай можалуйста эту строчку до if. 

Мне тоже не нравится именно такого вида комментарий, но он нас такой сейчас везде, мне не хочется что-либо еще выдумывать

2022-12-13 09:18 UTC, mrshiposha commented on tests/src/eth/createFTCollection.test.ts
> +        .setCollectionLimit('accountTokenOwnershipLimit', '1000')
Эм, я не вижу пути по которому тест не доходил до этого места

2022-12-13 09:18 UTC, mrshiposha commented on tests/src/eth/createFTCollection.test.ts
> +        .setCollectionLimit('accountTokenOwnershipLimit', '1000')
А или просто другая ошибка срабатывала раньше. Ну окей

2022-12-13 09:26 UTC, bugrazoid commented on tests/src/eth/createFTCollection.test.ts
> +        .setCollectionLimit('accountTokenOwnershipLimit', '1000')
Проверка прав была перенесена отсюда https://github.com/UniqueNetwork/unique-chain/blob/0a0e4a9ae3eca887ef9b6072b2f1d7e7295a81b8/pallets/common/src/erc.rs#L321
сюда, внутрь функции "<Pallet<T>>::update_limits" https://github.com/UniqueNetwork/unique-chain/blob/0a0e4a9ae3eca887ef9b6072b2f1d7e7295a81b8/pallets/common/src/erc.rs#L371

2022-12-14 08:09 UTC, mrshiposha approved these changes

2022-12-14 08:11 UTC, merged