added `collectionLimits` function in `Collection` interface,  changed…
UniqueNetwork/unique-chain pull request #759
Opened 2022-12-09 09:38 UTC by PraetorP

… signture for `setCollectionLimit`

2022-12-09 11:59 UTC, Maksandre commented on pallets/nonfungible/src/stubs/UniqueNFT.sol
> +	/// @dev EVM selector for this function is: 0x88150bd0,
Please add some docs to `@param status`

2022-12-12 08:27 UTC, mrshiposha requested changes

2022-12-12 08:27 UTC, mrshiposha commented on pallets/common/src/erc.rs
> +	fn collection_limits(&self) -> Result<Vec<(EvmCollectionLimits, bool, uint256)>> {
Мне снова кажется, что структуру возвращать было бы лучше.

Например, структуры такого вида:
```
// нужно реализовать From<crate::eth::CollectionLimits> для этой штуки
struct EvmCollectionLimits {
    accountTokenOwnershipLimit: CollectionLimit,
    sponsoredDataSize: CollectionLimit,
// и т. д.
}

struct CollectionLimit {
    present: bool,
    value: uint256,
}
```

А в тестах проверять равенство структур. Соот-но, если мы добавим новое поле в лимиты на стороне primitive-data-structs, а сюда забудем -- тест это поймает.

Уж очень не хочется делать поле зависимым от индекса в массиве.

2022-12-12 08:27 UTC, mrshiposha commented on pallets/common/src/erc.rs
> +		if !status {
Зачем нужна переменная `status`? Она нигде не используется, кроме этой проверки. Соот-но может только одно значение == true.

2022-12-12 08:27 UTC, mrshiposha commented on pallets/common/src/erc.rs
> +	fn set_collection_limit(
В принципе, если у нас будет структура, описанная выше, можно изменить этот метод на `set_collection_limits(caller, limits: EvmCollectionLimits)`, чтобы устанавливать лимиты разом.

@ut-akuznetsov мы можем так сделать? Мы же все равно меняем аргументы сейчас.

2022-12-12 08:59 UTC, ut-akuznetsov commented on pallets/common/src/erc.rs
> +	fn set_collection_limit(
Нет, сигнатуры - это требование от Сафта, они согласованы именно в том виде, как реализованы

2022-12-12 09:03 UTC, ut-akuznetsov commented on pallets/common/src/erc.rs
> +	fn collection_limits(&self) -> Result<Vec<(EvmCollectionLimits, bool, uint256)>> {
Тут тоже требование, нужен именно массив вместо структуры, для расширяемости

2022-12-12 09:04 UTC, mrshiposha commented on pallets/common/src/erc.rs
> +		if !status {
Точно надо убирать этот аргумент, см. коммент ниже

2022-12-14 09:38 UTC, mrshiposha requested changes

2022-12-14 09:38 UTC, mrshiposha commented on pallets/common/src/erc.rs
> +fn convert_bool_limit(
Эти функции используются? Я вижу только использование аналогичных замыканий

2022-12-15 08:27 UTC, PraetorP commented on pallets/common/src/erc.rs
> +	fn set_collection_limit(
@mrshiposha, имеется в виду, что в таком же виде, что уже сделаны сейчас. @ut-akuznetsov, подтвердишь ?!

2022-12-15 09:15 UTC, mrshiposha commented on pallets/common/src/erc.rs
> +	fn set_collection_limit(
Это зарезолвлено, Андрей сказал, что изменения по этим сигнатурам были согласованы.

2022-12-15 14:33 UTC, bugrazoid requested changes

2022-12-15 14:33 UTC, bugrazoid commented on tests/src/eth/util/index.ts
> +export enum CollectionLimits {
Мне кажется умкстней перенести в playgrounds/typess.ts

2022-12-15 14:33 UTC, bugrazoid commented on tests/src/eth/collectionLimits.test.ts
> +      expect(limitsEvm[0]).to.deep.eq(['0', true, limits.accountTokenOwnershipLimit.toString()]);
```suggestion
      expect(limitsEvm[0]).to.deep.eq([CollectionLimits.AccountTokenOwnership.toString(), true, limits.accountTokenOwnershipLimit.toString()]);
```

2022-12-16 10:37 UTC, fairax approved these changes

2022-12-16 10:37 UTC, fairax commented on pallets/common/src/erc.rs
> +				})
Nitpick
```suggestion
				.and_then(|limit| {
					if let SponsoringRateLimit::Blocks(blocks) = limit {
						Some((
							EvmCollectionLimits::SponsoredDataRateLimit,
							true,
							blocks.into(),
						))
					} else {
						None
					}
				})
```

2022-12-16 10:49 UTC, fairax requested changes

2022-12-16 10:49 UTC, fairax commented on pallets/common/src/eth.rs
> +}
Warning: missing documentation. И ниже у `CollectionPermissions` тоже.

2022-12-16 12:47 UTC, fairax commented on pallets/common/src/eth.rs
> +}
В `CollectionPermissions` Фархад уже добавил комменты.

2022-12-16 14:02 UTC, fairax approved these changes

2022-12-16 14:12 UTC, bugrazoid approved these changes

2022-12-16 15:36 UTC, merged