added the  ability to configure pallet `app-promotion` via the `confi…
UniqueNetwork/unique-chain pull request #766
Opened 2022-12-13 11:59 UTC by PraetorP

…guration` palette

2022-12-13 13:02 UTC, mrshiposha commented on pallets/configuration/CHANGELOG.md
> +- The ability to configure pallet `app-promotion` via the `configuration` palette
```suggestion
- The ability to configure pallet `app-promotion` via the `configuration` pallet
```

2022-12-13 13:03 UTC, mrshiposha commented on pallets/configuration/src/lib.rs
> +		type AppPromotionDailyRate: Get<Perbill>;
Мы, вроде, решили, что константы, которые относятся к app promotion будем держать в его конфиге, а не здесь

2022-12-13 13:05 UTC, mrshiposha commented on pallets/configuration/src/lib.rs
> +	pub type AppPromomotionConfigurationOverride<T: Config> = StorageValue<
На мой взгляд, лучше хранить прям всю структуру AppPromotionConfiguration здесь. И на вход экстринзика брать всю структуру целиком

2022-12-13 13:06 UTC, mrshiposha commented on pallets/configuration/src/lib.rs
> +						Perbill::from_rational(b, T::DayRelayBlocks::get())
Все вычиаления я бы вынес в app promotion (например, в метод AppPromotionConfiguration::get)

2022-12-14 10:38 UTC, mrshiposha requested changes

2022-12-14 10:38 UTC, mrshiposha commented on tests/src/app-promotion.test.ts
> +      palletAdmin = await privateKey('//Alice');
@Maksandre это норм в `*.test.ts` файлах?

2022-12-14 10:38 UTC, mrshiposha commented on tests/src/app-promotion.test.ts
> +          pendingInterval: UNLOCKING_PERIOD})], true);
Отформатировать бы

2022-12-14 10:38 UTC, mrshiposha commented on tests/src/app-promotion.test.ts
> +      await helper.executeExtrinsic(palletAdmin, 'api.tx.sudo.sudo', [helper.api!.tx.appPromotion.setAdminAddress({Substrate: palletAdmin.address})]);
`true` в конце, наверное, нужно. Это `expectSuccess`

2022-12-14 10:38 UTC, mrshiposha commented on tests/src/app-promotion.test.ts
> +
Эм... Тест опустел?)

2022-12-14 10:40 UTC, Maksandre commented on tests/src/app-promotion.test.ts
> +      palletAdmin = await privateKey('//Alice');
Нет, надо вернуть //PromotionAdmin

2022-12-14 10:59 UTC, mrshiposha approved these changes

2022-12-14 16:55 UTC, merged