Feature/evm_set-get_tokenPropertyPermissions
UniqueNetwork/unique-chain pull request #776
Opened 2022-12-15 07:49 UTC by bugrazoid

2022-12-15 14:19 UTC, Maksandre commented on tests/src/eth/tokenProperties.test.ts
> +    itEth.ifWithPallets(`[${testCase.mode}] Set and get token property permissions`, testCase.requiredPallets, async({helper}) => {
Would nice to have some negative tests

2022-12-16 05:36 UTC, PraetorP commented on pallets/nonfungible/src/erc.rs
> +			let mut token_permission = PropertyPermission {
Я бы предложил навесить Default для PropertyPermission вызывать его . Либо уже рассмотреть использование `none()`

2022-12-16 05:41 UTC, PraetorP commented on pallets/nonfungible/src/erc.rs
> +		Ok(res)
Может лучше сразу Ok(vec![...]) ?

2022-12-16 06:37 UTC, PraetorP approved these changes

2022-12-16 07:29 UTC, fairax requested changes

2022-12-16 07:29 UTC, fairax commented on pallets/nonfungible/src/erc.rs
> +		let mut res = <Vec<_>>::new();
```suggestion
		let mut res = Vec::new();
```

2022-12-16 07:29 UTC, fairax commented on pallets/nonfungible/src/erc.rs
> +		let mut perms = <Vec<_>>::new();
```suggestion
		let mut perms = Vec::new();
```

2022-12-16 07:29 UTC, fairax commented on pallets/nonfungible/src/erc.rs
> +					.map_err(|_| "too long key")?,
```suggestion
				key: key.into_bytes().try_into().map_err(|_| "too long key")?,
```

2022-12-16 07:29 UTC, fairax commented on pallets/refungible/src/erc.rs
> +	fn set_token_property_permissions(
Не задан вес. Для set_token_property_permission вес есть в новой версии develop, а этот метод новый.

2022-12-16 07:29 UTC, fairax commented on pallets/refungible/src/erc.rs
> +		let mut perms = <Vec<_>>::new();
```suggestion
		let mut perms = Vec::new();
```

2022-12-16 07:29 UTC, fairax commented on pallets/refungible/src/erc.rs
> +					.map_err(|_| "too long key")?,
```suggestion
				key: key.into_bytes().try_into().map_err(|_| "too long key")?,
```

2022-12-16 12:46 UTC, fairax commented on pallets/common/src/eth.rs
> +pub enum EthTokenPermissions {
В методах `from_sub_cross_account` и `into_sub_cross_account` Фархад похоже уже сам добавил коменты.

2022-12-16 13:45 UTC, fairax approved these changes

2022-12-16 13:53 UTC, merged