Feature/refinement_on_named_structures
UniqueNetwork/unique-chain pull request #795
Opened 2022-12-21 06:40 UTC by bugrazoid

2022-12-21 12:49 UTC, PraetorP approved these changes

2022-12-21 12:49 UTC, PraetorP commented on crates/evm-coder/procedural/src/abi_derive/derive_enum.rs
> +			const FIELDS_COUNT: usize = #option_count;
@CertainLach, @bugrazoid добавил элементы мета информации о типе. Это не совсем в рамках задачи данного PR. Хотелось бы узнать твое мнение об этом нововведении.

2022-12-21 12:49 UTC, PraetorP commented on pallets/common/src/eth.rs
> +	pub fn from_opt_int(field: CollectionLimitField, value: Option<u32>) -> Self {
```
pub fn from_opt_int<T: Into<u32>>(field: CollectionLimitField, value: Option<T>) -> Self {
```

2022-12-21 12:49 UTC, PraetorP commented on pallets/evm-contract-helpers/src/eth.rs
> +	fn sponsor(&self, contract_address: address) -> Result<pallet_common::eth::CrossAccount> {
Может все таки объявить use ? Кстати, он был в этом файле.

2022-12-21 12:49 UTC, PraetorP commented on pallets/refungible/src/erc_token.rs
> +		from: pallet_common::eth::CrossAccount,
@fairax, мне не нравится, что @bugrazoid решил избавится от use. Я бы поправил. Тем не менее, окончательное решение оставляю за тобой.

2022-12-21 13:01 UTC, bugrazoid commented on pallets/common/src/eth.rs
> +pub struct OptionUint {
Пока не уверен, это лучше отдельной задачей

2022-12-21 15:00 UTC, CertainLach commented on crates/evm-coder/procedural/src/abi_derive/derive_enum.rs
> +			const FIELDS_COUNT: usize = #option_count;
Я чот не помнимаю для чего это вообще)

2022-12-21 15:10 UTC, CertainLach requested changes

2022-12-21 15:10 UTC, CertainLach commented on pallets/common/src/eth.rs
> +pub struct CrossAccount {
Если переименовывать CrossAccount, то предлагаю использовать CrossAddress

По аналогии с substrate
AccountId => CrossAccountId
address => CrossAddress

В терминологии эфира так будет правильнее

2022-12-21 15:10 UTC, CertainLach commented on crates/evm-coder/src/solidity/impls.rs
> +		unimplemented!("Vectors have not declarations.")
Зачем тогда реализация этого трейта, если ничего собирать для этого типа не нужно?

2022-12-21 15:10 UTC, CertainLach commented on crates/evm-coder/src/solidity/mod.rs
>  		<T as StructCollect>::name()
Объясню почему метод называется names вообще
Идея была в том, что этот метод возвращает типы элементов тапла, и при этом имеет возможность какие-то из них коллекционировать, дабы выдать id (Т.к названия в таплах генерируются автоматически)

Для структур соответственно метод этот стоит изменить, он должен вовзращать не просто типы, а типы + названия полей

Ну и просто так мы не можем игнорировать его выхлоп, т.к у нас в структуре могут быть таплы, что текущий код не поддерживает:

```rust
struct BrokenStruct {
  field: (uint32, uint32),
}
```

2022-12-21 15:10 UTC, CertainLach commented on pallets/common/src/eth.rs
> +pub struct OptionUint {
Да по идее тут достаточно просто `impl AbiType for Option<T> where T: AbiType { const NAME = name!(static("Option") name(T::NAME)); }`

2022-12-21 17:21 UTC, bugrazoid commented on pallets/common/src/eth.rs
> +pub struct OptionUint {
Это все трейты надо будет ручками написать + тесты. Не думаю что стоить тратить на это время в текущем релизе.

2022-12-21 17:24 UTC, bugrazoid commented on crates/evm-coder/procedural/src/abi_derive/derive_enum.rs
> +			const FIELDS_COUNT: usize = #option_count;
Я использовал для проверки количества полей в векторе.

2022-12-21 17:24 UTC, bugrazoid commented on pallets/common/src/eth.rs
> +pub struct CrossAccount {
Звучит логично. Сделаю.

2022-12-22 08:25 UTC, fairax requested changes

2022-12-22 08:25 UTC, fairax commented on pallets/common/src/erc.rs
> +				let (key, value) = property.take_key_value();
Мне сложнее понять смысл метода `take_key_value` чем простой паттерн матчинг. Кроме того не ясно зачем преобразовывать структуру в тапл и паттерн матчить его, вместо непостредственного матчинга структуры.

2022-12-22 08:25 UTC, fairax commented on pallets/common/src/eth.rs
> +	pub fn from_opt_int(field: CollectionLimitField, value: Option<u32>) -> Self {
Можно даже
```
	/// Make [`CollectionLimit`] from [`CollectionLimitField`]
	pub fn new<T>(field: CollectionLimitField, value: T) -> Self
	where
		OptionUint: From<T>,
	{
		Self {
			field,
			value: value.into(),
		}
	}
```

2022-12-22 09:18 UTC, CertainLach requested changes

2022-12-22 09:18 UTC, CertainLach commented on tests/src/eth/api/UniqueNFT.sol
> +	OptionUint value;
А зачем тут кстати Option?
В случае с substrate у нас опциональные поля в CollectionLimits нужны потому, что None = поле трогать не нужно
Возможности сбросить к чейновым дефолтам у нас там нет, а соответственно тут должен быть просто uint

2022-12-22 09:20 UTC, CertainLach commented on pallets/common/src/eth.rs
> +	pub fn from_opt_int(field: CollectionLimitField, value: Option<u32>) -> Self {
Тогда уж `: Into<U256>`

2022-12-22 09:28 UTC, bugrazoid commented on pallets/common/src/erc.rs
> +				let (key, value) = property.take_key_value();
Чет я  себя фигово чувствовал. Делал для того, что бы не использовать поля напрямую, а все преобразования инкапсулировать внутрь типа. Поправлю.

2022-12-22 09:40 UTC, bugrazoid commented on tests/src/eth/api/UniqueNFT.sol
> +	OptionUint value;
Это скорее вопрос к @ut-akuznetsov . Так то здесь это выглядит странным. Делал по по требованию.

2022-12-22 10:18 UTC, fairax requested changes

2022-12-22 10:18 UTC, fairax commented on pallets/refungible/src/erc_token.rs
> +		from: pallet_common::eth::CrossAccount,
Да, хотябы до `eth::CrossAccount` сократить будет не лишним.

2022-12-22 10:29 UTC, fairax commented on pallets/refungible/src/erc_token.rs
> +		from: pallet_common::eth::CrossAccount,
Да, сократить хотябы до `eth::CrossAccount` не помешает.

2022-12-22 10:30 UTC, fairax commented on pallets/common/src/eth.rs
> +	pub fn from_opt_int(field: CollectionLimitField, value: Option<u32>) -> Self {
Можно и
```
	pub fn new<T>(field: CollectionLimitField, value: T) -> Self
	where
		OptionUint: From<T>,
	{
		Self {
			field,
			value: value.into(),
		}
	}
```

2022-12-22 10:42 UTC, bugrazoid commented on pallets/common/src/eth.rs
> +		let value = self.value.value.try_into().map_err(|error| {
Пока это лишнее. С Option'ом будем разбираться уже в следующем релизе.

2022-12-22 10:59 UTC, ut-akuznetsov commented on tests/src/eth/api/UniqueNFT.sol
> +	OptionUint value;
Такая сигнатура - это требование Сафта для совместимости с получением этих данных. В случае None будет выдаваться ошибка, так что тут более-менее норм

2022-12-22 12:29 UTC, fairax requested changes

2022-12-22 12:29 UTC, fairax commented on crates/evm-coder/src/abi/impls.rs
> +macro_rules! count {
warning: unused macro

2022-12-22 12:31 UTC, fairax approved these changes

2022-12-22 20:25 UTC, merged