Feature: Add ApproveFrom eth mirror
UniqueNetwork/unique-chain pull request #818
Opened 2023-01-09 09:44 UTC by fairax

2023-01-09 10:59 UTC, CertainLach requested changes

2023-01-09 10:59 UTC, CertainLach commented on pallets/fungible/src/lib.rs
> +	pub fn set_allowance_for(
_from*

2023-01-09 10:59 UTC, CertainLach commented on pallets/fungible/src/lib.rs
> +		if collection.permissions.access() == AccessMode::AllowList {
Лучше этот метод реализовать как остальные _from методы, см transfer_from/burn_from
Т.е вызывается check_allowed, а затем отрабатывает обычный код метода

2023-01-09 10:59 UTC, CertainLach commented on pallets/fungible/src/lib.rs
> +		if collection.permissions.access() == AccessMode::AllowList {
Только нужно обратить внимание на случаи sender == from / sender == to

2023-01-10 10:33 UTC, ut-akuznetsov approved these changes

2023-01-10 10:42 UTC, CertainLach approved these changes

2023-01-10 10:42 UTC, merged