fix: rft admin can unnest
UniqueNetwork/unique-chain pull request #831
Opened 2023-01-13 17:20 UTC by mrshiposha

2023-01-13 17:41 UTC, CertainLach requested changes
По идее этот коммит не нужен?

2023-01-13 17:41 UTC, CertainLach commented on pallets/refungible/src/lib.rs
> +		if collection.limits.owner_can_transfer() && collection.is_owner_or_admin(spender) {
Ниже есть вызов ignores_allowance:
https://github.com/UniqueNetwork/unique-chain/blob/2f349378f11ae0582f3bf68aadf65d5ffd0f0cf8/pallets/common/src/lib.rs#L394

2023-01-13 17:42 UTC, CertainLach commented on pallets/refungible/src/lib.rs
> +		if collection.limits.owner_can_transfer() && collection.is_owner_or_admin(spender) {
Комментарий к ignores_allowance правда сомнительный

2023-01-15 20:40 UTC, mrshiposha commented on pallets/refungible/src/lib.rs
> +		if collection.limits.owner_can_transfer() && collection.is_owner_or_admin(spender) {
Нужен, если попытаемся что-то делать с вложенным токеном. Если токен вложенный и админ попытается его сжечь -- ничего не выйдет. До ignore_allowance мы просто не дойдем.

2023-01-15 20:40 UTC, mrshiposha commented on pallets/refungible/src/lib.rs
> +		if collection.limits.owner_can_transfer() && collection.is_owner_or_admin(spender) {
Тесты как раз проверяют сценарий вложенного токена

2023-01-15 21:23 UTC, CertainLach commented on pallets/refungible/src/lib.rs
> +		if collection.limits.owner_can_transfer() && collection.is_owner_or_admin(spender) {
А, понял
Измени тогда тут на вызов .ignores_allowance, а ниже его проверку убери, т.к она станет невыполнимой

2023-01-15 21:56 UTC, CertainLach commented on pallets/refungible/src/lib.rs
> +		if collection.limits.owner_can_transfer() && collection.is_owner_or_admin(spender) {
А в идеале наверное стоит вынести эту проверку в сам нестинг, чтобы сделать счастливый путь ещё дешевле... Но меня где варианта устроят

2023-01-16 08:19 UTC, mrshiposha commented on pallets/refungible/src/lib.rs
> +		if collection.limits.owner_can_transfer() && collection.is_owner_or_admin(spender) {
Ну, тогда это не единообразно с NFT. В NFT сделано именно так. Если менять, то одновременно. Да и тут не только про нестинг. Можно обсудить на митинге

2023-01-16 22:37 UTC, CertainLach approved these changes

2023-01-16 22:37 UTC, merged