Fix: fix more warnings
UniqueNetwork/unique-chain pull request #833
Opened 2023-01-16 06:58 UTC by fairax

2023-01-16 09:26 UTC, CertainLach requested changes

2023-01-16 09:26 UTC, CertainLach commented on pallets/evm-contract-helpers/src/lib.rs
> -	#[deprecated]
Зачем, это хранилище не стоит использовать, оно deprecated

2023-01-16 09:26 UTC, CertainLach commented on pallets/common/src/lib.rs
> -	#[pallet::generate_deposit(pub fn deposit_event)]
А что не так с deposit_event?..

2023-01-16 09:26 UTC, CertainLach commented on pallets/unique/src/lib.rs
> -		#[deprecated(note = "`create_collection_ex` is more up-to-date and advanced, prefer it instead")]
Все deprecated вещи мы планируем в будущем убрать
Если сейчас они где-то нужны - то по месту вызова можно оставить #[allow(deprecated)]

2023-01-16 09:29 UTC, fairax commented on pallets/common/src/lib.rs
> -	#[pallet::generate_deposit(pub fn deposit_event)]
Макрос генерирует код, который кидает варнинг. Я не вижу способа починить это другим способом.

2023-01-16 09:30 UTC, fairax commented on pallets/evm-contract-helpers/src/lib.rs
> -	#[deprecated]
Я сделал его приватным, это должно уменьшить вероятность что его будут использовать. Могу ещё коменты добавить? что оно deprecated.

2023-01-16 09:59 UTC, fairax commented on pallets/unique/src/lib.rs
> -		#[deprecated(note = "`create_collection_ex` is more up-to-date and advanced, prefer it instead")]
Оно вызывается в генерированном макросом коде, так что просто по мету вызова `allow` добавить не получится.

2023-01-16 13:03 UTC, CertainLach commented on pallets/evm-contract-helpers/src/lib.rs
> -	#[deprecated]
Добавь пожалуйста

2023-01-17 07:00 UTC, fairax commented on pallets/common/src/lib.rs
> -	#[pallet::generate_deposit(pub fn deposit_event)]
Сгенерированный код:
```
impl<T: Config> Pallet<T> {
		pub fn deposit_event(event: Event<T>) {
			let event = <<T as Config>::RuntimeEvent as From<Event<T>>>::from(event);
			let event = <<T as Config>::RuntimeEvent as Into<
				<T as frame_system::Config>::RuntimeEvent,
			>>::into(event);
			<frame_system::Pallet<T>>::deposit_event(event)
		}
	}
```
Варниг:
```
missing documentation for an associated functionrustc[Click for full compiler diagnostic](rust-analyzer-diagnostics-view:/diagnostic%20message%20%5B1%5D?1#file%3Aunique-chain%2Fpallets%2Fcommon%2Fsrc%2Flib.rs)
lib.rs(52, 9): the lint level is defined here
```

2023-01-18 08:24 UTC, merged