Feature: check formatting before push
UniqueNetwork/unique-chain pull request #838
Opened 2023-01-17 08:22 UTC by fairax

2023-08-15 09:16 UTC, CertainLach commented on init.sh
> +git config --local core.hooksPath ./.githooks
Скопируй хук в .git, чтобы изменениями репозитория нельзя было вызвать RCE

2023-09-07 11:25 UTC, fairax commented on init.sh
> +git config --local core.hooksPath ./.githooks
Может расширить init.sh? Добавить туда
`cd tests
yarn install` ?

2023-09-11 08:29 UTC, CertainLach commented on init.sh
> +git config --local core.hooksPath ./.githooks
Да всё равно лучше на таск-раннер это спихнуть

2023-09-12 07:04 UTC, fairax commented on init.sh
> +git config --local core.hooksPath ./.githooks
> Скопируй хук в .git, чтобы изменениями репозитория нельзя было вызвать RCE

Ну во-первых, это в любом случае не RCE, т.к. вызов кода происходит не удалённо, а только если пользователь сам случайно вызовет вредоносный код.
Во-вторых, если кто-то может положить вредоносный код в репозиторий, обойдя code review, то у него есть ещё куча способов навредить и без изменения этого конкретного хука.
Вместе с тем при переносе кода в .git пользователям придётся вызывать скрипт копирования каждый раз когда мы что-то меняем в хуке. Сообщить пользователю о необходимости вызвать скрипт копирования хотябы один раз уже проблема, а сообщать ему каким-то образом о том, что нужно вызвать скрипт повторно, это вообще по моему не реально.

2023-09-21 07:44 UTC, CertainLach requested changes

2023-09-21 07:44 UTC, CertainLach commented on README.md
> +make init-fmt-on-commit
Такого в мейкфайле нет

2023-09-21 07:44 UTC, CertainLach commented on node_modules/.yarn-integrity
> +{
Ты вызвал yarn в корневой директории, этих файлов быть не должно

2023-09-22 07:54 UTC, CertainLach approved these changes

2023-09-22 07:54 UTC, merged