Feature: Preimage + Execution via Maintenance
UniqueNetwork/unique-chain pull request #893
Opened 2023-02-21 15:48 UTC by Fahrrader

2023-02-21 16:32 UTC, CertainLach requested changes
Мне не очень нравится что у нас транзакции для обслуживания есть и в pallet-evm-migration, и (после этого ПРа) в pallet-maintenance

Может всё-таки оставим эту палету минимальной, а все новые подобные фичи продолжим в evm-migration добавлять?

2023-02-21 16:32 UTC, CertainLach commented on pallets/maintenance/src/lib.rs
> +			let len = T::Preimages::len(&hash).ok_or(DispatchError::Unavailable)?;
Почему бы не `.fetch(&hash, None)?` + в явном виде декодировать RuntimeCall? Я вижу семантику, но мне кажется что нам не нужны тут лишние сложности

2023-02-21 16:32 UTC, CertainLach commented on pallets/maintenance/src/weights.rs
> +	fn execute_preimage() -> Weight {
Не редактируй веса вручную, эти изменения затрёт при бенчмарках
Вместо этого добавь в бенчмарки вызов этого экстринзика с какой-либо дешёвой транзакцией

2023-02-21 16:32 UTC, CertainLach commented on pallets/maintenance/src/lib.rs
> +		#[pallet::weight(<T as Config>::WeightInfo::execute_preimage())]
Сюда нужно добавить стоимость закодированного вызова

Т.к мы не знаем её заранее, можно принимать Weight аргументом, и проверять что Call::pre_dispatch его не превышает

2023-02-21 16:32 UTC, CertainLach commented on runtime/common/runtime_apis.rs
> +                    // todo:governance switch feature to governance
Если мы хотим это в релиз - то стоит прымо сейчас на фичу это и перевести)

2023-02-21 16:38 UTC, mrshiposha commented on pallets/maintenance/src/lib.rs
> +		#[pallet::weight(<T as Config>::WeightInfo::execute_preimage())]
Ярослав меня опередил :)

-----

\+ вернуть сдачу, сколько осталось

2023-02-21 16:41 UTC, mrshiposha commented on pallets/maintenance/src/lib.rs
> +			let len = T::Preimages::len(&hash).ok_or(DispatchError::Unavailable)?;
По-хорошему, тут нужен length_bound, ибо читать длину тоже стоит денег -- надо учитывать в весе

2023-02-21 16:44 UTC, mrshiposha commented on pallets/maintenance/src/lib.rs
> +			let len = T::Preimages::len(&hash).ok_or(DispatchError::Unavailable)?;
Мб, стоит дать Operational class этому экстринзику

2023-02-21 16:55 UTC, CertainLach commented on pallets/maintenance/src/lib.rs
> +			let len = T::Preimages::len(&hash).ok_or(DispatchError::Unavailable)?;
Если добавить проверку длины и использовать её для веса - то имеет смысл текущий код расширить, да. Можно из переданного weight делать checked_sub длины preimage

2023-02-21 16:55 UTC, CertainLach commented on pallets/maintenance/src/lib.rs
> +			let len = T::Preimages::len(&hash).ok_or(DispatchError::Unavailable)?;
Operational тут излишен

2023-02-21 16:57 UTC, Fahrrader commented on pallets/maintenance/src/weights.rs
> +	fn execute_preimage() -> Weight {
Я знаю, но их же нужно чем-то занять сейчас, чтобы дать ссылку на вес вызову)

2023-02-21 16:59 UTC, mrshiposha requested changes

2023-02-21 16:59 UTC, mrshiposha commented on runtime/common/config/pallets/governance.rs
> +	// pub PreimageByteDeposit: Balance = 1 * CENTIUNIQUE; // deposit(0, 1);
unneeded comment

2023-02-21 16:59 UTC, mrshiposha commented on runtime/common/config/pallets/governance.rs
> +impl pallet_preimage::Config for Runtime {
Строго говоря, preimages это не только про governance. Наш скедулер тоже ими будет потом пользоваться. Имхо, стоит переименовать модуль просто в `preimages.rs`

2023-02-21 16:59 UTC, mrshiposha commented on pallets/maintenance/src/lib.rs
> +		type RuntimeOrigin: From<RawOrigin<Self::AccountId>>
Новые типы надо загнать по feature `preimages`

2023-02-21 16:59 UTC, mrshiposha commented on runtime/common/config/pallets/mod.rs
> +#[cfg(feature = "collator-selection")]
Лучше не мешать сущности. `collactor-selection` это только про него. Давай заведем отдельный feature `preimages`.

2023-02-21 16:59 UTC, mrshiposha commented on runtime/common/config/pallets/mod.rs
> +	type RuntimeOrigin = RuntimeOrigin;
нужно загнать под feature'ы

2023-02-21 16:59 UTC, mrshiposha commented on runtime/common/construct_runtime.rs
> +                #[cfg(feature = "collator-selection")]
```suggestion
                #[cfg(feature = "preimages")]
```

И тд

2023-02-21 16:59 UTC, mrshiposha commented on runtime/common/maintenance.rs
> +				RuntimeCall::Preimage(_) => Err(TransactionValidityError::Invalid(InvalidTransaction::Call)),
Ох, демократия не сможет работать. Нам preimages нужны всегда

2023-02-21 16:59 UTC, mrshiposha commented on tests/src/pallet-presence.test.ts
> +      const governance = ['preimage'];
```suggestion
      const preimage = ['preimage'];
```

2023-02-21 16:59 UTC, mrshiposha commented on tests/src/util/identitySetter.ts
> +        await uploadPreimage(
Мб я не вижу, но ощущение, что никто эти preimage'ы не вызывает потом

2023-02-21 17:04 UTC, Fahrrader commented on tests/src/util/identitySetter.ts
> +        await uploadPreimage(
Это правда) Но в этом и суть переработки, чтобы Игорь или кто-то мог это сам вызывать позже

2023-02-21 17:06 UTC, Fahrrader commented on tests/src/pallet-presence.test.ts
> +      const governance = ['preimage'];
Сюда потом другие палеты governance пошли бы) С одной стороны, да, можно заменить, но с другой стороны, это всё больше к governance относится

2023-02-21 17:12 UTC, mrshiposha commented on tests/src/util/identitySetter.ts
> +        await uploadPreimage(
Да, я понимаю. Но в тесте, по идее, в итоге, их кто-то должен же вызвать? Или нет?)

2023-02-21 17:14 UTC, mrshiposha commented on tests/src/pallet-presence.test.ts
> +      const governance = ['preimage'];
Ну, governance еще нет, только sudo. А сейчас это-таки просто preimages. И до мейннетов preimages дойдут явно раньше демократии. Это значит, что на демократию свой feature придется городить, при живом governance :)
Поэтому лучше по прямому назначению назвать

2023-02-21 17:20 UTC, Fahrrader commented on tests/src/util/identitySetter.ts
> +        await uploadPreimage(
Но это не тест, это util-скрипт)

2023-02-21 17:22 UTC, Fahrrader commented on tests/src/util/identitySetter.ts
> +        await uploadPreimage(
Который в идеале стоит куда-нибудь перенести, но пока он здесь, и вызывается на живой чейн - тест с аналогом отдельный

2023-02-21 18:34 UTC, CertainLach commented on pallets/maintenance/src/weights.rs
> +	fn execute_preimage() -> Weight {
Можно делать наоборот, ставить вызову #[weight(Default::default())], писать бенчмарк, и потом переключать вызов на результат бенчмарка

2023-02-22 12:06 UTC, CertainLach commented on pallets/maintenance/src/lib.rs
> +		#[pallet::weight(<T as Config>::WeightInfo::execute_preimage())]
Сдача не нужна, pallet-sudo в случае успеха возвращает все деньги: https://github.com/paritytech/substrate/blob/master/frame/sudo/src/lib.rs#L188

2023-02-22 13:59 UTC, mrshiposha requested changes

2023-02-22 13:59 UTC, mrshiposha commented on pallets/maintenance/src/lib.rs
> +			let data = T::Preimages::fetch(&hash, preimage_length)?;
Нам, по-хорошему, нужно передавать не length, а именно length_bound, чтобы вычислить вес.
См. pallet-collective: https://github.com/paritytech/substrate/blob/473b5d06354c5b82e8f6df904c5f50d95c6fcc22/frame/collective/src/lib.rs#L480-L494.

Соот-но, `WeightInfo::execute_preimage` должен принимать два аргумента: length_bound и weight_bound.

2023-02-22 13:59 UTC, mrshiposha commented on pallets/maintenance/src/lib.rs
> +			let data = T::Preimages::fetch(&hash, preimage_length)?;
Примерно как здесь: https://github.com/paritytech/substrate/blob/b0ed48e2295861b79ca7399323d6d64157fa2303/frame/collective/src/benchmarking.rs#L139

2023-02-22 13:59 UTC, mrshiposha commented on runtime/common/maintenance.rs
> +				RuntimeCall::Preimage(_) => Err(TransactionValidityError::Invalid(InvalidTransaction::Call)),
Нам нельзя блокировать вызовы preimage, иначе демократия не может работать во время maintenance

2023-02-22 13:59 UTC, mrshiposha commented on tests/src/txPool.test.ts.ts
> +// Copyright 2019-2022 Unique Network (Gibraltar) Ltd.
Кажется, этот файл из другой оперы)

2023-02-22 13:59 UTC, mrshiposha commented on tests/src/util/migrateChain.ts
> +// Copyright 2019-2022 Unique Network (Gibraltar) Ltd.
Это тоже выглядит относящимся к другому PR

2023-02-22 14:11 UTC, Fahrrader commented on runtime/common/maintenance.rs
> +				RuntimeCall::Preimage(_) => Err(TransactionValidityError::Invalid(InvalidTransaction::Call)),
Так это же RuntimeCall, а демократия вызывает трейты палеты, которые не Call?

2023-02-22 14:25 UTC, Fahrrader commented on tests/src/txPool.test.ts.ts
> +// Copyright 2019-2022 Unique Network (Gibraltar) Ltd.
Упс)))

2023-02-22 14:48 UTC, mrshiposha commented on runtime/common/maintenance.rs
> +				RuntimeCall::Preimage(_) => Err(TransactionValidityError::Invalid(InvalidTransaction::Call)),
Нам нужно оставить возможность подавать новый preimage во время maintenance.
Ибо это нужно для создания пропозала на демократию (а во время maintenance нам очень нужен RootOrigin).

В будущем, чтобы ограничить законадательную инициативу во время maintenance (например, чтобы в это время Братство не могло подавать пропозалы и мешать тех обслуживанию), нужно будет подключить ManagerOrigin, который будет зависеть от состояния maintenance mode.

P.S.
Так же, когда скедулер снова будет включен -- блокировать не просто вызовы из него, а вообще останавливать обработку адженды, чтобы скедулер до preimage'й даже не добрался.

2023-02-22 15:11 UTC, CertainLach commented on pallets/maintenance/src/lib.rs
> +					actual_weight: post_info.actual_weight,
Лучше не переопределяй actual_weight
Оно важно если мы хотим возвращать деньги, однако в ином случае для неё юзкейсы сомнительные.

2023-02-22 15:43 UTC, Maksandre approved these changes

2023-02-22 21:12 UTC, CertainLach approved these changes

2023-02-22 21:58 UTC, mrshiposha approved these changes

2023-02-22 22:00 UTC, merged