feat: implement ERC721 `getApproved` for NFT.
UniqueNetwork/unique-chain pull request #897
Opened 2023-03-07 12:30 UTC by bugrazoid

2023-03-07 12:52 UTC, CertainLach requested changes

2023-03-07 12:52 UTC, CertainLach commented on pallets/nonfungible/src/erc.rs
>  	/// @dev Not implemented
Доку бы (возьми её из ERC721)

2023-03-07 12:52 UTC, CertainLach commented on tests/src/eth/nonFungible.test.ts
> +  itEth('Can perform setApproval()', async ({helper}) => {
Лучше проверку getApproved в реализацию теста approve перенести

2023-03-07 12:52 UTC, CertainLach commented on pallets/nonfungible/src/lib.rs
> +		<TokenData<T>>::iter_keys().find(
Получи data по ключу, перебор ключей будет стоить очень дофига по времени и по PoV)

2023-03-09 07:52 UTC, bugrazoid commented on pallets/nonfungible/src/lib.rs
> +		<TokenData<T>>::iter_keys().find(
Да, спасибо, чет тупанул.

2023-03-09 09:22 UTC, CertainLach commented on pallets/nonfungible/src/lib.rs
> +		ensure! {
Форматирование поправь, используй !() для вызова

2023-03-09 09:23 UTC, CertainLach commented on tests/src/eth/nonFungible.test.ts
> +  itEth.only('Can perform approve()', async ({helper}) => {
.only убрать

2023-03-09 09:23 UTC, CertainLach commented on tests/src/eth/nonFungible.test.ts
> +      const badTokenId = 1234567;
Можно произвольный, но лучше для консистентности лучше .getNonxistingTokenId используй

2023-03-09 09:26 UTC, CertainLach commented on pallets/nonfungible/src/erc.rs
> +		let token = token_id.try_into()?;
У нас же вроде теперь можно token_id: TokenId писать?

2023-03-30 07:30 UTC, CertainLach approved these changes

2023-03-30 07:31 UTC, merged