Upgrade to polkadot v0.9.39
UniqueNetwork/unique-chain pull request #899
Opened 2023-03-10 11:23 UTC by CertainLach

2023-03-10 11:24 UTC, CertainLach commented
Можно смотреть, лучше пока не сильно трогать. (Но работать оно должно)
Блочится на релизе cumulus, сейчас сделано поверх форков cumulus и ORML

2023-03-16 16:31 UTC, mrshiposha requested changes

2023-03-16 22:50 UTC, CertainLach commented on runtime/common/construct_runtime.rs
> +				// RandomnessCollectiveFlip = 31
Палета пропала из апстрима, пользователей у неё в нашей сети нет

2023-03-16 22:52 UTC, CertainLach commented on runtime/common/tests/xcm.rs
> -	xcm: &mut Xcm<RuntimeCall>,
Нет, но тут везде в пути до этой структуры был &mut [Instruction], поэтому тут  тоже тип изменил, чтобы не переупаковывать обратно в Xcm (Xcm = Vec<Instruction>)

2023-03-16 22:59 UTC, CertainLach commented on primitives/data-structs/src/lib.rs
> +		(4 * 4) * (MAX_PROPERTIES_PER_ITEM as usize) + 4
В BoundedBTreeMap MaxEncodedLen считается  как MAX_PROPS * (MAX_KEY  +  MAX_VALUE), что сейчас выходит много, а будет выходить ещё больше, если примем предложение сафта и сделаем MAX_PROPS = 255
Внимание на реализацию Properties, там я делаю MaxEncodedLen в байтах равным размеру данных  как мы подсчитали. Уменьшить MaxEncodedLen нам нужно чтобы уменьшить выхлоп бенчмарков.

Этот метод нужен чтобы размер метаданных (=размеры размеров ключей) посчитать, который в struct Properties не учитывается, и потому я просто беру худший случай отсюда (Т.к эта структура является обёрткой над BoundedBTreeMap, возможно лучше будет вынести это в отдельный метод `fn metadata_size_of(map)`)
Важно: в properties также не учитывается размер ключа, надо это исправить

2023-03-16 23:04 UTC, CertainLach commented on pallets/nonfungible/src/lib.rs
> -		OnEmpty = up_data_structs::TokenProperties,
Потому что размер переехал в генерик (для новой реализации MaxEncodedLen), и соответственно дефолтный OnEmpty нас устраивает (`Default::default()`)

2023-03-17 16:00 UTC, mrshiposha commented on primitives/data-structs/src/lib.rs
> +		(4 * 4) * (MAX_PROPERTIES_PER_ITEM as usize) + 4
Ощущение, что должно быть `(4 + 4) * (MAX_PROPERTIES_PER_ITEM as usize)`, а последняя 4 прибавляется уже позже (и вместо 4*4 использовать 4+4, не понимаю почему тут умножение).
```rust
<PropertiesMap<PropertyValue>>::metadata_encoded_len()
			+ (u32::max_encoded_len() * 2)
			+ S as usize
```

И я не понимаю почему там `* 2`...

Предлагаю вместо цифр писать, например, `(PropertyKey::max_encoded_len() + Value::max_encoded_len()) * (MAX_PROPERTIES_PER_ITEM as usize)`. Надо только навесить нужный баунд на Value.

2023-03-17 19:02 UTC, CertainLach commented on primitives/data-structs/src/lib.rs
> +		(4 * 4) * (MAX_PROPERTIES_PER_ITEM as usize) + 4
Метадата тут - размер длины строки, т.е (псевдокод) PropertyKey::max_encoded_len()::max_encoded_len()

2023-03-17 19:03 UTC, CertainLach commented on primitives/data-structs/src/lib.rs
> +		(4 * 4) * (MAX_PROPERTIES_PER_ITEM as usize) + 4
4*4 - верно, ошибка, 4 + 4

2023-03-24 08:59 UTC, CertainLach commented on runtime/common/construct_runtime.rs
> +				// RmrkCore: pallet_proxy_rmrk_core = 71,
Пусть остаётся, у нас палета контрактов там тоже есть)

2023-03-27 12:13 UTC, CertainLach commented on runtime/common/construct_runtime.rs
> +				// RmrkCore: pallet_proxy_rmrk_core = 71,
С контрактами та же ситуация, пусть живёт ещё недолго)

2023-03-29 18:47 UTC, merged