Configure astar barrier
UniqueNetwork/unique-chain pull request #905
Opened 2023-03-27 08:42 UTC by CertainLach

2023-03-29 13:48 UTC, Maksandre requested changes

2023-03-29 13:48 UTC, Maksandre commented on .docker/xcm-config/launch-config-xcm-quartz.j2
> +            "chain": "astar-dev",
```suggestion
            "chain": "shiden-dev",
```

2023-03-29 13:48 UTC, Maksandre commented on .docker/xcm-config/launch-config-xcm-quartz.j2
> +            "recipient": 1000,
```suggestion
            "recipient": 2095,
```

2023-03-29 13:48 UTC, Maksandre commented on .docker/xcm-config/launch-config-xcm-quartz.j2
> +            "sender": 1000,
```suggestion
            "sender": 2095,
```

2023-03-29 15:34 UTC, mrshiposha requested changes

2023-03-29 15:34 UTC, mrshiposha commented on .docker/Dockerfile-xcm.j2
> +COPY --from=builder-unique /unique_parachain/6validators.jsonnet /polkadot-launch/6validators.jsonnet
@CertainLach это по твоей части. Не уверен, что это надо.

2023-03-29 15:34 UTC, mrshiposha commented on .docker/xcm-config/launch-config-xcm-unique.j2
> +            "recipient": 1000,
Канала с Юником нет. Я вижу, что тут для Юника используется 2037

2023-03-29 15:34 UTC, mrshiposha commented on runtime/unique/src/xcm_barrier.rs
> +			interior: X1(Parachain(2006)),
@CertainLach если мы это смерджим раньше 39-ой Польки -- будут конфликты

2023-03-29 15:34 UTC, mrshiposha commented on .docker/xcm-config/launch-config-xcm-quartz.j2
> +            "recipient": 1000,
Тесты по Кварц без этого не должны пройти вообще, по идее. Т.к. нет канала между shiden и quartz

2023-03-29 15:34 UTC, mrshiposha commented on runtime/unique/src/xcm_barrier.rs
> +			interior: X1(Parachain(2006)),
Если мерджим раньше, то надо еще `2007` добавить -- для shiden

2023-03-29 15:34 UTC, mrshiposha commented on tests/src/util/index.ts
> +export const usingAstarPlaygrounds = (url: string, code: (helper: DevAstarHelper, privateKey: (seed: string) => Promise<IKeyringPair>) => Promise<void>) => {
Хорошо бы добавить отдельную функцию для Shiden. Это нужно на случай, если эти рантаймы разойдутся. Такое уже было с Мунбимом -- ненадолго Мунривер и Мунбим разошлись и отличались достаточно сильно

2023-03-29 15:34 UTC, mrshiposha commented on tests/src/xcm/xcmQuartz.test.ts
> +      alice = await privateKey('//Alice');
Не уверен, что мы в других местах пользуем Алису...
Там какой-то донор специальный вроде :/

2023-03-29 15:34 UTC, mrshiposha commented on tests/src/xcm/xcmQuartz.test.ts
> +      console.log('1. Create foreign asset and metadata');
```suggestion
      console.log('1. Create foreign asset and metadata on Shiden');
```

2023-03-29 15:34 UTC, mrshiposha commented on tests/src/xcm/xcmQuartz.test.ts
> +      await helper.assets.create(
Надо TODO добавить, чтобы в будущем заменить значения здесь на те, что будут на проде у Shiden

2023-03-29 15:34 UTC, mrshiposha commented on tests/src/xcm/xcmQuartz.test.ts
> +      await helper.assets.create(
А лучше выяснить какие они точно будут

2023-03-29 15:34 UTC, mrshiposha commented on tests/src/xcm/xcmQuartz.test.ts
> +        1,
Добавь, плиз именованную константу, не сразу понял, что это QTZ_ASSET_ID_ON_SHIDEN

2023-03-29 15:34 UTC, mrshiposha commented on tests/src/xcm/xcmQuartz.test.ts
> +        1n,
Добавь, плиз, именованную константу QTZ_MINIMAL_BALANCE_ON_SHIDEN

Не настаиваю на конкретном нейминге, можно любое совместимое имя

2023-03-29 15:34 UTC, mrshiposha commented on tests/src/xcm/xcmQuartz.test.ts
> +        1,
Именованная константа assetId

2023-03-29 15:34 UTC, mrshiposha commented on tests/src/xcm/xcmQuartz.test.ts
> +        18,
Именованная константа decimals

2023-03-29 15:34 UTC, mrshiposha commented on tests/src/xcm/xcmQuartz.test.ts
> +      console.log('2. Register asset location');
```suggestion
      console.log('2. Register asset location on Shiden');
```

2023-03-29 15:34 UTC, mrshiposha commented on tests/src/xcm/xcmQuartz.test.ts
> +      await helper.getSudo().executeExtrinsic(alice, 'api.tx.xcAssetConfig.registerAssetLocation', [assetLocation, 1]);
Замени везде голые числа на именованные константы. 
Тут я имею в виду единичку в конце, которая означает assetId

2023-03-29 15:34 UTC, mrshiposha commented on tests/src/xcm/xcmQuartz.test.ts
> +      console.log('3. Set payment for computation');
```suggestion
      console.log('3. Set QTZ payment for XCM execution on Shiden');
```

2023-03-29 15:34 UTC, mrshiposha commented on tests/src/xcm/xcmQuartz.test.ts
> +      // TODO this is Phala's price, what price will be for Unique?
Согласен TODO-шкой. Но надо бы еще напрямую Астар спросить об этом.

2023-03-29 15:34 UTC, mrshiposha commented on tests/src/xcm/xcmQuartz.test.ts
> +      console.log('4. Transfer 1 SDN to recepient');
```suggestion
      console.log('4. Transfer 1 SDN to recipient to create the account (needed due to existential balance)');
```

2023-03-29 15:34 UTC, mrshiposha commented on tests/src/xcm/xcmQuartz.test.ts
> +      V1: {
Нам надо будет все это заменить на V2, но это будет нормально работать только после обновления Польки

2023-03-29 15:34 UTC, mrshiposha commented on tests/src/xcm/xcmQuartz.test.ts
> +      const xcUNQbalance = await helper.assets.account(1, randomAccount.address);
Снова единичка сбивает с толку. Нужна именованная константа assetId

2023-03-29 15:34 UTC, mrshiposha commented on tests/src/xcm/xcmQuartz.test.ts
> +              Fungible: 5_000_000_000_000_000_000n,
Сходу не понимаю сколько это кварцев :)
Мб как-то так? `5 * (10 ** 18)`

2023-03-29 15:34 UTC, mrshiposha commented on tests/src/xcm/xcmQuartz.test.ts
> +      await helper.executeExtrinsic(randomAccount, 'api.tx.polkadotXcm.reserveWithdrawAssets', [destination, beneficiary, assets, feeAssetItem]);
Добавь, плиз, комментарий, что этот экстринзик -- нестандартное расширение polkadotXcm для Астара. Этот экстринзик в итоге вызывает XCM команду `InitiateReserveWithdraw`

2023-03-29 15:34 UTC, mrshiposha commented on tests/src/xcm/xcmQuartz.test.ts
> +      expect(balanceSDN / (10n ** 15n)).to.eq(996n);
Все `decimals`бы в константу вынести...

2023-03-29 15:34 UTC, mrshiposha commented on tests/src/xcm/xcmQuartz.test.ts
> +      // Assert: xcQTZ balance decreased
```suggestion
      // Assert: xcQTZ balance correctly decreased
```

2023-03-29 15:34 UTC, mrshiposha commented on tests/src/xcm/xcmQuartz.test.ts
Я бы добавил еще логов, как в других тестах.
Что ушло, что пришло и где.

Это очень помогает отлаживаться, если вдруг чего

2023-03-29 15:34 UTC, mrshiposha commented on tests/src/xcm/xcmUnique.test.ts
Все аналогично комментариям по тесту Кварца

2023-03-29 17:25 UTC, mrshiposha requested changes

2023-03-29 17:25 UTC, mrshiposha commented on .env
> +SHIDEN_BUILD_BRANCH=v4.49.0
Точно такой рантайм сейчас на проде Шиден?

2023-03-29 17:25 UTC, mrshiposha commented on tests/src/xcm/xcmQuartz.test.ts
> +  const shidenInitialBalance = 1n * (10n ** 18n); // 1 SHD, existencial deposit required in order to perform XCM call
```suggestion
  const shidenInitialBalance = 1n * (10n ** 18n); // 1 SHD, existential deposit required to actually create the account on Shiden.
```

2023-03-29 17:25 UTC, mrshiposha commented on tests/src/xcm/xcmQuartz.test.ts
> +      expect(balanceSDN / (10n ** 15n)).to.eq(996n);
Я имел в виду заменить все штуки вида (n ** 18n) или (n ** 15n) на что-то вроде (n ** DECIMALS)

2023-03-29 18:43 UTC, Maksandre commented on .docker/xcm-config/launch-config-xcm-unique.j2
> +            "recipient": 1000,
Поправил

2023-03-29 18:43 UTC, Maksandre commented on .env
> +SHIDEN_BUILD_BRANCH=v4.49.0
Да

2023-03-30 08:55 UTC, Maksandre commented on tests/src/xcm/xcmQuartz.test.ts
> +  const shidenInitialBalance = 1n * (10n ** 18n); // 1 SHD, existencial deposit required in order to perform XCM call
Исправил, спасибо

2023-03-30 09:43 UTC, Maksandre commented on tests/src/xcm/xcmQuartz.test.ts
> +      expect(balanceSDN / (10n ** 15n)).to.eq(996n);
Вынес. Оставил только 10n ** 15n для того, чтобы точнее сравнивать баланс Астар после взятия комиссии. Можно просто сравнивать, что баланс уменьшился, так как не наша зона ответственности. Как обойтись без магических чисел по другому, я не придумал

2023-03-30 09:43 UTC, Maksandre approved these changes

2023-03-30 14:22 UTC, mrshiposha commented on tests/src/xcm/xcmQuartz.test.ts
> +      expect(balanceSDN / (10n ** 15n)).to.eq(996n);
Ну, можно воткнуть `SHIDEN_DECIMALS`. Но да ладно

2023-03-30 15:00 UTC, Maksandre commented on tests/src/xcm/xcmQuartz.test.ts
> +      expect(balanceSDN / (10n ** 15n)).to.eq(996n);
Нет, это не SHIDEN_DECIMALS. Это просто сокращение до 3 знаков после запятой. Можно было бы сделать `SHIDEN_DECIMALS - 3`, но будет ли понятнее?

2023-03-30 15:02 UTC, Maksandre commented on tests/src/xcm/xcmQuartz.test.ts
> +      await helper.assets.create(
Астар сказали, что посчитают по своей формуле, т.е. узнаем постфактум. TODO добавил

2023-03-30 18:24 UTC, mrshiposha approved these changes

2023-03-30 18:54 UTC, merged