feat: add crossBalanceOf
UniqueNetwork/unique-chain pull request #919
Opened 2023-04-17 08:19 UTC by bugrazoid

2023-04-17 09:10 UTC, CertainLach approved these changes
Думаю что стоит добавить ещё этот же метод в fungible и соответственно rft токен

2023-04-17 09:32 UTC, CertainLach commented on pallets/nonfungible/src/erc.rs
> +	/// @dev NFTs assigned to the zero address are considered invalid, and this
Также стоит убрать этот комментарий, поскольку CrossAddress не поддерживает нулевые адреса

2023-04-18 07:39 UTC, uandysmith requested changes

2023-04-18 07:39 UTC, uandysmith commented on tests/src/eth/fungible.test.ts
> +    for (let i = 1n; i < 100n; i++) {
По всем тестам у тебя выходит 6 раз по 100n,  это куча транзакций (т.к. где-то внутри цикла их две), тесты будут идти очень долго. 
Здесь лучше более простую проверку добавить - перекинуть часть баланса (не весь) на другого пользователя и посмотреть, что балансы и у оригинала и у нового владельца соответствуют ожиданиям. Потом баланс можно вернуть оригиналу и убедиться, что он снова полный, а у донора больше нет ни одной части. 
Этого должно быть достаточно и без циклов

2023-04-18 10:44 UTC, uandysmith commented on tests/src/eth/fungible.test.ts
> +    expect(BigInt(await collectionEvm.methods.balanceOfCross(other).call({from: owner.eth})) === 0n).to.be.true;
to.be.equal даже можно

2023-04-18 11:09 UTC, CertainLach commented on tests/src/eth/fungible.test.ts
> +    expect(BigInt(await collectionEvm.methods.balanceOfCross(other).call({from: owner.eth})) === 0n).to.be.true;
Да, это будет сильно лучше

2023-04-18 12:37 UTC, CertainLach approved these changes

2023-04-18 14:07 UTC, uandysmith requested changes

2023-04-18 14:07 UTC, uandysmith commented on tests/src/eth/nonFungible.test.ts
> +    for (let i = 1n; i < 100n; i++) {
Остались же циклы. Это 200 транзакций или 2400 секунд.

2023-04-18 14:07 UTC, uandysmith commented on tests/src/eth/reFungible.test.ts
> +    for (let i = 1n; i < 100n; i++) {
И тут тоже 200 транзакций

2023-04-19 08:05 UTC, merged