fix: unused `on_runtime_upgrade()` was removed
UniqueNetwork/unique-chain pull request #920
Opened 2023-04-19 11:50 UTC by PraetorP

- AppPromo
- Common
- NonFungible

2023-04-19 11:52 UTC, CertainLach requested changes

2023-04-19 11:52 UTC, CertainLach commented on pallets/common/src/lib.rs
> -			StorageVersion::new(1).put::<Pallet<T>>();
Это нужно переместить в GenesisConfig, чтобы у чейна из спеки по дефолту стояла первая версия хранилища

2023-04-19 11:52 UTC, CertainLach commented on pallets/nonfungible/src/lib.rs
> -			StorageVersion::new(1).put::<Pallet<T>>();
Нужен GenesisConfig

2023-04-20 04:56 UTC, PraetorP commented on pallets/common/src/lib.rs
> +	impl<T: Config> Default for GenesisConfig<T> {
Есть проблема с неккоретным определением ограничений в дерайв (https://github.com/rust-lang/rust/issues/26925). В данном случае, он также требует `T: Default`.
Видимо по этой причине парити так же делает это явно: 
https://sourcegraph.com/github.com/paritytech/substrate/-/blob/frame/sudo/src/lib.rs?L282

2023-04-20 08:56 UTC, CertainLach approved these changes

2023-04-20 08:57 UTC, merged