[WIP] Update polkadot to v0.9.42
UniqueNetwork/unique-chain pull request #934
Opened 2023-05-15 11:36 UTC by CertainLach

2023-05-24 13:53 UTC, CertainLach commented on pallets/foreign-assets/src/impl_fungibles.rs
> +	// This function does not exists, thus compilation will fail, if its call is
Linking*, компиляция успешно пройдёт.

Это тот костыль о котором я говорил, его я предлагаю использовать и в релизе, если кто-то ещё согласен со мной в том, что это хорошее решение нашей проблемы

@mrshiposha WDYT?

2023-05-31 09:43 UTC, CertainLach commented on pallets/app-promotion/src/lib.rs
> +						Self::set_freeze_unchecked(&staker, new_state);
К вызовам set_freeze_unchecked нужен бы комментарий, почему оно не может провалиться

2023-05-31 09:43 UTC, CertainLach commented on pallets/app-promotion/src/lib.rs
> +		// fn on_runtime_upgrade() -> Weight {
Убрать?

2023-05-31 09:44 UTC, CertainLach commented on pallets/app-promotion/src/lib.rs
> +		Self::set_freeze_with_result(staker, amount);
```suggestion
		let _ = Self::set_freeze_with_result(staker, amount);
```

2023-05-31 09:55 UTC, CertainLach commented on runtime/common/config/substrate.rs
> +	pub const MigrationMaxKeyLen: u32 = 512;
Ключей длинные 512 байт у нас достаточно, однако мне кажется что хорошим планом миграции было бы в одном релизе быстро мигрировать все мелкие ключи и :code (Этот ключ мигрирует сам при обновлении), а длинные ключи в следующем релизе отдельно потрогать.

Не беда если не сразу все ключи мигрируем, нода будет работать в гибридном режиме ещё долго из-за реле.

2023-05-31 09:56 UTC, CertainLach commented on runtime/common/config/substrate.rs
> +	pub const MigrationMaxKeyLen: u32 = 512;
Мой консерн заключается в том, что если мигрировать ключи большими пачками, то у нас может в одну пачку попасть слишком много длинных ключей.

2023-05-31 12:51 UTC, PraetorP commented on pallets/collator-selection/src/tests.rs
> +	traits::{fungible, GenesisBuild, OnInitialize},
В тестах вроде бы используется только `fungible::Mutate`. Может явно его здесь указать? 
```suggestion
	traits::{fungible::Mutate as MutateFungible, GenesisBuild, OnInitialize},
```

2023-05-31 13:03 UTC, PraetorP commented on pallets/app-promotion/src/lib.rs
> +		// fn on_runtime_upgrade() -> Weight {
Убрал. И еще ниже тоже было нечто подобное - теперь нет.

2023-06-01 15:10 UTC, CertainLach commented on pallets/collator-selection/src/tests.rs
> +	traits::{fungible, GenesisBuild, OnInitialize},
А какая разница, fungible::Mutate, или MutateFungible? Мне кажется что первый вариант лучше

2023-06-01 15:57 UTC, mrshiposha requested changes

2023-06-01 15:57 UTC, mrshiposha commented on pallets/nonfungible/src/lib.rs
> +		+ pallet_balances::Config
Не вижу причины добавления зависимости на balances

2023-06-01 16:08 UTC, mrshiposha requested changes

2023-06-01 22:43 UTC, CertainLach commented on runtime/common/config/substrate.rs
> +	type DustRemoval = ();
Пыли у нас пока нет, т.к ED = 0, к слову. Но если будет не 0 - то нужно исправить

2023-06-02 05:49 UTC, PraetorP commented on pallets/app-promotion/src/lib.rs
> +					<= match Self::get_frozen_balance(&staker_id) {
Да, это преднамеренное поведение. чтобы ты мог, например, стекать деньги залоченные вестингом.

2023-06-02 06:21 UTC, PraetorP commented on runtime/tests/src/lib.rs
> +	type CurrencyBalance = <Balances as Currency<Self::AccountId>>::Balance;
В тестах оставляем Currency?

2023-06-02 12:21 UTC, CertainLach commented on pallets/nonfungible/src/lib.rs
> +		+ pallet_balances::Config
Она видимо осталась от перечисления детей в нативных балансах

2023-06-02 12:49 UTC, mrshiposha requested changes

2023-06-02 12:50 UTC, mrshiposha commented on pallets/collator-selection/src/tests.rs
> +	traits::{fungible, GenesisBuild, OnInitialize},
Parity у себя повсюду пишет fungible::Mutate. Имхо, лучше сделать по аналогии

2023-06-02 12:53 UTC, mrshiposha commented on pallets/nonfungible/src/lib.rs
> +		+ pallet_balances::Config
Ага, надо бы убрать. Сейчас необходимости в ней не видно, испольваний нет

2023-06-02 13:57 UTC, CertainLach commented on tests/src/eth/collectionSponsoring.test.ts
> +    // FIXME: doesn't work
Там все подобные рядом с выдачей балансов излишние, т.к эти вызовы должны вовсе бесплатно проходить, я их все уберу после исправления во frontier.

2023-06-02 13:58 UTC, CertainLach commented on tests/src/eth/collectionSponsoring.test.ts
> +    // FIXME: doesn't work
Я помечу все аналогичные комментарии как resolved, т.к это не является блокером для этого PR, но блочит релиз.

2023-06-02 13:59 UTC, CertainLach commented on tests/src/eth/nativeRpc/estimateGas.test.ts
> +  itEth.skip('estimate gas', async ({helper}) => {
Этот тест изначально написан как не проходящий, с обновлением frontier будет исправлено.

2023-06-02 13:59 UTC, CertainLach commented on tests/src/eth/util/playgrounds/unique.dev.ts
> +      abi = nativeFungibleAbi;
Там нет collection properties и прочего.

2023-06-02 14:01 UTC, CertainLach commented on tests/src/util/playgrounds/unique.ts
> +export class CrossAccountId {
ICrossAccountId всё ещё интерфейс, а в class CrossAccountId несколько хелперов для преобразования.
Впрочем, мне тоже не совсем понятно зачем нам в типах иметь несколько разных описаний CrossAccountId)

2023-06-05 06:19 UTC, PraetorP commented on tests/src/sub/appPromotion/appPromotion.test.ts
> +    itSub.skip('should allow to stake() if balance is locked with different id', async ({helper}) => {
пока вестинг не станет фризить - смысла в этом тесте особо нет.

2023-06-05 09:33 UTC, mrshiposha commented on tests/src/sub/appPromotion/appPromotion.test.ts
> +    itSub.skip('should allow to stake() if balance is locked with different id', async ({helper}) => {
Мб тогда TODO оставить? Когда вестинг поумнеет.

@CertainLach а при обновлении ORML на 42 польку вестинг не поумнел?

2023-06-05 09:34 UTC, mrshiposha commented on tests/src/sub/appPromotion/appPromotion.test.ts
> +    itSub.skip('should allow to stake() if balance is locked with different id', async ({helper}) => {
я имею в виду к комменту в начале добавить просто "TODO".

2023-06-05 16:12 UTC, CertainLach commented on tests/src/util/playgrounds/unique.ts
> +export class CrossAccountId {
Интерфейс и тип суть одно и то же, просто с интерфейсом работает implements, а с типами можно делать discriminated union

2023-06-05 16:15 UTC, CertainLach commented on pallets/collator-selection/src/tests.rs
> +	traits::{fungible, GenesisBuild, OnInitialize},
Квалифицированное большинство за вариант парити, резолвлю)

2023-06-06 08:02 UTC, mrshiposha commented on tests/src/util/playgrounds/unique.ts
> +export class CrossAccountId {
Но по использованию теперь, похоже, они используются одинаково... Обычный `CrossAccountId` выглядит лишним. Можно было бы оставить толькой `ICrossAccountId`

2023-06-07 09:32 UTC, merged