Add test for market v2 deployment
UniqueNetwork/unique-chain pull request #942
Opened 2023-05-30 21:31 UTC by fairax

2023-05-31 02:50 UTC, uandysmith requested changes

2023-05-31 02:50 UTC, uandysmith commented on tests/package.json
> -    "chai-as-promised": "^7.1.1",
У нас от этого точно ничего не сломается? Он используется в `utils/index.ts` вроде как, по крайней мере раньше

2023-05-31 02:50 UTC, uandysmith commented on tests/src/eth/marketplace-v2/marketplace.test.ts
> +  itEth('Deploy', async ({helper}) => {
Давай добавим минимальный тест-кейс помимо деплоя. Вызываем put и buy, чтобы убедиться что контракт не только деплоится, но и работает хотя бы минимально

2023-05-31 06:03 UTC, fairax commented on tests/package.json
> -    "chai-as-promised": "^7.1.1",
хмм, видимо при мёрже удалилось, сейчас поправлю

2023-06-02 09:16 UTC, uandysmith approved these changes

2023-06-07 11:57 UTC, CertainLach approved these changes

2023-06-07 12:25 UTC, merged