Token data for old runtimes
UniqueNetwork/unique-chain pull request #957
Opened 2023-06-20 07:05 UTC by fairax

2023-06-26 08:06 UTC, CertainLach requested changes

2023-06-26 08:06 UTC, CertainLach commented on client/rpc/src/lib.rs
> +	let _api_version = if let Ok(Some(api_version)) =
Переименуй в api_version (без _)

2023-06-26 08:06 UTC, CertainLach commented on client/rpc/src/lib.rs
> +						properties: Vec::new(),
Мы же вроде договорились, что легаси const_metadata/variable_metadata будем поддерживать?

2023-06-27 07:10 UTC, fairax commented on client/rpc/src/lib.rs
> +						properties: Vec::new(),
Договорились сделать для начала так, а потом подумать надо ли делать дальше, на сколько я помню. Андрей сказал, что этого достаточно.

2023-06-27 11:01 UTC, CertainLach commented on primitives/rpc/src/lib.rs
> +		//TODO: check if this is correct. Attribute in TokenData says that it was changed in since version 2
Версии структур и версии rpc не связаны, версия структуры поднималась для хранилища.

2023-06-27 11:02 UTC, CertainLach approved these changes
Ну и кроме последних двух комментариев всё ок, можно принимать.

2023-06-28 08:07 UTC, merged