Feature/rebase democracy
UniqueNetwork/unique-chain pull request #965
Opened 2023-07-10 09:04 UTC by PraetorP

2023-07-10 09:26 UTC, mrshiposha commented on pallets/maintenance/src/lib.rs
> +			T::ManagerOrigin::ensure_origin(origin)?;
Это точно должен быть другой origin, не manager. Потому что тех. коммитет будет иметь возможность включать/выключать maintenance, но **ни в коем случае** не может исполнять код от Root Origin

2023-07-10 11:27 UTC, mrshiposha commented on runtime/common/config/xcm/mod.rs
> +	type ControllerOrigin = governance::RootOrAllTechnicalCommittee;
Здесь нужно использовать MemberOrigin. Любой член тех. коммитета должен иметь возможность остановить XCM (это согласно документу по gov)

2023-07-10 11:27 UTC, mrshiposha commented on runtime/quartz/Cargo.toml
> +quartz-runtime = ['app-promotion', 'collator-selection', 'foreign-assets', 'governance', 'preimage', 'refungible']
В Кварце это пока включать не надо

2023-07-10 11:27 UTC, mrshiposha commented on tests/src/maintenance.seqtest.ts
> +        preimageHashes.push(await helper.preimage.notePreimage(bob, preimage, true));
Хмм, по идее это не должно отличаться от текущего develop?

2023-07-10 11:27 UTC, mrshiposha commented on tests/src/maintenance.seqtest.ts
> +      const preimageHash = await helper.preimage.notePreimage(bob, preimage, true);
И это, по идее, тоже не должно отличаться от текущего develop

2023-07-10 11:27 UTC, mrshiposha commented on tests/src/util/index.ts
> +  //CouncilMembership = 'councilmembership',
Не помню почему это закомментировано

2023-07-10 12:25 UTC, uandysmith commented on runtime/quartz/Cargo.toml
> +quartz-runtime = ['app-promotion', 'collator-selection', 'foreign-assets', 'governance', 'preimage', 'refungible']
Надо, в 60-ом sapphire и quartz сразу

2023-07-19 13:13 UTC, mrshiposha requested changes

2023-07-20 02:03 UTC, PraetorP commented on runtime/common/construct_runtime.rs
> +				#[cfg(feature = "governance")]
Вообще я делал `cargo fmt --all`. Странно

2023-07-20 02:05 UTC, PraetorP commented on runtime/common/config/pallets/governance/types.rs
> +			1u16,
Тогда никто из братсва не сможет делать пропозалы ... Может обсудим ? В будущем да - можно .

2023-07-21 11:13 UTC, mrshiposha requested changes

2023-07-21 11:13 UTC, mrshiposha commented on runtime/common/config/pallets/governance/types.rs
> +	TryMapSuccess<pallet_ranked_collective::EnsureRanked<T, I, 5>, CheckedReduceBy<ConstU16<1>>>,
Не сделано

2023-07-21 11:13 UTC, mrshiposha commented on runtime/common/config/pallets/governance/types.rs
> +			Ok(_) => Ok(1),
```suggestion
			Ok(_) => Ok(DEMOCRACY_TRACK_ID),
```

2023-07-21 11:13 UTC, mrshiposha commented on runtime/common/construct_runtime.rs
> +				#[cfg(feature = "governance")]
Все опять съехало. Пожалуйста, замени на пробелы

2023-07-21 14:12 UTC, mrshiposha commented on runtime/common/config/pallets/governance/technical_committee.rs
> +pub type FellowshipCollective = pallet_ranked_collective::Pallet<Runtime>;
~~Шпион из Fellowship :)~~ Это вообще надо?

2023-07-21 14:13 UTC, mrshiposha commented on runtime/common/config/pallets/governance/fellowship.rs
> +	MapSuccess<CouncilMember, Replace<ConstU16<9>>>,
```suggestion
	MapSuccess<RootOrAllCouncil, Replace<ConstU16<9>>>,
```

2023-08-11 15:57 UTC, mrshiposha requested changes

2023-08-11 15:57 UTC, mrshiposha commented on tests/src/governance/council.test.ts
> +  async function proposalFromCouncil(proposal: any) {
```suggestion
  async function proposalFromAllCouncil(proposal: any) {
```

2023-08-11 15:57 UTC, mrshiposha commented on tests/src/governance/council.test.ts
> +    const [newMember] = await helper.arrange.createAccounts([0n], donor);
Я видел у нас добавился специальный метод для создания пустых акков. Наверное, его здесь использовать будет хорошо. В других похожих местах, думаю, тоже.

2023-08-11 15:57 UTC, mrshiposha commented on tests/src/governance/council.test.ts
> +  itSub('50%> Council can add TechComm member', async ({helper}) => {
Для консистентности. У нас в других местах знак "больше" идет раньше.

```suggestion
  itSub('>50% Council can add TechComm member', async ({helper}) => {
```

2023-08-11 15:57 UTC, mrshiposha commented on tests/src/governance/council.test.ts
> +    await expect(helper.getSudo().executeExtrinsic(sudoer, 'api.tx.councilMembership.addMember', [newMember.address])).to.be.fulfilled;
У нас есть в плейграундах класс, который предоставляет методы для работы с membership. Там есть методы `addMember/getMembers` и прочие. Лучше использовать их, а не напрямую дергать executeExtrinsic. Во всех похожих местах.

2023-08-11 15:57 UTC, mrshiposha commented on tests/src/governance/council.test.ts
> +    await expect(proposalFromCouncil(councilProposal)).to.be.rejectedWith('Proposal execution failed with BadOrigin');
Такие reject'ы у нас в других тестах обычно ловяться по regex'у:

```suggestion
    await expect(proposalFromCouncil(councilProposal)).to.be.rejectedWith(/BadOrigin/);
```

2023-08-11 15:57 UTC, mrshiposha commented on tests/src/governance/council.test.ts
> +  itSub('[Negative] Cannot add a duplicate Council member', async ({helper}) => {
Не уверен, что нам вообще нужен этот тест-кейс. Мы тут тестируем логику (которая написана не нами, а Парити), а не нашу настройку.

То же самое относится к другим тестам про мемберов-дубликатов

2023-08-11 15:57 UTC, mrshiposha commented on tests/src/governance/council.test.ts
> +    await expect(helper.council.membership.addMember(counselors.alex, newCouncilMember.address)).to.be.rejectedWith('BadOrigin');
Council Member (как и TechComm Member) -- это особенный origin соот-го коллектива, а не обычные signed origin'ы, соот-но, не смотря на то, что тест проходит, он тестирует не то, что нужно.

В данном случае, этот тест тестирует, что обычный signed-origin не может добавить/убрать советника. А нам нужное другое.

Здесь и в других "Council member" тестах нужно использовать экстринзик `council.execute`.

Для TechComm -- аналогично

2023-08-14 03:38 UTC, PraetorP commented on tests/src/governance/council.test.ts
> +    await expect(helper.council.membership.addMember(counselors.alex, newCouncilMember.address)).to.be.rejectedWith('BadOrigin');
То, что у них там как раз не совсем корректно (имхо) сделан адаптер Еншюр мамбер, я как раз заметил в тех ком. Тут не правил еще - поскольку решил это сделать после реализации тестов.

2023-08-14 03:39 UTC, PraetorP commented on tests/src/governance/council.test.ts
> +    await expect(proposalFromCouncil(councilProposal)).to.be.rejectedWith('Proposal execution failed with BadOrigin');
Не только. Можно просто строкой

2023-08-14 06:28 UTC, uandysmith commented on tests/src/governance/council.test.ts
> +  itSub('[Negative] Cannot add a duplicate Council member', async ({helper}) => {
Да, поддерживаю, давайте уберем. 
Итак слишком долго идут тесты

2023-08-14 11:54 UTC, mrshiposha commented on tests/src/governance/council.test.ts
> +    await expect(proposalFromCouncil(councilProposal)).to.be.rejectedWith('Proposal execution failed with BadOrigin');
Можно, но `/BadOrigin/` покрывает вообще все случаи. В других тестах (не только governance) как правило используется именно такой вариант

2023-08-14 14:54 UTC, mrshiposha requested changes

2023-08-14 14:54 UTC, mrshiposha commented on tests/src/governance/technicalCommittee.test.ts
> +  itSub('[Negative] TechComm member cannot blacklist Democracy proposals', async ({helper}) => {
Надо бы еще добавить тест, что коммитет целиком НЕ может блеклистить. Я такого теста не вижу.
(Может только Совет)

2023-08-14 14:54 UTC, mrshiposha commented on tests/src/governance/technicalCommittee.test.ts
> +  itSub('[Negative] TechComm member cannot propose an existing TechComm proposal', async ({helper}) => {
Это логика Парити

2023-08-14 14:54 UTC, mrshiposha commented on tests/src/governance/technicalCommittee.test.ts
> +  itSub('[Negative] TechComm non-member cannot propose', async ({helper}) => {
Логика Парити

2023-08-14 14:54 UTC, mrshiposha commented on tests/src/governance/technicalCommittee.test.ts
> +  itSub('[Negative] TechComm non-member cannot vote', async ({helper}) => {
Логика Парити

2023-08-14 15:49 UTC, CertainLach commented on tests/src/governance/council.test.ts
> +    await expect(proposalFromCouncil(councilProposal)).to.be.rejectedWith('Proposal execution failed with BadOrigin');
Строка тоже вхождение проверяет а не полное совпадение
Регулярки есть смысл использовать только для проверки полной ошибки: /^section.BadOrigin$/

2023-08-15 12:03 UTC, PraetorP commented on tests/src/governance/council.test.ts
> +      helper.technicalCommittee.membership.removeMemberCall(counselors.charu.address),
Вообще без разницы кого - мы смотрим, что это упадет с `BadOrigin` а не с какой либо другой ошибкой, тест не про то, что не можем удалить несуществующего мембера.

2023-08-18 08:36 UTC, CertainLach requested changes

2023-08-18 08:36 UTC, CertainLach commented on runtime/common/config/pallets/governance/scheduler.rs
> +	pub MaximumSchedulerWeight: Weight = Perbill::from_percent(80) * <Runtime as frame_system::Config>::BlockWeights::get().max_block;
Кажется мне что тут стоит базироваться не на всём блоке, а на нормальных транзакциях, может тут стоит использовать normal rate/идти через per_class(normal)?

2023-08-18 13:46 UTC, PraetorP commented on runtime/common/config/pallets/governance/fellowship.rs
> +			other => sp_runtime::traits::Identity::convert(other),
Наш с Даниилом высокий стиль не понравился )

2023-08-22 08:15 UTC, CertainLach commented on .github/workflows/gov.yml
> +          # TODO: Remove state-version-0 after mainnet upgrade
Комментарий можно убрать, тут же не включена эта фича

2023-08-22 08:27 UTC, CertainLach commented on runtime/unique/src/governance_timings.rs
> +			pub const CONFIRM_PERIOD: BlockNumber = 30 * MINUTES;
У кварца увеличили до 2х, а у других сетей нет, может стоит переиспользовать тайминги? В common их вынести например

2023-08-22 08:32 UTC, CertainLach commented on pallets/gov-origins/Cargo.toml
> +codec = { workspace = true, package = "parity-scale-codec" }
Макросы фрейма ищут parity-scale-codec, они просто принимают его и в качестве названия, и в качестве пакета
И когда мы передаём в качестве названия пакета, нам не хватает указать это название в воркспейсе, макросы использующие Codec не умеют работать с воркспейсами

2023-08-22 08:34 UTC, CertainLach commented on pallets/gov-origins/Cargo.toml
> +codec = { workspace = true, package = "parity-scale-codec" }
В репах субстрата и polkadot тоже потихоньку переходит

2023-08-22 10:04 UTC, PraetorP commented on runtime/unique/src/governance_timings.rs
> +			pub const CONFIRM_PERIOD: BlockNumber = 30 * MINUTES;
Потенциально, тайминги у сетей могут отличаться.

2023-08-23 09:03 UTC, merged