Update polkadot to v0.9.43
UniqueNetwork/unique-chain pull request #968
Opened 2023-07-17 08:07 UTC by CertainLach

2023-07-17 08:20 UTC, CertainLach commented on runtime/common/config/ethereum.rs
> +	pub const ProofSizePerGas: u64 = 0; //WEIGHT_REF_TIME_PER_SECOND / GasPerSecond::get();
Такая простая формула тут не работает по разным причинам, нормальная токеномика будет проставлена после разбирательств с frontier

2023-08-14 10:47 UTC, mrshiposha requested changes

2023-08-14 10:47 UTC, mrshiposha commented on node/cli/src/service.rs
> +				// eth_backend,
?

2023-08-14 10:47 UTC, mrshiposha commented on node/cli/src/service.rs
> +			Duration::new(6, 0),
Это как-то связано с временем создания блока? Если да, то почему это не 12?

2023-08-14 10:47 UTC, mrshiposha commented on node/cli/src/service.rs
> +			0,
Что это за значения?

2023-08-14 10:47 UTC, mrshiposha commented on pallets/configuration/src/lib.rs
> +			// This code should not be called in production, but why keep development in the
>but why keep development

Мб имелось в виду "we keep"? Ибо это не звучит как вопрос.

2023-08-14 10:47 UTC, mrshiposha commented on runtime/common/config/ethereum.rs
>  // ~~Assuming slowest ethereum opcode is SSTORE, with gas price of 20000 as our worst case~~
Коль это "very wrong", то мб еще отдельно скажем, что это TODO и будет сделано "тогда-то"

2023-08-14 10:47 UTC, mrshiposha commented on runtime/common/runtime_apis.rs
> +                        None,
Что это за параметры?

2023-08-14 10:51 UTC, CertainLach commented on runtime/common/runtime_apis.rs
> +                        None,
Рантайм апи и TODO тут копипаста с шаблона frontier

Параметры отвечают за запись внешней стоимости (вес), что на данный момент в rpc не поддерживается и не используется.

2023-08-14 10:53 UTC, CertainLach commented on pallets/configuration/src/lib.rs
> +			// This code should not be called in production, but why keep development in the
Это вопрос, просто риторический)

2023-08-14 10:53 UTC, CertainLach commented on pallets/configuration/src/lib.rs
> +			// This code should not be called in production, but why keep development in the
Why?
Why not?

2023-08-14 10:56 UTC, CertainLach commented on node/cli/src/service.rs
> +			Duration::new(6, 0),
Это со временем создания блока, однако тут таймер не синхронизирован, как и финализация в целом
6 секунд позволяют ускорить получение ответов от web3.js значительно в некоторых случаях (иначе в худшем случае ответ может приходить через 11.9 секунд после финализации условно)

Такое же значение ставят все эфирные чейны

2023-08-14 10:58 UTC, CertainLach commented on Cargo.toml
> +evm-core = { git = "https://github.com/rust-blockchain/evm", rev = "b7b82c7e1fc57b7449d6dfa6826600de37cc1e65", default-features = false }
Оно так в апстриме frontier, нужные для фронтира правки пока не приняли

2023-08-14 10:59 UTC, CertainLach commented on .env
>  MOONBEAM_BUILD_BRANCH=runtime-2302
.env перегенерирую в обновлении Ci, на данной ветке оно не полностью живое в любом случае.

2023-08-14 11:17 UTC, mrshiposha commented on pallets/configuration/src/lib.rs
> +			// This code should not be called in production, but why keep development in the
А кто знает ответ?)
Чет не пойму что тут к чему :D

2023-08-14 11:19 UTC, mrshiposha commented on runtime/common/config/ethereum.rs
>  // ~~Assuming slowest ethereum opcode is SSTORE, with gas price of 20000 as our worst case~~
Просто из коммента не ясно что оно уже исправлено, а ощущение, что это надо исправить

2023-08-14 11:19 UTC, mrshiposha approved these changes

2023-08-14 13:11 UTC, merged