feat(test xcm): added generic  `low level` xcm tests
UniqueNetwork/unique-chain pull request #999
Opened 2023-09-25 06:53 UTC by PraetorP

2023-09-25 15:41 UTC, mrshiposha requested changes

2023-09-25 15:41 UTC, mrshiposha commented on tests/src/xcm/lowLevelXcmUnique.test.ts
> +        const batchCall = helper.encodeApiCall('api.tx.utility.batch', [[xcmSend]]);
Можно напрямую отдать `xcmSend`, не используя batch, в данном случае

2023-09-25 15:41 UTC, mrshiposha commented on tests/src/xcm/lowLevelXcmUnique.test.ts
> +        const batchCall = helper.encodeApiCall('api.tx.utility.batch', [[xcmSend]]);
`Bypass the call filter` по идее сам Рут его обойдет

2023-09-25 15:41 UTC, mrshiposha commented on tests/src/xcm/lowLevelXcmUnique.test.ts
> +        const batchCall = helper.encodeApiCall('api.tx.utility.batch', [[xcmSend]]);
Таким же образом стоит изменить и в других местах

2023-09-25 15:41 UTC, mrshiposha commented on tests/src/xcm/lowLevelXcmUnique.test.ts
> +        await helper.fastDemocracy.executeProposal('sending MoonBeam -> Unique via XCM program', batchCall);
Надо бы вместо MoonBeam использовать имя, выбранной в данный момент, сети

2023-09-25 15:41 UTC, mrshiposha commented on tests/src/xcm/lowLevelXcmUnique.test.ts
> +        await helper.fastDemocracy.executeProposal('sending MoonBeam -> Unique via XCM program', batchCall);
И так же в других местах

2023-09-25 15:41 UTC, mrshiposha commented on tests/src/xcm/lowLevelXcmUnique.test.ts
> +  const uniqueAssetId = {
Может быть тоже уберем это все в глобальную область видимости?
Это часто используется

2023-09-25 15:41 UTC, mrshiposha commented on tests/src/xcm/lowLevelXcmUnique.test.ts
> +  const uniqueAssetId = {
И в `Concrete` просто передать `uniqueMultilocation`

2023-09-25 15:41 UTC, mrshiposha commented on tests/src/xcm/lowLevelXcmUnique.test.ts
> +      if(!isWhitelisted) {
Мне понравилось как другие тесты сообщают о том, что ассет уже зарегистрирован. Мб здесь тоже об этом прологгируем?

2023-09-25 15:41 UTC, mrshiposha commented on tests/src/xcm/lowLevelXcmUnique.test.ts
> +      await helper.getSudo().xcm.setSafeXcmVersion(alice, SAFE_XCM_VERSION);
По идее эта вещь должна быть в каждом before

2023-09-26 06:04 UTC, PraetorP commented on tests/src/xcm/lowLevelXcmUnique.test.ts
> +const SAFE_XCM_VERSION = 2;
Я еще это в прошлое наше обсуждение предлагал )

2023-09-26 06:19 UTC, PraetorP commented on tests/src/xcm/lowLevelXcmUnique.test.ts
> +      await helper.getSudo().xcm.setSafeXcmVersion(alice, SAFE_XCM_VERSION);
`setSafeXcmVersion` ? она есть в каждом `describe`-> `before` .

2023-09-26 08:16 UTC, mrshiposha commented on tests/src/xcm/lowLevelXcmUnique.test.ts
> +      await helper.getSudo().xcm.setSafeXcmVersion(alice, SAFE_XCM_VERSION);
Хмм, мне показалось где-то пропущено. Но, перепроверив, я вижу что везде есть. Сорри.

2023-09-26 08:31 UTC, PraetorP commented on tests/src/xcm/lowLevelXcmUnique.test.ts
> +      await helper.getSudo().xcm.setSafeXcmVersion(alice, SAFE_XCM_VERSION);
Тут много чего нового - у меня была возможность что то пропустить ) Спасибо за внимательное ревью! Лучше перестраховаться .

2023-09-26 10:06 UTC, mrshiposha commented on tests/src/xcm/lowLevelXcmUnique.test.ts
> +        const batchCall = helper.encodeApiCall('api.tx.utility.batch', [[xcmSend]]);
Note: судя по всему без `utility.batch` фильтр обойти действительно нельзя.
Возможно, стоит копнуть глубже потом, но пока что, мне кажется, можем оставить как есть

2023-09-27 08:29 UTC, mrshiposha requested changes

2023-09-27 08:29 UTC, mrshiposha commented on tests/src/xcm/lowLevelXcmUnique.test.ts
> +async function genericRejectNativeToknsFrom(netwokrName: keyof typeof NETWORKS, sudoerOnTargetChain: IKeyringPair) {
```suggestion
async function genericRejectNativeTokensFrom(networkName: keyof typeof NETWORKS, sudoerOnTargetChain: IKeyringPair) {
```

2023-09-27 08:29 UTC, mrshiposha commented on tests/src/xcm/lowLevelXcmUnique.test.ts
> +        Concrete: {
Хочется воспользоваться `uniqueAssetId` во всех подобных местах

2023-09-27 08:42 UTC, mrshiposha commented on tests/src/xcm/lowLevelXcmUnique.test.ts
> +        Concrete: {
Note: отложили на другой PR

2023-09-27 09:03 UTC, PraetorP commented on tests/src/xcm/lowLevelXcmUnique.test.ts
> +        Concrete: {
Мы друг друга не совсем поняли - правки для `Concrete` в я сделал в этом . Единственное, для ll - это излишнее , поскольку потом всеравно делать с учетом тестируемой сети.

2023-09-27 09:20 UTC, mrshiposha approved these changes

2023-09-28 08:37 UTC, merged